// Add future games here. Paths are relative to the portal's index.html.
// Each game lives in games/<id>/ and has its own index.html.
export const games = [
  {
    id: 'barcraft',
    title: 'Barcraft',
    subtitle: 'Find your flow.',
    description: 'Catch a beat and turn word prompts into your next great bar. Pass the mic, chase a rhyme, and see who finds their flow.',
    category: 'Music & wordplay',
    players: 'Solo or take turns',
    duration: '2–5 min per round',
    path: 'games/barcraft/',
    artwork: 'art/barcraft.svg',
    color: '#c8b7fb',
    features: ['Eight beats', 'Rhyme chains', 'Freestyle'],
    available: true
  },
  {id:'wavelength',title:'Wavelength',subtitle:'Get on the same wavelength.',description:'One private target. One perfect clue. Move your dial, talk it out, and see how close the room can get.',category:'Clues & intuition',players:'2–16 players · Shared party',duration:'15–25 min',path:'games/wavelength/',artwork:'art/wavelength.svg',color:'#edb396',features:['Private targets','Group dial','Five-character code'],available:true},
  {id:'imposter',title:'Imposter',subtitle:'Someone is playing along.',description:'Everyone knows the secret word. Except one of you. Trade subtle clues, find the bluff, and vote before they figure it out.',category:'Bluffing & deduction',players:'3–16 players · Shared party',duration:'10–20 min',path:'games/imposter/',artwork:'art/imposter.svg',color:'#b4c7b5',features:['Secret roles','Private votes','Five-character code'],available:true},
  {id:'scattergories',title:'Scattergories',subtitle:'Beat the clock. Be original.',description:'One letter, twelve categories, two minutes. Find answers nobody else picks, then compare your lists and settle the score.',category:'Words & quick thinking',players:'2–16 players · Shared party',duration:'15–20 min',path:'games/scattergories/',artwork:'art/scattergories.svg',color:'#c8b7fb',features:['451 categories','Private answer sheets','Live scoring'],available:true},
  {id:'hivemind',title:'Hive Mind',subtitle:'Think like your people.',description:'Choose a question, write your answers, and match the room. The least aligned groups move toward the edge of the hive.',category:'Matching & intuition',players:'3–16 players · Shared party',duration:'20–45 min',path:'games/hivemind/',artwork:'art/hivemind.svg',color:'#e2c888',features:['Survival board','697 questions','Custom questions'],available:true},
  {id:'apples',title:'Apples to Apples',subtitle:'Make the perfect comparison.',description:'A green adjective. Seven red cards. Find the comparison your judge will love, from clever to delightfully ridiculous.',category:'Comparisons & judging',players:'4–16 players · Shared party',duration:'20–35 min',path:'games/apples/',artwork:'art/apples.svg',color:'#b4c7b5',features:['Private hands','Original large deck','Rotating judge'],available:true},
  {id:'humanity',title:'Cards Against Humanity',subtitle:'Make the room lose it.',description:'Fill a questionable prompt with an even more questionable response. Play in secret, then let the Card Czar choose the funniest.',category:'Adult humor & judging',players:'4–16 players · Shared party',duration:'15–45 min',path:'games/humanity/',artwork:'art/humanity.svg',color:'#c8b7fb',features:['Original adult deck','Pick 2 combinations','Free play'],available:true},
  {id:'word-circuit',title:'Word Circuit',subtitle:'One letter changes everything.',description:'Connect two words, one letter at a time. Every step is verified. Find a route, then make it shorter before the clock runs out.',category:'Logic & wordplay',players:'1–16 players · Shared party',duration:'3 min per round',path:'games/word-circuit/',artwork:'art/word-circuit.svg',color:'#b4c7b5',features:['5,400 solvable pairs','16,604-word dictionary','Solo or race'],available:true},
  {id:'sudoku-race',title:'Sudoku Race',subtitle:'Same grid. First to finish.',description:'Race your friends through the same unique-solution Sudoku. Private grids, pencil notes, live progress, and three levels of challenge.',category:'Logic & numbers',players:'1–16 players · Shared party',duration:'10–20 min per round',path:'games/sudoku-race/',artwork:'art/sudoku-race.svg',color:'#a9cadd',features:['450 unique puzzles','Pencil notes','Solo or race'],available:true},
  {id:'desktop-disaster',title:'Desktop Disaster',subtitle:'Just one simple task.',description:'Finish a task on a fake desktop while your friends deploy popups, errors, notifications, and slippery buttons. Beat the clock. Survive the clicks.',category:'Sabotage & chaos',players:'2–16 players · Shared party',duration:'15–30 min',path:'games/desktop-disaster/',artwork:'art/desktop-disaster.svg',color:'#a9cadd',features:['Five task types','Secret gadget channels','Live traps'],available:true},
  {"id":"rulebreakers","title":"Rulebreakers","subtitle":"Test words. Discover the rule.","description":"Find a hidden spelling rule by testing words and learning from counterexamples.","category":"Deduction & discovery","players":"2\u201316 players \u00b7 Shared party","duration":"5\u20136 min per round","path":"games/rulebreakers/","artwork":"art/rulebreakers.svg","color":"#b4c7b5","features":["8,244 distinct rules","16,579 dictionary words","Private experiments"],"available":true},
  {"id":"alien-dictionary","title":"Alien Dictionary","subtitle":"Study examples. Translate eight phrases.","description":"Study examples, decode unfamiliar words, and translate a brand-new language.","category":"Deduction & discovery","players":"2\u201316 players \u00b7 Shared party","duration":"5\u20136 min per round","path":"games/alien-dictionary/","artwork":"art/alien-dictionary.svg","color":"#a9cadd","features":["Fresh languages","Eight translations","Grammar puzzles"],"available":true},
  {"id":"question-quest","title":"Question Quest","subtitle":"Ask questions. Narrow the suspects.","description":"Find the responsible visitor using yes/no questions and a limited question budget.","category":"Deduction & discovery","players":"2\u201316 players \u00b7 Shared party","duration":"5\u20136 min per round","path":"games/question-quest/","artwork":"art/question-quest.svg","color":"#edb396","features":["3,200 case setups","Generated suspect boards","Question budget"],"available":true},
{"id": "quiz-after-dark", "title": "Quiz After Dark", "subtitle": "Trust your questionable instincts.", "description": "Fast trivia, tricky questions, and one screw to sabotage an opponent.", "category": "Jackbox Games", "players": "2–16 players · Shared parties", "duration": "10–25 min", "path": "games/quiz-after-dark/", "artwork": "art/quiz-after-dark.svg", "color": "#edb396", "features": ["Speed scoring", "One screw per game", "717 trivia questions"], "available": true, "inspiredBy": "YDKJ"},
{"id": "punchline", "title": "Punchline", "subtitle": "Make the room laugh.", "description": "Two writers. One funny prompt. Vote for the response that deserves the laugh.", "category": "Jackbox Games", "players": "2–16 players · Shared parties", "duration": "10–25 min", "path": "games/punchline/", "artwork": "art/punchline.svg", "color": "#c8b7fb", "features": ["9,600 prompts", "Anonymous matchups", "Two-player house mode"], "available": true, "inspiredBy": "Quiplash"},
{"id": "fact-or-fiction", "title": "Fact or Fiction", "subtitle": "Lie like you mean it.", "description": "Invent believable missing answers to real facts, then find the truth among the bluffs.", "category": "Jackbox Games", "players": "2–16 players · Shared parties", "duration": "10–25 min", "path": "games/fact-or-fiction/", "artwork": "art/fact-or-fiction.svg", "color": "#b4c7b5", "features": ["121 real facts", "Player-written bluffs", "Truth reveals"], "available": true, "inspiredBy": "Fibbage"},
{"id": "doodle-bluff", "title": "Doodle Bluff", "subtitle": "Terrible art. Excellent guesses.", "description": "Draw a strange private prompt, invent fake captions, and guess the original.", "category": "Jackbox Games", "players": "2–16 players · Shared parties", "duration": "10–25 min", "path": "games/doodle-bluff/", "artwork": "art/doodle-bluff.svg", "color": "#a9cadd", "features": ["6,000 drawing prompts", "Touch drawing", "Caption bluffing"], "available": true, "inspiredBy": "Drawful"},
{"id": "last-laugh-trivia", "title": "Last Laugh Trivia", "subtitle": "Know it. Or survive it.", "description": "Wrong answers lead to traps. Survive memory and number challenges, then race your friends toward escape.", "category": "Jackbox Games", "players": "2–16 players · Shared parties", "duration": "10–25 min", "path": "games/last-laugh-trivia/", "artwork": "art/last-laugh-trivia.svg", "color": "#ddafd0", "features": ["Three trap types", "Ghost comebacks", "Escape race"], "available": true, "inspiredBy": "Trivia Murder Party"},
{"id": "thread-battle", "title": "Thread Battle", "subtitle": "Wear your worst ideas.", "description": "Make drawings and slogans, remix them into shirts, and vote for the best design.", "category": "Jackbox Games", "players": "2–16 players · Shared parties", "duration": "10–25 min", "path": "games/thread-battle/", "artwork": "art/thread-battle.svg", "color": "#e2c888", "features": ["Touch drawing", "Shirt remixes", "Shared creator points"], "available": true, "inspiredBy": "Tee K.O."}
];
