import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
const raw=await readFile(new URL('../api/rulebreakers-data.php',import.meta.url),'utf8');
const data=JSON.parse(raw.split("<<<'RULES'\n")[1].split('\nRULES')[0]);
const byId=new Map(data.atoms.map(a=>[a.id,a]));
function predicate(atom,w){const {kind:k,arg:a}=atom,vowels=[...w].filter(c=>'aeiou'.includes(c));switch(k){
 case 'length':return w.length===a;case 'vowels':return vowels.length===a;case 'atleastvowels':return vowels.length>=a;case 'unique':return new Set(w).size===a;case 'starts':return w.startsWith(a);case 'ends':return w.endsWith(a);case 'contains':case 'pair':return w.includes(a);case 'count':return [...w].filter(c=>c===a).length===2;case 'even':return w.length%2===0;case 'vowelstart':return 'aeiou'.includes(w[0]);case 'vowelend':return 'aeiou'.includes(w.at(-1));case 'double':return [...w].some((c,i)=>i&&c===w[i-1]);case 'repeat':return new Set(w).size<w.length;case 'sameends':return w[0]===w.at(-1);case 'alphabet':return w[0]<w.at(-1);case 'vowelrun':return [...w].some((c,i)=>i&&'aeiou'.includes(c)&&'aeiou'.includes(w[i-1]));case 'consonantrun':return [...w].some((c,i)=>i>=2&&![w[i-2],w[i-1],c].some(v=>'aeiou'.includes(v)));case 'voweleven':return vowels.length%2===0;case 'uniquevowels':return vowels.length===new Set(vowels).size;case 'alternating':return [...w].every((c,i)=>!i||'aeiou'.includes(c)!=='aeiou'.includes(w[i-1]));default:throw Error(k);}}
function mask(rule){const a=Buffer.from(byId.get(rule.a).mask,'base64');if(rule.op==='single')return a;const b=Buffer.from(byId.get(rule.b).mask,'base64');for(let i=0;i<a.length;i++)a[i]=rule.op==='and'?a[i]&b[i]:rule.op==='or'?a[i]|b[i]:rule.op==='xor'?a[i]^b[i]:a[i]&~b[i];return a;}
const php=code=>JSON.parse(execFileSync('php',['-r',`require 'api/engine.php';${code}`],{cwd:new URL('..',import.meta.url),maxBuffer:64*1024*1024,timeout:30000}).toString());
test('all 244 Rulebreakers conditions classify every dictionary word correctly',()=>{
 assert.equal(data.words.length,16579);assert.equal(new Set(data.words).size,data.words.length);assert.equal(data.atoms.length,244);
 for(const atom of data.atoms){const bits=Buffer.from(atom.mask,'base64');let passing=0;for(let i=0;i<data.words.length;i++){const actual=!!(bits[i>>3]&(1<<(i%8)));assert.equal(actual,predicate(atom,data.words[i]),`${atom.text}: ${data.words[i]}`);passing+=Number(actual);}assert.ok(passing>=32&&passing<=data.words.length-32);}
});
test('all 8,244 rule puzzles have distinct classifications and both passing and failing words',()=>{
 const seen=new Set();const pop=Array.from({length:256},(_,i)=>i.toString(2).replaceAll('0','').length);let count=0;
 for(const [difficulty,deck] of Object.entries(data.decks))for(const rule of deck){const bits=mask(rule);const fingerprint=createHash('sha256').update(bits).digest('hex');assert.ok(!seen.has(fingerprint),rule.id);seen.add(fingerprint);let yes=0;for(const b of bits)yes+=pop[b];assert.ok(yes>=32&&yes<data.words.length-31);assert.ok(difficulty==='easy'?rule.op==='single':difficulty==='classic'?['and','or'].includes(rule.op):['xor','andnot'].includes(rule.op));count++;}assert.equal(count,8244);
});
function translate(meaning,language){const groups=[[]];let verb;for(const t of meaning){if(t.kind==='verb'){verb=t;groups.push([]);}else groups.at(-1).push(t);}const phrases=groups.map(g=>language.phraseOrder.flatMap(k=>g.filter(t=>t.kind===k).map(t=>t.alien)));if(!verb)return phrases[0];const parts={S:phrases[0],V:[verb.alien],O:phrases[1]};return [...language.sentenceOrder].flatMap(k=>parts[k]);}
test('300 generated alien languages have identifiable lexicons, consistent grammar and unique answer choices',()=>{
 const puzzles=php('$out=[];foreach(["easy","classic","expert"] as $d)for($i=0;$i<100;$i++)$out[]=party_alien_puzzle($d);echo json_encode($out);');
 for(const p of puzzles){const terms=Object.values(p.language.lexicon).flat();assert.equal(new Set(terms.map(t=>t.alien)).size,terms.length);const signatures=terms.map(t=>p.examples.map(e=>e.alien.includes(t.alien)?'1':'0').join(''));assert.equal(new Set(signatures).size,terms.length);assert.ok(signatures.every(s=>s.replaceAll('0','').length>=2));for(const e of p.examples)assert.deepEqual(e.alien,translate(e.meaning,p.language));assert.equal(p.challenges.length,8);const targets=new Set();for(const q of p.challenges){assert.equal(q.options.length,6);assert.equal(new Set(q.options.map(o=>o.english)).size,6);assert.equal(new Set(q.options.map(o=>o.alien.join('|'))).size,6);assert.ok(!targets.has(q.english));targets.add(q.english);assert.equal(q.options[q.correct].english,q.english);assert.deepEqual(q.options[q.correct].alien,q.alien);}}
});
test('Question Quest offers 3,200 distinct cases and every generated suspect is identifiable within the question budget',()=>{
 const result=php('$fields=party_quest_fields();$out=[];foreach([16,24,36] as $n)for($i=0;$i<40;$i++)$out[]=party_quest_roster($n,$fields);echo json_encode(["stories"=>party_quest_stories(),"rosters"=>$out]);');assert.equal(result.stories.length,3200);assert.equal(new Set(result.stories.map(s=>s.key)).size,3200);assert.equal(new Set(result.stories.map(s=>s.title+'|'+s.text)).size,3200);
 for(const roster of result.rosters){assert.equal(new Set(roster.map(p=>p.name)).size,roster.length);assert.equal(new Set(roster.map(p=>Object.values(p.traits).join('|'))).size,roster.length);for(const target of roster){let possible=roster;let cost=0;for(const field of ['time','color']){while(possible.length>1){const values=[...new Set(possible.map(p=>p.traits[field]))];if(values.length===1)break;const group=values.slice(0,values.length<=3?1:Math.min(4,Math.floor(values.length/2)));const yes=group.includes(target.traits[field]);possible=possible.filter(p=>group.includes(p.traits[field])===yes);cost+=group.length===1?1:2;}}assert.equal(possible.length,1);assert.equal(possible[0].id,target.id);assert.ok(cost+2<=(roster.length===16?14:12));}}
});
