import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile,writeFile,cp,mkdir,readdir} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
let server,base,webroot,dataRoot;
before(async()=>{const temp=await mkdtemp(path.join(os.tmpdir(),'party-room-test-'));dataRoot=path.join(temp,'private-rooms');webroot=path.join(temp,'public_html');await mkdir(webroot);await cp('release/party-room',path.join(webroot,'friends','friday'),{recursive:true});const port=18000+Math.floor(Math.random()*2000);base=`http://127.0.0.1:${port}/friends/friday/`;server=spawn('php',['-S',`127.0.0.1:${port}`,'-t',webroot],{env:{...process.env,PARTY_ROOM_DATA_DIR:dataRoot},stdio:'ignore'});for(let n=0;n<50;n++){try{await fetch(base);return;}catch{await new Promise(r=>setTimeout(r,100));}}throw Error('PHP test server did not start');});
after(()=>server?.kill());
async function api(action,session={},payload={},status=200){const response=await fetch(base+'api/room.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,...payload,action})});const body=await response.json();assert.equal(response.status,status,JSON.stringify(body));return body;}
async function create(game,count){const first=await api('create',{}, {game,name:'Host'});assert.match(first.session.code,/^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{5}$/);const sessions=[first.session];for(let n=1;n<count;n++)sessions.push((await api('join',{}, {game,code:first.session.code.toLowerCase(),name:`Friend ${n}`})).session);assert.equal(new Set(sessions.map(s=>s.token)).size,count);return sessions;}
const act=async(s,a,p={},status=200)=>(await api(a,s,p,status)).room;
test('renamed nested folder: pages, return routes, modules, audio, artwork and fonts resolve',async()=>{
 const extra=['quiz-after-dark','punchline','fact-or-fiction','doodle-bluff','last-laugh-trivia','thread-battle'].map(g=>`games/${g}/`);const roots=['','games/barcraft/','games/wavelength/?room=ABCDE','games/imposter/?room=ABCDE','games/scattergories/?room=ABCDE','games/hivemind/?room=ABCDE','games/apples/?room=ABCDE','games/humanity/?room=ABCDE','games/desktop-disaster/?room=ABCDE','games/word-circuit/?room=ABCDE','games/sudoku-race/?room=ABCDE','games/rulebreakers/?room=ABCDE','games/alien-dictionary/?room=ABCDE','games/question-quest/?room=ABCDE',...extra];
 for(const route of roots){const url=new URL(route,base),response=await fetch(url);assert.equal(response.status,200);const html=await response.text();for(const m of html.matchAll(/(?:href|src)="([^"]+)"/g)){if(m[1].startsWith('#')||m[1].startsWith('https:'))continue;const asset=await fetch(new URL(m[1],url));assert.equal(asset.status,200,`${route}: ${m[1]}`);}}
 const shared=await readFile('shared/party-client.js','utf8');assert.match(shared,/new URL\('\.\.\/api\/room.php',import.meta.url\)/);
 for(const route of ['art/wavelength.svg','art/imposter.svg','shared/party-ui.js','shared/game-tools.js','games/wavelength/style.css','games/imposter/app.js','fonts/dm-sans-400.ttf','games/barcraft/audio/griphop.mp3']){const res=await fetch(base+route);if(route.endsWith('griphop.mp3')){assert.equal(res.status,200);await res.body.cancel();}else{assert.equal(res.status,200,route);await res.arrayBuffer();}}
 const apiGet=await fetch(base+'api/room.php');assert.equal(apiGet.status,405);
});
test('Wavelength private targets, synchronized guesses, median scoring and round rotation',async()=>{
 const s=await create('wavelength',3);await act({...s[0],token:'bad'},'state',{},401);await act(s[1],'start',{},403);
 let room=await act(s[0],'start');assert.equal(room.phase,'clue');const giver=s.find(p=>p.id===room.giver),others=s.filter(p=>p.id!==giver.id);const secret=await act(giver,'state');assert.equal(typeof secret.target,'number');const redacted=await act(others[0],'state');assert.equal('target' in redacted,false);assert.equal(JSON.stringify(redacted).includes('token'),false);
 await act(others[0],'clue',{clue:'Coffee'},403);await act(giver,'clue',{clue:'Coffee'});await act(giver,'guess',{value:50},403);await act(others[0],'guess',{value:secret.target-2});await act(others[1],'guess',{value:secret.target+2});room=await act(s[0],'reveal');assert.equal(room.phase,'reveal');assert.equal(room.result.points,4);assert.equal(room.totalScore,4);assert.ok(Math.abs(room.result.guess-secret.target)<0.00001);assert.equal((await act(others[0],'state')).target,secret.target);await act(s[0],'reveal',{},409);
 room=await act(s[0],'next');assert.equal(room.round,2);assert.notEqual(room.giver,giver.id);await act(s[0],'skip',{round:1},409);await act(s[0],'skip');await act(s[0],'reset');
});
test('Imposter secret roles, turn order, locked private ballots, caught imposter final guess',async()=>{
 const s=await create('imposter',3);let room=await act(s[0],'start',{category:'Food'});const views=await Promise.all(s.map(p=>act(p,'state')));const imp=s[views.findIndex(v=>v.role==='imposter')],informed=s.filter(p=>p.id!==imp.id),word=views.find(v=>v.word).word;assert.equal(views.filter(v=>v.role==='imposter').length,1);assert.equal('word' in views.find(v=>v.role==='imposter'),false);assert.equal('imposter' in room,false);
 for(const id of room.order){const current=s.find(p=>p.id===id);await act(current,'clue',{clue:`hint ${id.slice(0,3)}`});}room=await act(s[0],'state');assert.equal(room.phase,'vote');await act(informed[0],'vote',{suspect:imp.id});await act(informed[0],'vote',{suspect:imp.id},409);const other=await act(imp,'state');assert.equal(other.voteCount,1);assert.equal('votes' in other,false);assert.equal(other.yourVote,null);await act(informed[1],'vote',{suspect:imp.id});room=await act(imp,'vote',{suspect:informed[0].id});assert.equal(room.phase,'last_guess');assert.equal('word' in room,false);await act(informed[0],'final_guess',{guess:word},403);room=await act(imp,'final_guess',{guess:'Definitely not a food'});assert.equal(room.phase,'reveal');assert.equal(room.word,word);assert.equal(room.imposter,imp.id);assert.equal(room.result.imposterWins,false);assert.equal(room.players.find(p=>p.id===imp.id).score,0);assert.equal(room.players.find(p=>p.id===informed[0].id).score,1);
 room=await act(s[0],'next');const newViews=await Promise.all(s.map(p=>act(p,'state')));assert.notEqual(newViews.find(v=>v.role==='imposter').you,imp.id);assert.notEqual(newViews.find(v=>v.word).word,word);
});
test('Imposter tied vote gives the imposter the round; late arrivals wait until next round',async()=>{
 const s=await create('imposter',3);let room=await act(s[0],'start');const late=(await api('join',{}, {game:'imposter',code:s[0].code,name:'Late friend'})).session;await act(late,'clue',{clue:'Hello'},403);for(const id of room.order)await act(s.find(p=>p.id===id),'clue',{clue:'Maybe'});for(let n=0;n<3;n++)room=await act(s[n],'vote',{suspect:s[(n+1)%3].id});assert.equal(room.phase,'reveal');assert.equal(room.result.accused,null);assert.equal(room.result.imposterWins,true);assert.equal(room.players.filter(p=>p.score===2).length,1);room=await act(s[0],'next');assert.ok(room.participants.includes(late.id));
});
test('complete sessions finish once, can restart, and transfer hosting when a host leaves',async()=>{
 for(const game of ['wavelength','imposter']){const s=await create(game,game==='wavelength'?2:3);let room=await act(s[0],'start');for(let round=1;round<=room.maxRounds;round++){assert.equal(room.round,round);if(game==='wavelength'){const giver=s.find(p=>p.id===room.giver),other=s.find(p=>p.id!==room.giver);const target=(await act(giver,'state')).target;await act(giver,'clue',{clue:'A fresh idea'});await act(other,'guess',{value:target});room=await act(s[0],'reveal');}else{for(const id of room.order)await act(s.find(p=>p.id===id),'clue',{clue:'Something subtle'});for(let i=0;i<s.length;i++)room=await act(s[i],'vote',{suspect:s[(i+1)%s.length].id});}room=await act(s[0],'next');}assert.equal(room.phase,'finished');if(game==='wavelength')assert.equal(room.totalScore,32);room=await act(s[0],'again');assert.equal(room.round,1);await act(s[0],'leave');room=await act(s[1],'state');assert.equal(room.host,s[1].id);await act(s[1],'skip');await act(s[1],'reset');assert.equal((await act(s[1],'state')).phase,'lobby');}
});
test('Scattergories keeps sheets private, locks submissions, scores duplicates and supports host review',async()=>{
 const s=await create('scattergories',3);let room=await act(s[0],'start');assert.equal(room.phase,'writing');assert.equal(room.categories.length,12);assert.equal(new Set(room.categories).size,12);assert.match(room.letter,/^[A-Z]$/);const prefix=room.letter;const values=[`${prefix}Shared`,`${prefix}Unique`,`${prefix}Good`,'1wrong'];await act(s[0],'answers',{answers:values});const hidden=await act(s[1],'state');assert.equal('answers' in hidden,false);assert.deepEqual(hidden.yourAnswers,[]);assert.equal(hidden.result,null);
 await act(s[0],'submit',{answers:values});await act(s[0],'answers',{answers:values},409);await act(s[1],'submit',{answers:[`The ${prefix.toLowerCase()}shared`,`${prefix}Other`,`${prefix}Second`,'']});room=await act(s[2],'submit',{answers:['',`${prefix}Third`,'','']});assert.equal(room.phase,'reveal');assert.equal(room.result.details[s[0].id][0].status,'duplicate');assert.equal(room.result.details[s[1].id][0].status,'duplicate');assert.equal(room.result.details[s[0].id][3].status,'letter');assert.equal(room.result.scores[s[0].id],2);assert.equal(room.result.scores[s[1].id],2);assert.equal(room.result.scores[s[2].id],1);assert.equal(room.players.find(p=>p.id===s[0].id).score,2);
 await act(s[1],'review',{player:s[0].id,index:1,accepted:false},403);room=await act(s[0],'review',{player:s[0].id,index:1,accepted:false});assert.equal(room.result.scores[s[0].id],1);assert.equal(room.players.find(p=>p.id===s[0].id).score,1);room=await act(s[0],'review',{player:s[0].id,index:1,accepted:false});assert.equal(room.players.find(p=>p.id===s[0].id).score,1);room=await act(s[0],'review',{player:s[0].id,index:1,accepted:true});assert.equal(room.players.find(p=>p.id===s[0].id).score,2);const oldCategories=room.categories,oldLetter=room.letter;room=await act(s[0],'next');assert.equal(room.round,2);assert.notEqual(room.letter,oldLetter);assert.ok(room.categories.every(v=>!oldCategories.includes(v)));assert.deepEqual((await act(s[1],'state')).yourAnswers,[]);
});
test('Scattergories server timer reveals the latest saved answers and rejects late edits',async()=>{
 const s=await create('scattergories',2);let room=await act(s[0],'start');await act(s[0],'answers',{answers:[`${room.letter}example`]});const file=path.join(dataRoot,s[0].code+'.json'),stored=JSON.parse(await readFile(file));stored.deadline=Math.floor(Date.now()/1000)-1;await writeFile(file,JSON.stringify(stored));room=await act(s[1],'state');assert.equal(room.phase,'reveal');assert.equal(room.answers[s[0].id][0],`${room.letter}example`);assert.equal(room.result.scores[s[0].id],1);await act(s[0],'answers',{answers:['Late']},409);assert.equal((await act(s[0],'state')).players.find(p=>p.id===s[0].id).score,1);
});
test('Scattergories plays all six rounds and reaches a fresh session with zero scores',async()=>{
 const s=await create('scattergories',2);let room=await act(s[0],'start');const used=new Set();for(let round=1;round<=6;round++){assert.equal(room.round,round);assert.ok(room.categories.every(v=>!used.has(v)));room.categories.forEach(v=>used.add(v));await act(s[0],'submit',{answers:[`${room.letter}first`]});await act(s[1],'submit',{answers:[`${room.letter}second`]});room=await act(s[0],'next');}assert.equal(room.phase,'finished');assert.deepEqual(room.players.map(p=>p.score),[6,6]);room=await act(s[0],'again',{recent:[...used]});assert.equal(room.round,1);assert.ok(room.categories.every(v=>!used.has(v)));assert.deepEqual(room.players.map(p=>p.score),[0,0]);
});
test('all imported modules, local music tracks and CSS font assets exist in the deployable folder',async()=>{
 const files=await readdir('release/party-room',{recursive:true}),local=[];
 for(const file of files){if(!/\.(js|css)$/.test(file))continue;const source=await readFile(path.join('release/party-room',file),'utf8');const matches=[...source.matchAll(/from\s+['"]([^'"]+)['"]/g),...source.matchAll(/url\(['"]?([^)'"\s]+)['"]?\)/g)];for(const m of matches){if(!m[1].startsWith('http')&&!m[1].startsWith('data:'))local.push(new URL(m[1],new URL(file.replaceAll(path.sep,'/'),base)));}}
 const {games}=await import('../games.js');for(const game of games){local.push(new URL(game.path,base),new URL(game.artwork,base));}for(const file of files.filter(v=>v.endsWith('.mp3')))local.push(new URL(file.replaceAll(path.sep,'/'),base));
 for(const url of local){const res=await fetch(url);assert.equal(res.status,200,url.href);await res.body.cancel();}
});
test('recent spectra and secret words supplied by a returning host are avoided in new games',async()=>{
 const w=await create('wavelength',2);let room=await act(w[0],'start');const spectrum=room.spectrum.join(' | ');await act(w[0],'reset');room=await act(w[0],'start',{recent:[spectrum]});assert.notEqual(room.spectrum.join(' | '),spectrum);
 const i=await create('imposter',3);room=await act(i[0],'start',{category:'Food'});const views=await Promise.all(i.map(p=>act(p,'state'))),word=views.find(v=>v.word).word;await act(i[0],'reset');await act(i[0],'start',{category:'Food',recent:[word]});const newViews=await Promise.all(i.map(p=>act(p,'state')));assert.notEqual(newViews.find(v=>v.word).word,word);
});
async function editRoom(session,update){const file=path.join(dataRoot,session.code+'.json'),stored=JSON.parse(await readFile(file));update(stored);stored.version++;await writeFile(file,JSON.stringify(stored));}
test('Hive Mind private multi-answer lists, plural matches, synonym review and survival movement',async()=>{
 const s=await create('hivemind',3);let room=await act(s[0],'start',{levels:6});assert.equal(room.phase,'question');assert.equal(room.questionOptions.length,3);assert.equal('questionOptions' in await act(s[1],'state'),false);await act(s[1],'question',{index:0},403);await act(s[0],'question',{custom:'Name three ordinary things.',count:3});await editRoom(s[0],r=>{r.die={dots:1,star:false};});await act(s[0],'answer',{answers:['dog','cats','rock']});let hidden=await act(s[1],'state');assert.deepEqual(hidden.yourAnswers,[]);assert.equal(hidden.result,null);assert.equal('answers' in hidden,false);await act(s[0],'submit',{answers:['dog','cats','rock']});await act(s[1],'submit',{answers:['dogs','cat','stone']});room=await act(s[2],'submit',{answers:['dog','cat','fish']});assert.equal(room.phase,'reveal');assert.deepEqual(Object.values(room.result.scores),[7,7,7]);await act(s[1],'merge',{from:'rock',to:'stone'},403);room=await act(s[0],'merge',{from:'rock',to:'stone'});assert.deepEqual(Object.values(room.result.scores),[8,8,7]);assert.equal(room.result.levels[s[2].id],1);assert.equal(room.levels[s[2].id],0);room=await act(s[0],'next');assert.equal(room.levels[s[2].id],1);assert.equal(room.active,s[1].id);assert.equal(room.phase,'question');assert.equal(room.maxRounds,0);
 await act(s[1],'question',{custom:'Name two things.',count:2});await editRoom(s[0],r=>{r.die={dots:1,star:false};for(const id of r.participants)r.levels[id]=5;});for(const player of s)room=await act(player,'submit',{answers:['sun','moon']});assert.deepEqual(Object.values(room.result.levels),[6,6,6]);room=await act(s[0],'next');assert.equal(room.phase,'finished');assert.deepEqual(room.winners,s.map(p=>p.id));
});
test('Apples private seven-card hands, anonymous shuffled judging, locked submissions and hand refill',async()=>{
 const s=await create('apples',4);let room=await act(s[0],'start');assert.equal(room.targetScore,8);assert.equal(room.hand.length,7);assert.equal(room.judge,s[0].id);const views=await Promise.all(s.map(p=>act(p,'state')));const all=views.flatMap(v=>v.hand.map(c=>c.id));assert.equal(new Set(all).size,28);await act(s[0],'play',{cards:[room.hand[0].id]},403);await act(s[1],'play',{cards:[room.hand[0].id]},403);await act(s[1],'play',{cards:[]},400);
 for(let i=1;i<4;i++){room=await act(s[i],'play',{cards:[views[i].hand[0].id]});if(i===1){assert.equal(room.hand.length,6);await act(s[i],'play',{cards:[views[i].hand[1].id]},409);const judge=await act(s[0],'state');assert.equal('choices' in judge,false);assert.equal('submissions' in judge,false);}}
 room=await act(s[0],'state');assert.equal(room.phase,'judging');assert.equal(room.choices.length,3);assert.ok(room.choices.every(c=>!('player' in c)));const chosen=room.choices.find(v=>v.texts[0]===views[1].hand[0].text);await act(s[1],'choose',{choice:chosen.id},403);room=await act(s[0],'choose',{choice:chosen.id});assert.equal(room.result.winner,s[1].id);assert.equal(room.players.find(p=>p.id===s[1].id).score,1);await act(s[0],'choose',{choice:chosen.id},403);room=await act(s[0],'next');assert.equal(room.judge,s[1].id);const refilled=await act(s[1],'state');assert.equal(refilled.hand.length,7);assert.ok(refilled.hand.every(c=>c.id!==views[1].hand[0].id));
});
test('Cards Against Humanity supports ordered Pick 2s, ten-card hands, winning targets and free play',async()=>{
 const s=await create('humanity',4);await act(s[0],'start',{target:5});await editRoom(s[0],r=>{r.prompt={text:'Combine _____ with _____.',pick:2};});const views=await Promise.all(s.map(p=>act(p,'state')));assert.ok(views.every(v=>v.hand.length===10));await act(s[1],'play',{cards:[views[1].hand[0].id,views[1].hand[0].id]},400);
 for(let i=1;i<4;i++)await act(s[i],'play',{cards:[views[i].hand[1].id,views[i].hand[0].id]});let room=await act(s[0],'state');assert.equal(room.phase,'judging');const chosen=room.choices.find(v=>v.texts[0]===views[1].hand[1].text);assert.deepEqual(chosen.texts,[views[1].hand[1].text,views[1].hand[0].text]);await editRoom(s[0],r=>{r.players.find(p=>p.id===s[1].id).score=4;});room=await act(s[0],'choose',{choice:chosen.id});assert.equal(room.result.gameOver,true);room=await act(s[0],'next');assert.equal(room.phase,'finished');assert.equal(room.players.find(p=>p.id===s[1].id).score,5);await act(s[0],'again',{target:0});let first=await act(s[0],'state');const activeViews=await Promise.all(s.map(p=>act(p,'state')));for(let i=1;i<4;i++)await act(s[i],'play',{cards:activeViews[i].hand.slice(0,first.prompt.pick).map(c=>c.id)});room=await act(s[0],'state');await act(s[0],'choose',{choice:room.choices[0].id});await act(s[1],'finish',{},403);room=await act(s[0],'finish');assert.equal(room.phase,'finished');
});
test('absent card judge can be replaced without judging their own submission',async()=>{
 const s=await create('apples',4);await act(s[0],'start');const views=await Promise.all(s.map(p=>act(p,'state')));for(let i=1;i<4;i++)await act(s[i],'play',{cards:[views[i].hand[0].id]});await act(s[0],'leave');let room=await act(s[1],'state');assert.equal(room.host,s[1].id);room=await act(s[1],'take_judge');assert.equal(room.judge,s[1].id);assert.equal(room.choices.length,2);assert.ok(room.choices.every(c=>c.texts[0]!==views[1].hand[0].text));room=await act(s[1],'choose',{choice:room.choices[0].id});assert.notEqual(room.result.winner,s[1].id);
});
test('Desktop Disaster roles, hidden gadget ownership, trap points, penalties and validated task completion',async()=>{
 const s=await create('desktop-disaster',2);let room=await act(s[0],'start');assert.equal(room.phase,'desktop');assert.equal(room.active,s[0].id);assert.equal(room.maxRounds,4);assert.equal('channels' in room,false);assert.equal('expected' in room.task.current,false);let sab=await act(s[1],'state');assert.equal(sab.channels.length,4);await act(s[1],'step',{step:0,value:'fake'},403);await act(s[0],'trap',{kind:'popup',index:0},403);await act(s[0],'step',{step:0,value:'fake'},400);
 await act(s[1],'trap',{kind:'popup',index:0});room=await act(s[0],'state');let trap=room.traps[0];assert.equal('owner' in trap,false);await act(s[0],'seen',{traps:[trap.id]});await act(s[0],'seen',{traps:[trap.id]});sab=await act(s[1],'state');assert.equal(sab.roundPoints,1);assert.equal(sab.players.find(p=>p.id===s[1].id).score,0);await act(s[0],'dismiss',{trap:trap.id});await editRoom(s[0],r=>{r.trapCooldown[s[1].id]=0;});await act(s[1],'trap',{kind:'error',index:0});room=await act(s[0],'state');trap=room.traps[0];const deadline=room.deadline;await act(s[0],'seen',{traps:[trap.id]});room=await act(s[0],'hit',{trap:trap.id});assert.equal(room.deadline,deadline-4);await act(s[0],'hit',{trap:trap.id},409);sab=await act(s[1],'state');assert.equal(sab.roundPoints,4);assert.equal(sab.yourStats.hits,1);
 const stored=JSON.parse(await readFile(path.join(dataRoot,s[0].code+'.json')));for(let step=0;step<4;step++)room=await act(s[0],'step',{step,value:stored.task.steps[step].expected});assert.equal(room.phase,'reveal');assert.equal(room.result.success,true);assert.equal(room.players.find(p=>p.id===s[1].id).score,4);assert.ok(room.players.find(p=>p.id===s[0].id).score>=10);assert.equal(room.result.channels[s[1].id].length,4);room=await act(s[0],'next');assert.equal(room.active,s[1].id);assert.notEqual(room.task.type,stored.task.type);
});
test('Desktop Disaster enforces assigned channels and timed-out rounds award sabotage bonuses once',async()=>{
 const s=await create('desktop-disaster',3);await act(s[0],'start');let sab=await act(s[1],'state');const forbidden=['popup','notification','error','buttons'].find(v=>!sab.channels.includes(v));await act(s[1],'trap',{kind:forbidden,index:0},403);await editRoom(s[0],r=>{r.deadline=Math.floor(Date.now()/1000)-1;});let room=await act(s[0],'state');assert.equal(room.phase,'reveal');assert.equal(room.result.success,false);assert.deepEqual(room.players.map(p=>p.score),[0,3,3]);room=await act(s[0],'state');assert.deepEqual(room.players.map(p=>p.score),[0,3,3]);
});
test('Hive timers reveal saved lists; a star lifts top scores and lowers only the bottom group',async()=>{
 const s=await create('hivemind',3);await act(s[0],'start',{levels:8});await act(s[0],'question',{custom:'Name two animals.',count:2});await editRoom(s[0],r=>{r.die={dots:1,star:true};for(const id of r.participants)r.levels[id]=2;});await act(s[0],'answer',{answers:['dog','cat']});await act(s[1],'answer',{answers:['dogs','cats']});await act(s[2],'answer',{answers:['goose','duck']});await editRoom(s[0],r=>{r.deadline=Math.floor(Date.now()/1000)-1;});let room=await act(s[0],'state');assert.equal(room.phase,'reveal');assert.deepEqual(Object.values(room.result.scores),[4,4,2]);assert.deepEqual(Object.values(room.result.levels),[1,1,3]);await act(s[0],'answer',{answers:['late','late']},409);
});
test('Hive matching bonuses apply once per meaning even when a list has equivalent answers',async()=>{
 const s=await create('hivemind',3);await act(s[0],'start');await act(s[0],'question',{custom:'Name three objects.',count:3});await act(s[0],'submit',{answers:['stone','rock','bird']});await act(s[1],'submit',{answers:['stone','rock','birds']});await act(s[2],'submit',{answers:['rock','bird','stone']});let room=await act(s[0],'merge',{from:'stone',to:'rock'});assert.deepEqual(Object.values(room.result.scores),[7,7,7]);
});
test('card-game submission and judging timers recover safely without awarding phantom points',async()=>{
 const s=await create('apples',4);await act(s[0],'start');const view=await act(s[1],'state');await act(s[1],'play',{cards:[view.hand[0].id]});await editRoom(s[0],r=>{r.deadline=Math.floor(Date.now()/1000)-1;});let room=await act(s[0],'state');assert.equal(room.phase,'judging');assert.equal(room.choices.length,1);await editRoom(s[0],r=>{r.deadline=Math.floor(Date.now()/1000)-1;});room=await act(s[0],'state');assert.equal(room.phase,'reveal');assert.equal(room.result.skipped,true);assert.ok(room.players.every(p=>p.score===0));await act(s[0],'next');await editRoom(s[0],r=>{r.deadline=Math.floor(Date.now()/1000)-1;});room=await act(s[0],'state');assert.equal(room.phase,'reveal');assert.equal(room.result.skipped,true);
});
test('twenty-five card rounds keep prompts and dealt responses fresh; new hosts carry recent history',async()=>{
 const s=await create('humanity',4);let room=await act(s[0],'start',{target:0});const prompts=[],cards=new Set();for(let round=1;round<=25;round++){assert.ok(!prompts.includes(room.prompt.text));prompts.push(room.prompt.text);const views=await Promise.all(s.map(p=>act(p,'state')));for(const view of views)for(const card of view.hand)cards.add(card.text);const judge=s.find(p=>p.id===room.judge);for(const player of s.filter(p=>p.id!==judge.id)){const hand=views.find(v=>v.you===player.id).hand;await act(player,'play',{cards:hand.slice(0,room.prompt.pick).map(c=>c.id)});}room=await act(judge,'state');await act(judge,'choose',{choice:room.choices[0].id});room=await act(s[0],'next');}assert.equal(room.round,26);assert.ok(cards.size>100);await act(s[0],'reset');room=await act(s[0],'start',{target:0,recent:[...prompts,...[...cards].map(v=>'card:'+v)]});assert.ok(!prompts.includes(room.prompt.text));assert.ok(room.hand.every(c=>!cards.has(c.text)));
});
test('Desktop task rotation gives everyone two active turns and ends with consistent scores',async()=>{
 const s=await create('desktop-disaster',2);let room=await act(s[0],'start');for(let round=1;round<=4;round++){assert.equal(room.round,round);assert.equal(room.active,s[(round-1)%2].id);const active=s.find(p=>p.id===room.active),stored=JSON.parse(await readFile(path.join(dataRoot,s[0].code+'.json')));for(let step=0;step<4;step++)room=await act(active,'step',{step,value:stored.task.steps[step].expected});assert.equal(room.phase,'reveal');room=await act(s[0],'next');}assert.equal(room.phase,'finished');assert.ok(room.players.every(p=>p.score>=20));
});
async function startRace(s,payload={}){await act(s[0],'start',payload);await editRoom(s[0],r=>{r.raceStarts=Date.now()/1000-10;});return act(s[0],'state');}
async function storedPuzzle(s){return JSON.parse(await readFile(path.join(dataRoot,s.code+'.json'))).puzzle;}
test('Word Circuit validates dictionary, exact letter changes, loops, private routes and shortest-route scoring',async()=>{
 const s=await create('word-circuit',2);let room=await act(s[0],'start',{difficulty:'easy',rounds:1});assert.equal(room.phase,'race');assert.equal('solution' in room.puzzle,false);assert.equal('paths' in room,false);await act(s[0],'word',{word:room.puzzle.start},409);await editRoom(s[0],r=>{r.raceStarts=Date.now()/1000-10;});await act(s[0],'word',{word:'zzzz'},400);await act(s[0],'word',{word:'too long'},400);await act(s[0],'word',{word:room.puzzle.start},400);
 const puzzle=await storedPuzzle(s[0]);for(const word of puzzle.solution.slice(1))room=await act(s[0],'word',{word:word.toUpperCase()});assert.deepEqual(room.bestPath,puzzle.solution);const hidden=await act(s[1],'state');assert.deepEqual(hidden.path,[puzzle.start]);assert.equal(hidden.bestPath,null);assert.ok(!JSON.stringify(hidden).includes('solution'));assert.equal(hidden.progress.find(p=>p.player===s[0].id).solved,true);await act(s[0],'word',{word:puzzle.solution.at(-2)},400);
 room=await act(s[0],'restart_path');assert.deepEqual(room.path,[puzzle.start]);assert.deepEqual(room.bestPath,puzzle.solution);await act(s[0],'lock');await act(s[0],'undo',{},409);room=await act(s[1],'give_up');assert.equal(room.phase,'reveal');assert.deepEqual(room.result.solution,puzzle.solution);assert.equal(room.result.scores[s[0].id],12);assert.equal(room.result.scores[s[1].id],0);assert.equal(room.players.find(p=>p.id===s[0].id).score,12);room=await act(s[0],'next');assert.equal(room.phase,'finished');
});
test('Word Circuit hints are private, bounded and charged; saved routes reveal on timeout only once',async()=>{
 const s=await create('word-circuit',2);let room=await startRace(s,{difficulty:'classic',rounds:3});const pair=room.puzzleKey;room=await act(s[0],'hint');assert.equal(room.hints,1);assert.ok(room.hint.word);assert.equal((await act(s[0],'hint')).hints,1);assert.equal((await act(s[1],'state')).hint,null);const route=(await storedPuzzle(s[0])).solution;await act(s[0],'word',{word:room.hint.word});await act(s[0],'undo');room=await act(s[0],'restart_path');for(const word of route.slice(1))room=await act(s[0],'word',{word});await editRoom(s[0],r=>{r.deadline=Date.now()/1000-1;});room=await act(s[1],'state');assert.equal(room.phase,'reveal');assert.equal(room.result.scores[s[0].id],10);const score=room.players.find(p=>p.id===s[0].id).score;assert.equal((await act(s[0],'state')).players.find(p=>p.id===s[0].id).score,score);await act(s[0],'hint',{},409);await act(s[0],'reset');room=await act(s[0],'start',{difficulty:'classic',recent:[pair]});assert.notEqual(room.puzzleKey,pair);
});
test('Word Circuit supports solo play, late spectators, recovery, host ending and validated options',async()=>{
 const s=await create('word-circuit',1);await act(s[0],'start',{difficulty:'bad'},400);await act(s[0],'start',{rounds:999},400);let room=await startRace(s,{difficulty:'expert',rounds:3});const late=(await api('join',{}, {game:'word-circuit',code:s[0].code,name:'Late'})).session;let view=await act(late,'state');assert.equal('path' in view,false);await act(late,'word',{word:room.puzzle.end},403);await act(late,'end_race',{},403);await act(s[0],'end_race');room=await act(s[0],'next');assert.ok(room.participants.includes(late.id));await act(s[0],'leave');room=await act(late,'state');assert.equal(room.host,late.id);
});
test('Sudoku Race shares clues while keeping solutions and boards private, validates givens and records ordered finishes',async()=>{
 const s=await create('sudoku-race',3);let room=await startRace(s,{difficulty:'medium',rounds:1});const givens=room.puzzle.givens,puzzle=await storedPuzzle(s[0]);assert.equal(givens.length,81);assert.equal(givens.replaceAll('0','').length,34);assert.equal('solution' in room.puzzle,false);let index=givens.indexOf('0'),board=givens.slice(0,index)+puzzle.solution[index]+givens.slice(index+1);await act(s[0],'board',{board});let other=await act(s[1],'state');assert.equal(other.puzzle.givens,givens);assert.equal(other.board,givens);assert.equal('boards' in other,false);assert.equal(other.progress.find(p=>p.player===s[0].id).filled,35);await act(s[0],'board',{board:'bad'},400);const fixed=[...givens].findIndex(v=>v!=='0');await act(s[0],'board',{board:givens.slice(0,fixed)+'0'+givens.slice(fixed+1)},400);await act(s[0],'finish',{board},400);
 room=await act(s[0],'finish',{board:puzzle.solution});assert.equal(room.phase,'race');assert.ok(room.ready.includes(s[0].id));await act(s[0],'board',{board},409);await act(s[1],'finish',{board:puzzle.solution});room=await act(s[2],'give_up');assert.equal(room.phase,'reveal');assert.equal(room.result.standings[0].player,s[0].id);assert.deepEqual(room.result.standings.map(p=>p.points),[16,14,0]);assert.equal(room.result.solution,puzzle.solution);assert.ok(room.result.standings[0].time>=10);room=await act(s[0],'next');assert.equal(room.phase,'finished');
});
test('Sudoku hints fill a selected cell and use adjusted race times; puzzle reset avoids recent bases',async()=>{
 const s=await create('sudoku-race',2);let room=await startRace(s,{difficulty:'hard',rounds:3});const puzzle=await storedPuzzle(s[0]),id=room.puzzleKey,blanks=[...puzzle.givens].map((v,i)=>v==='0'?i:-1).filter(i=>i>=0);let board=room.board;
 for(const index of blanks.slice(0,3)){room=await act(s[0],'hint',{board,index});board=room.board;assert.equal(board[index],puzzle.solution[index]);}assert.equal(room.hints,3);await act(s[0],'hint',{board,index:blanks[3]},409);await act(s[0],'hint',{board,index:100},400);assert.equal((await act(s[1],'state')).hints,0);await act(s[0],'finish',{board:puzzle.solution});await editRoom(s[0],r=>{r.raceStarts=Date.now()/1000-20;});room=await act(s[1],'finish',{board:puzzle.solution});assert.equal(room.phase,'reveal');assert.equal(room.result.standings[0].player,s[1].id);assert.equal(room.result.standings[1].hints,3);assert.ok(room.result.standings[1].adjustedTime>=100);await act(s[0],'reset');room=await act(s[0],'start',{difficulty:'hard',recent:[id]});assert.notEqual(room.puzzleKey,id);
});
test('Sudoku Race timeout awards no points for filling incorrect cells, and solo sessions finish and restart',async()=>{
 const s=await create('sudoku-race',1);let room=await startRace(s,{rounds:1,difficulty:'easy'});const wrong=[...room.board].map(v=>v==='0'?'1':v).join('');await act(s[0],'board',{board:wrong});await act(s[0],'finish',{board:wrong},400);await editRoom(s[0],r=>{r.deadline=Date.now()/1000-1;});room=await act(s[0],'state');assert.equal(room.phase,'reveal');assert.equal(room.result.standings[0].solved,false);assert.equal(room.result.standings[0].points,0);await act(s[0],'next');room=await act(s[0],'again',{difficulty:'easy',rounds:1});assert.equal(room.round,1);assert.equal(room.players[0].score,0);
});
test('puzzle-bank HTTP requests never reveal the server-side solutions',async()=>{
 for(const file of ['api/puzzle-data.php','api/puzzle-games.php']){const res=await fetch(base+file);assert.equal(res.status,200);assert.equal(await res.text(),'');}const res=await fetch(base+'api/word-circuit-words.txt');assert.equal(res.status,200);assert.ok((await res.text()).includes('\ncold\n'));
});
async function storedDeduction(session){return JSON.parse(await readFile(path.join(dataRoot,session.code+'.json'),'utf8'));}
async function startDeduction(s,payload={}){let r=await act(s[0],'start',{difficulty:'classic',rounds:3,...payload});assert.equal(r.phase,'deducing');await editRoom(s[0],room=>{room.deductionStarts=Date.now()/1000-5;});return act(s[0],'state');}
const ruleData=JSON.parse((await readFile('api/rulebreakers-data.php','utf8')).split("<<<'RULES'\n")[1].split('\nRULES')[0]);
function ruleTruth(rule,word){const i=ruleData.words.indexOf(word),a=ruleData.atoms.find(a=>a.id===rule.a),b=ruleData.atoms.find(a=>a.id===rule.b);const bit=atom=>!!(Buffer.from(atom.mask,'base64')[i>>3]&(1<<(i%8)));return rule.op==='single'?bit(a):rule.op==='and'?bit(a)&&bit(b):rule.op==='or'?bit(a)||bit(b):rule.op==='xor'?bit(a)!==bit(b):bit(a)&&!bit(b);}
test('Rulebreakers validates dictionary probes, keeps hypotheses private and accepts equivalent composed rules',async()=>{
 const s=await create('rulebreakers',2);let r=await startDeduction(s);const stored=await storedDeduction(s[0]),rule=stored.deductionPuzzle.rule;assert.equal(r.atoms.length,244);assert.ok(!('solution'in r));assert.ok(!('puzzleKey'in r));assert.ok(!JSON.stringify(r).includes('"mask"'));for(const w of r.examples.yes)assert.equal(ruleTruth(rule,w),true);for(const w of r.examples.no)assert.equal(ruleTruth(rule,w),false);
 await act(s[0],'probe',{word:'zzzzzz'},400);const example=[...r.examples.yes,...r.examples.no];const word=ruleData.words.find(w=>!example.includes(w));r=await act(s[0],'probe',{word});assert.equal(r.state.probes[0].pass,ruleTruth(rule,word));await act(s[0],'probe',{word},409);assert.deepEqual((await act(s[1],'state')).state.probes,[]);
 r=await act(s[0],'rule',{a:'a0',op:'single',b:null});assert.equal(r.state.wrong,1);const counter=r.state.guesses[0].counter;assert.equal(counter.pass,ruleTruth(rule,counter.word));await act(s[0],'rule',{a:'bogus',op:'single'},400);assert.equal((await act(s[1],'state')).state.wrong,0);
 r=await act(s[0],'rule',{a:rule.b,op:rule.op,b:rule.a});assert.equal(r.state.solved,true);assert.equal(r.phase,'deducing');await act(s[0],'probe',{word:'house'},409);r=await act(s[1],'rule',rule);assert.equal(r.phase,'reveal');assert.equal(r.result.scores[s[0].id],10);assert.equal(r.result.scores[s[1].id],12);assert.equal(r.solution.rule.id,rule.id);const score=r.players.map(p=>p.score);assert.deepEqual((await act(s[0],'state')).players.map(p=>p.score),score);
});
test('Rulebreakers six incorrect hypotheses lock the player, and returning hosts avoid recent rules',async()=>{
 const s=await create('rulebreakers',2);let r=await startDeduction(s,{difficulty:'expert'});for(let i=0;i<6;i++)r=await act(s[0],'rule',{a:'a0',op:'single'});assert.ok(r.ready.includes(s[0].id));assert.equal(r.state.solved,false);await act(s[0],'rule',{a:'a0',op:'single'},409);r=await act(s[1],'give_up');assert.equal(r.phase,'reveal');assert.equal(r.result.scores[s[0].id],0);const key=r.puzzleKey;await act(s[0],'reset');r=await act(s[0],'start',{difficulty:'expert',recent:[key]});assert.notEqual((await storedDeduction(s[0])).deductionPuzzle.rule.id,key);
});
test('Alien Dictionary hides solutions, locks each answer once and scores all eight translations',async()=>{
 const s=await create('alien-dictionary',2);let r=await startDeduction(s);const p=(await storedDeduction(s[0])).deductionPuzzle;assert.ok(!('solution'in r));assert.ok(!JSON.stringify(r.challenges).includes('correct'));assert.ok(!JSON.stringify(r.examples).includes('"meaning"'));await act(s[0],'translate',{question:8,choice:0},400);await act(s[0],'translate',{question:0,choice:6},400);
 for(let i=0;i<8;i++){r=await act(s[0],'translate',{question:i,choice:p.challenges[i].correct});assert.equal(r.state.answers[i].correct,true);}assert.ok(r.ready.includes(s[0].id));await act(s[0],'translate',{question:0,choice:0},409);assert.deepEqual((await act(s[1],'state')).state.answers,[]);
 for(let i=0;i<8;i++)r=await act(s[1],'translate',{question:i,choice:i===0?(p.challenges[i].correct+1)%6:p.challenges[i].correct});assert.equal(r.phase,'reveal');assert.equal(r.result.scores[s[0].id],16);assert.equal(r.result.scores[s[1].id],14);assert.equal(r.solution.lexicon.noun.length,3);
});
test('Question Quest validates question costs and private elimination, and solves through six yes/no questions',async()=>{
 const s=await create('question-quest',2);let r=await startDeduction(s,{difficulty:'expert'});const p=(await storedDeduction(s[0])).deductionPuzzle,target=p.roster.find(v=>v.id===p.secret);assert.equal(r.roster.length,36);assert.equal(r.budget,12);assert.ok(!('solution'in r));assert.ok(!('secret'in r));await act(s[0],'question',{field:'job',values:['nonsense']},400);await act(s[0],'question',{field:'nonsense',values:['chef']},400);
 const wrong=r.roster.find(v=>v.id!==target.id);r=await act(s[1],'accuse',{suspect:wrong.id});assert.equal(r.state.spent,2);assert.ok(!r.state.possible.includes(wrong.id));assert.ok((await act(s[0],'state')).state.possible.includes(wrong.id));
 let cost=0;for(const [field,value] of Object.entries(target.traits)){r=await act(s[0],'question',{field,values:[value]});cost++;assert.ok(r.state.possible.includes(target.id));assert.equal(r.state.history.at(-1).yes,true);assert.equal(r.state.spent,cost);await act(s[0],'question',{field,values:[value]},409);if(r.state.possible.length===1)break;}
 assert.equal(r.state.possible.length,1);r=await act(s[0],'accuse',{suspect:target.id});assert.equal(r.state.solved,true);assert.equal(r.state.spent,cost+2);r=await act(s[1],'give_up');assert.equal(r.phase,'reveal');assert.equal(r.solution,target.id);assert.equal(r.result.scores[s[0].id],18-cost);assert.equal(r.result.scores[s[1].id],0);
});
test('Question Quest grouped questions cost two credits, eliminate consistently, and preserve credits for a final choice',async()=>{
 const s=await create('question-quest',2);let r=await startDeduction(s);const p=(await storedDeduction(s[0])).deductionPuzzle,target=p.roster.find(v=>v.id===p.secret);const values=p.fields.job.values.slice(0,4);r=await act(s[0],'question',{field:'job',values});assert.equal(r.state.spent,2);const yes=values.includes(target.traits.job);assert.equal(r.state.history[0].yes,yes);assert.deepEqual(r.state.possible,p.roster.filter(v=>values.includes(v.traits.job)===yes).map(v=>v.id));await act(s[0],'question',{field:'job',values:p.fields.job.values.slice(0,5)},400);
 await editRoom(s[0],room=>{room.deductionStates[s[0].id].spent=10;});await act(s[0],'question',{field:'color',values:[p.fields.color.values[0]]},409);assert.equal((await act(s[0],'state')).state.spent,10);r=await act(s[0],'accuse',{suspect:target.id});assert.equal(r.state.solved,true);
});
test('new deduction games enforce minimum players, options, countdown, late arrivals and host-only reveal',async()=>{
 for(const game of ['rulebreakers','alien-dictionary','question-quest']){const s=await create(game,1);await act(s[0],'start',{},409);s.push((await api('join',{}, {game,code:s[0].code,name:'Friend'})).session);await act(s[0],'start',{difficulty:'bogus'},400);await act(s[0],'start',{rounds:2},400);let r=await act(s[0],'start',{rounds:1});assert.equal(r.phase,'deducing');await act(s[0],'give_up',{},409);await editRoom(s[0],room=>{room.deductionStarts=Date.now()/1000-5;});const late=(await api('join',{}, {game,code:s[0].code,name:'Late'})).session;const view=await act(late,'state');assert.ok(!('state'in view));await act(late,'give_up',{},403);await act(s[1],'end_race',{},403);r=await act(s[0],'end_race');assert.equal(r.phase,'reveal');r=await act(s[0],'next');assert.equal(r.phase,'finished');r=await act(s[0],'again',{rounds:1,difficulty:'easy'});assert.equal(r.phase,'deducing');assert.ok(r.participants.includes(late.id));assert.ok(r.players.every(p=>p.score===0));}
});
test('new deduction timers reveal once, skipped rounds do not score and secret bank URLs return no data',async()=>{
 for(const game of ['rulebreakers','alien-dictionary','question-quest']){const s=await create(game,2);await startDeduction(s);await editRoom(s[0],room=>{room.deadline=Date.now()/1000-1;});let r=await act(s[0],'state');assert.equal(r.phase,'reveal');const scores=r.players.map(p=>p.score);assert.deepEqual((await act(s[1],'state')).players.map(p=>p.score),scores);await act(s[0],'reset');await startDeduction(s);r=await act(s[0],'skip');assert.equal(r.result.skipped,true);assert.ok(r.players.every(p=>p.score===0));}
 for(const file of ['api/deduction-games.php','api/deduction-data.php','api/rulebreakers-data.php']){const res=await fetch(base+file);assert.equal(res.status,200);assert.equal(await res.text(),'');}
});
test('all new deduction games complete three rounds, restart and avoid recent rules or case setups',async()=>{
 for(const game of ['rulebreakers','alien-dictionary','question-quest']){const s=await create(game,2);let r=await startDeduction(s);const used=new Set();for(let round=1;round<=3;round++){assert.equal(r.round,round);await act(s[0],'end_race');r=await act(s[0],'state');if(game!=='alien-dictionary'){assert.ok(!used.has(r.puzzleKey));used.add(r.puzzleKey);}r=await act(s[0],'next');if(round<3){assert.equal(r.phase,'deducing');await editRoom(s[0],room=>{room.deductionStarts=Date.now()/1000-5;});}}assert.equal(r.phase,'finished');r=await act(s[0],'again',{rounds:1,recent:[...used]});const stored=await storedDeduction(s[0]);if(game==='rulebreakers')assert.ok(!used.has(stored.deductionPuzzle.rule.id));if(game==='question-quest')assert.ok(!used.has(stored.deductionPuzzle.story.key));assert.equal(r.round,1);}
});

const jbGames=['quiz-after-dark','punchline','fact-or-fiction','doodle-bluff','last-laugh-trivia','thread-battle'];
const strokes=[{color:'#292039',width:4,points:[[10,10],[200,90],[350,250]]}];
async function stored(session){return JSON.parse(await readFile(path.join(dataRoot,session.code+'.json'),'utf8'));}
async function changeStored(session,fn){const r=await stored(session);fn(r);await writeFile(path.join(dataRoot,session.code+'.json'),JSON.stringify(r));}
async function voteAll(s){let last;for(const player of s){const view=await act(player,'state');if(view.phase!=='jb-voting')continue;for(const e of view.entries){if(e.eligible.length&&e.yourVote===null)last=await act(player,'vote',{entry:e.id,choice:e.eligible[0]});}}return last||await act(s[0],'state');}
async function completeJb(s){
 let r=await act(s[0],'state');
 if(r.phase==='jb-trivia'){const secret=await stored(s[0]);for(const player of s){r=await act(player,'answer',{choice:secret.jbQuestion.correct});}return r;}
 if(r.phase==='jb-drawing'){for(const player of s)r=await act(player,'draw',{strokes});}
 if(r.phase==='jb-writing'){
  for(const [i,player] of s.entries()){const v=await act(player,'state');r=await act(player,'write',v.prompts?{answers:Object.fromEntries(v.prompts.map(p=>[p.id,`Funny ${i} response ${p.id}`]))}:{text:`a suspicious ${i} toaster`});}
 }
 if(r.phase==='jb-bluffing'){for(const [i,player] of s.entries()){const v=await act(player,'state');for(const pic of v.pictures)r=await act(player,'bluff',{picture:pic.id,text:`a fake label ${i} for ${pic.id}`});}}
 if(r.phase==='jb-slogans')for(const [i,player] of s.entries())r=await act(player,'slogans',{texts:[`Slogan ${i} A`,`Slogan ${i} B`]});
 if(r.phase==='jb-designing')for(const [i,player] of s.entries()){const v=await act(player,'state');r=await act(player,'design',{drawing:v.artworks[i%v.artworks.length].id,slogan:v.slogans[i%v.slogans.length].id});}
 return voteAll(s);
}
test('one party joins from any game, retains identities and code across every game, and rejects stale actions',async()=>{
 const s=await create('party',2);const first=await act(s[0],'state');await act(s[1],'select_game',{selection:'imposter'},403);await act(s[0],'select_game',{selection:'invalid-game'},400);
 const cross=(await api('join',{}, {game:'sudoku-race',code:s[0].code,name:'Cross-game friend'})).session;s.push(cross);
 for(const game of ['wavelength','imposter','scattergories','hivemind','apples','humanity','desktop-disaster','word-circuit','sudoku-race','rulebreakers','alien-dictionary','question-quest',...jbGames,'barcraft','party']){
  const previous=await act(s[0],'state');const r=await act(s[0],'select_game',{selection:game});assert.equal(r.code,first.code);assert.equal(r.host,first.host);assert.deepEqual(r.players.map(p=>p.id),s.map(p=>p.id));assert.equal(r.game,game);assert.equal(r.phase,'lobby');assert.equal(r.gameEpoch,previous.gameEpoch+1);assert.equal('target' in r,false);assert.equal('word' in r,false);assert.equal('entries' in r,false);await act(s[0],'start',{gameEpoch:previous.gameEpoch},409);for(const p of s)p.game=game;
 }
 await act(s[1],'leave');const r=await act(s[0],'state');assert.equal(r.players.length,2);
});
test('all six Jackbox adaptations complete full three-round sessions, restart, and support two-player mode',async()=>{
 for(const game of jbGames)for(const count of [2,4]){const s=await create(game,count);let r=await act(s[0],'start',{rounds:3});for(let n=1;n<=3;n++){assert.equal(r.round,n,game);r=await completeJb(s);assert.equal(r.phase,'reveal',game);const before=r.players.map(p=>p.score);const again=await act(s[0],'state');assert.deepEqual(again.players.map(p=>p.score),before,game);r=await act(s[0],'next');}assert.equal(r.phase,'finished',game);r=await act(s[0],'again',{rounds:1});assert.equal(r.round,1,game);assert.ok(r.players.every(p=>p.score===0),game);}
});
test('trivia answers stay private and screws enforce eight-second personal deadlines once per game',async()=>{
 const s=await create('quiz-after-dark',3);let r=await act(s[0],'start',{rounds:1});const truth=(await stored(s[0])).jbQuestion.correct;assert.equal('correct' in r.question,false);assert.equal('truth' in r,false);await act(s[1],'screw',{target:s[1].id},400);await act(s[0],'screw',{target:s[1].id});r=await act(s[1],'state');assert.ok(r.personalDeadline<r.deadline);await act(s[0],'screw',{target:s[2].id},409);await changeStored(s[0],r=>{r.jbJammed[s[1].id]=microtimePlaceholder();});
 function microtimePlaceholder(){return Date.now()/1000-1;}
 await act(s[1],'answer',{choice:truth},409);await act(s[2],'answer',{choice:truth});const other=await act(s[0],'state');assert.equal(other.yourAnswer,null);assert.equal('answers' in other,false);await changeStored(s[0],r=>{r.deadline=Date.now()/1000-1;});r=await act(s[0],'state');assert.equal(r.phase,'reveal');assert.equal(r.result.correct,truth);assert.ok(r.result.scores[s[1].id]<0);
});
test('bluffs remain private, real-answer submissions are rejected, own lies cannot receive own votes',async()=>{
 const s=await create('fact-or-fiction',3);await act(s[0],'start');const q=(await stored(s[0])).jbQuestion;await act(s[0],'write',{text:q.truth},400);await act(s[0],'write',{text:'believable invented thing'});let r=await act(s[1],'state');assert.equal(r.yourWriting,null);assert.equal(JSON.stringify(r).includes('believable invented thing'),false);await act(s[1],'write',{text:'another invented thing'});await act(s[2],'write',{text:'a third invention'});r=await act(s[0],'state');assert.equal(r.phase,'jb-voting');const own=r.entries[0].options.find(o=>o.text==='believable invented thing');assert.ok(!r.entries[0].eligible.includes(own.id));await act(s[0],'vote',{entry:'fact',choice:own.id},400);assert.equal(JSON.stringify(r.entries).includes('truth'),false);await voteAll(s);
});
test('drawings validate coordinates and colors, prompts stay private, and anonymous shirt pools do not expose creator IDs',async()=>{
 const s=await create('thread-battle',2);await act(s[0],'start');const a=await act(s[0],'state'),b=await act(s[1],'state');assert.notEqual(a.drawingPrompt,b.drawingPrompt);assert.equal('jbDrawingPrompts' in a,false);await act(s[0],'draw',{strokes:[{color:'url(evil)',width:4,points:[[10,10]]}]},400);await act(s[0],'draw',{strokes:[{color:'#292039',width:4,points:[[999,10]]}]},400);await act(s[0],'draw',{strokes});let r=await act(s[1],'draw',{strokes});assert.equal(r.phase,'jb-slogans');await act(s[0],'slogans',{texts:['A','B']});r=await act(s[1],'state');assert.deepEqual(r.yourSlogans,[]);await act(s[1],'slogans',{texts:['C','D']});r=await act(s[0],'state');assert.ok(r.artworks.every(a=>/^a\d+$/.test(a.id)));assert.ok(r.slogans.every(a=>/^s\d+$/.test(a.id)));assert.equal(JSON.stringify(r.artworks).includes(s[1].id),false);await act(s[0],'design',{drawing:'invalid',slogan:'s0'},400);await act(s[0],'design',{drawing:'a0',slogan:'s0'});r=await act(s[1],'design',{drawing:'a1',slogan:'s2'});assert.equal(r.entries[0].options.length,3);assert.equal(JSON.stringify(r.entries).includes('artist'),false);await voteAll(s);
});
test('survival trivia runs private traps, ghosts revive, memory previews disappear, and escape standings persist',async()=>{
 const s=await create('last-laugh-trivia',2);await act(s[0],'start',{rounds:3});let secret=await stored(s[0]);const wrong=(secret.jbQuestion.correct+1)%4;await act(s[0],'answer',{choice:wrong});let r=await act(s[1],'answer',{choice:secret.jbQuestion.correct});assert.equal(r.phase,'jb-danger');assert.equal('challenge' in r,false);const trapped=await act(s[0],'state');assert.ok(trapped.challenge);assert.equal('correct' in trapped.challenge,false);await changeStored(s[0],r=>{r.jbChallenges[s[0].id]={text:'Remember',preview:'1234',hideAt:Date.now()/1000-1,options:['1234','4321','1111','2222'],correct:0};});r=await act(s[0],'state');assert.equal('preview' in r.challenge,false);r=await act(s[0],'danger',{choice:1});assert.equal(r.phase,'reveal');assert.equal(r.lives[s[0].id],1);await act(s[0],'next');await changeStored(s[0],r=>{r.jbLives[s[0].id]=0;r.jbGhostWins={...r.jbGhostWins,[s[0].id]:1};});secret=await stored(s[0]);await act(s[0],'answer',{choice:secret.jbQuestion.correct});r=await act(s[1],'answer',{choice:secret.jbQuestion.correct});assert.equal(r.phase,'reveal');assert.equal(r.lives[s[0].id],1);assert.ok(r.escape[s[0].id]>=2);
});
test('all new stages recover on timers, late arrivals wait, and private source banks expose no data over HTTP',async()=>{
 for(const game of jbGames){const s=await create(game,2);await act(s[0],'start',{rounds:1});const late=(await api('join',{}, {game:'party',code:s[0].code,name:'Late'})).session;await act(late,'answer',{choice:0},403);await act(s[1],'finish_stage',{},403);let r;for(let n=0;n<5;n++){await changeStored(s[0],r=>{r.deadline=Date.now()/1000-1;});r=await act(s[0],'state');if(r.phase==='reveal')break;}assert.equal(r.phase,'reveal',game);assert.ok(r.players.every(p=>p.score<=0),game);}
 for(const file of ['api/jackbox-data.php','api/jackbox-games.php','api/party-hub.php']){const r=await fetch(base+file);assert.equal((await r.text()).trim(),'');}
});

test('host can kick a member from the party lobby or game, guests cannot kick, removed sessions lose access',async()=>{
 const s=await create('party',3);await act(s[1],'kick',{player:s[2].id},403);await act(s[0],'kick',{player:s[0].id},400);let r=await act(s[0],'kick',{player:s[2].id});assert.equal(r.players.length,2);await act(s[2],'state',{},401);await act(s[2],'select_game',{selection:'imposter'},401);await act(s[0],'select_game',{selection:'fact-or-fiction'});s[0].game='fact-or-fiction';s[1].game='fact-or-fiction';await act(s[0],'start');r=await act(s[0],'kick',{player:s[1].id});assert.equal(r.players.length,1);await act(s[1],'state',{},401);await act(s[0],'finish_stage');
});

test('legacy numeric player IDs cannot vote for their own bluffs, drawings or shirts',async()=>{
 for(const game of ['fact-or-fiction','doodle-bluff','thread-battle','quiz-after-dark']){
  const s=await create(game,2);await changeStored(s[0],r=>{r.players.forEach((p,i)=>p.id=String(123456789010+i));r.host=r.players[0].id;});s.forEach((p,i)=>p.id=String(123456789010+i));await act(s[0],'start',{rounds:1});
  if(game==='fact-or-fiction'){await act(s[0],'write',{text:'invented answer one'});await act(s[1],'write',{text:'invented answer two'});const r=await act(s[0],'state'),own=r.entries[0].options.find(o=>o.text==='invented answer one');assert.ok(!r.entries[0].eligible.includes(own.id));await act(s[0],'vote',{entry:'fact',choice:own.id},400);}
  else if(game==='quiz-after-dark'){await act(s[0],'answer',{choice:0});assert.deepEqual((await act(s[1],'state')).jbReady,[s[0].id]);}
  else{await act(s[0],'draw',{strokes});await act(s[1],'draw',{strokes});if(game==='doodle-bluff'){for(const p of s){const r=await act(p,'state');assert.equal(r.pictures.length,1);await act(p,'bluff',{picture:r.pictures[0].id,text:'invented drawing label'});}assert.equal((await act(s[0],'state')).entries.find(e=>e.id==='d0').eligible.length,0);}
   else{await act(s[0],'slogans',{texts:['one','two']});await act(s[1],'slogans',{texts:['three','four']});await act(s[0],'design',{drawing:'a0',slogan:'s0'});await act(s[1],'design',{drawing:'a1',slogan:'s2'});const r=await act(s[0],'state'),own=r.entries[0].options.find(o=>o.text==='one');assert.ok(!r.entries[0].eligible.includes(own.id));}
  }
 }
});
