import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile,writeFile,cp,mkdir,readdir} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
let server,base,webroot,dataRoot;
before(async()=>{const temp=await mkdtemp(path.join(os.tmpdir(),'party-room-test-'));dataRoot=path.join(temp,'private-rooms');webroot=path.join(temp,'public_html');await mkdir(webroot);await cp('release/party-room',path.join(webroot,'friends','friday'),{recursive:true});const port=18000+Math.floor(Math.random()*2000);base=`http://127.0.0.1:${port}/friends/friday/`;server=spawn('php',['-S',`127.0.0.1:${port}`,'-t',webroot],{env:{...process.env,PARTY_ROOM_DATA_DIR:dataRoot},stdio:'ignore'});for(let n=0;n<50;n++){try{await fetch(base);return;}catch{await new Promise(r=>setTimeout(r,100));}}throw Error('PHP test server did not start');});
after(()=>server?.kill());
async function api(action,session={},payload={},status=200){const response=await fetch(base+'api/room.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,...payload,action})});const body=await response.json();assert.equal(response.status,status,JSON.stringify(body));return body;}
async function create(game,count){const first=await api('create',{}, {game,name:'Host'});assert.match(first.session.code,/^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{5}$/);const sessions=[first.session];for(let n=1;n<count;n++)sessions.push((await api('join',{}, {game,code:first.session.code.toLowerCase(),name:`Friend ${n}`})).session);assert.equal(new Set(sessions.map(s=>s.token)).size,count);return sessions;}
const act=async(s,a,p={},status=200)=>(await api(a,s,p,status)).room;
test('renamed nested folder: pages, return routes, modules, audio, artwork and fonts resolve',async()=>{
 const roots=['','games/barcraft/','games/wavelength/?room=ABCDE','games/imposter/?room=ABCDE','games/scattergories/?room=ABCDE','games/hivemind/?room=ABCDE','games/apples/?room=ABCDE','games/humanity/?room=ABCDE','games/desktop-disaster/?room=ABCDE','games/word-circuit/?room=ABCDE','games/sudoku-race/?room=ABCDE'];
 for(const route of roots){const url=new URL(route,base),response=await fetch(url);assert.equal(response.status,200);const html=await response.text();for(const m of html.matchAll(/(?:href|src)="([^"]+)"/g)){if(m[1].startsWith('#')||m[1].startsWith('https:'))continue;const asset=await fetch(new URL(m[1],url));assert.equal(asset.status,200,`${route}: ${m[1]}`);}}
 const shared=await readFile('shared/party-client.js','utf8');assert.match(shared,/new URL\('\.\.\/api\/room.php',import.meta.url\)/);
 for(const route of ['art/wavelength.svg','art/imposter.svg','shared/party-ui.js','shared/game-tools.js','games/wavelength/style.css','games/imposter/app.js','fonts/dm-sans-400.ttf','games/barcraft/audio/griphop.mp3']){const res=await fetch(base+route);if(route.endsWith('griphop.mp3')){assert.equal(res.status,200);await res.body.cancel();}else{assert.equal(res.status,200,route);await res.arrayBuffer();}}
 const apiGet=await fetch(base+'api/room.php');assert.equal(apiGet.status,405);
});
test('Wavelength private targets, synchronized guesses, median scoring and round rotation',async()=>{
 const s=await create('wavelength',3);await api('join',{}, {game:'imposter',code:s[0].code,name:'Wrong game'},400);await act({...s[0],token:'bad'},'state',{},401);await act(s[1],'start',{},403);
 let room=await act(s[0],'start');assert.equal(room.phase,'clue');const giver=s.find(p=>p.id===room.giver),others=s.filter(p=>p.id!==giver.id);const secret=await act(giver,'state');assert.equal(typeof secret.target,'number');const redacted=await act(others[0],'state');assert.equal('target' in redacted,false);assert.equal(JSON.stringify(redacted).includes('token'),false);
 await act(others[0],'clue',{clue:'Coffee'},403);await act(giver,'clue',{clue:'Coffee'});await act(giver,'guess',{value:50},403);await act(others[0],'guess',{value:secret.target-2});await act(others[1],'guess',{value:secret.target+2});room=await act(s[0],'reveal');assert.equal(room.phase,'reveal');assert.equal(room.result.points,4);assert.equal(room.totalScore,4);assert.ok(Math.abs(room.result.guess-secret.target)<0.00001);assert.equal((await act(others[0],'state')).target,secret.target);await act(s[0],'reveal',{},409);
 room=await act(s[0],'next');assert.equal(room.round,2);assert.notEqual(room.giver,giver.id);await act(s[0],'skip',{round:1},409);await act(s[0],'skip');await act(s[0],'reset');
});
test('Imposter secret roles, turn order, locked private ballots, caught imposter final guess',async()=>{
 const s=await create('imposter',3);let room=await act(s[0],'start',{category:'Food'});const views=await Promise.all(s.map(p=>act(p,'state')));const imp=s[views.findIndex(v=>v.role==='imposter')],informed=s.filter(p=>p.id!==imp.id),word=views.find(v=>v.word).word;assert.equal(views.filter(v=>v.role==='imposter').length,1);assert.equal('word' in views.find(v=>v.role==='imposter'),false);assert.equal('imposter' in room,false);
 for(const id of room.order){const current=s.find(p=>p.id===id);await act(current,'clue',{clue:`hint ${id.slice(0,3)}`});}room=await act(s[0],'state');assert.equal(room.phase,'vote');await act(informed[0],'vote',{suspect:imp.id});await act(informed[0],'vote',{suspect:imp.id},409);const other=await act(imp,'state');assert.equal(other.voteCount,1);assert.equal('votes' in other,false);assert.equal(other.yourVote,null);await act(informed[1],'vote',{suspect:imp.id});room=await act(imp,'vote',{suspect:informed[0].id});assert.equal(room.phase,'last_guess');assert.equal('word' in room,false);await act(informed[0],'final_guess',{guess:word},403);room=await act(imp,'final_guess',{guess:'Definitely not a food'});assert.equal(room.phase,'reveal');assert.equal(room.word,word);assert.equal(room.imposter,imp.id);assert.equal(room.result.imposterWins,false);assert.equal(room.players.find(p=>p.id===imp.id).score,0);assert.equal(room.players.find(p=>p.id===informed[0].id).score,1);
 room=await act(s[0],'next');const newViews=await Promise.all(s.map(p=>act(p,'state')));assert.notEqual(newViews.find(v=>v.role==='imposter').you,imp.id);assert.notEqual(newViews.find(v=>v.word).word,word);
});
test('Imposter tied vote gives the imposter the round; late arrivals wait until next round',async()=>{
 const s=await create('imposter',3);let room=await act(s[0],'start');const late=(await api('join',{}, {game:'imposter',code:s[0].code,name:'Late friend'})).session;await act(late,'clue',{clue:'Hello'},403);for(const id of room.order)await act(s.find(p=>p.id===id),'clue',{clue:'Maybe'});for(let n=0;n<3;n++)room=await act(s[n],'vote',{suspect:s[(n+1)%3].id});assert.equal(room.phase,'reveal');assert.equal(room.result.accused,null);assert.equal(room.result.imposterWins,true);assert.equal(room.players.filter(p=>p.score===2).length,1);room=await act(s[0],'next');assert.ok(room.participants.includes(late.id));
});
test('complete sessions finish once, can restart, and transfer hosting when a host leaves',async()=>{
 for(const game of ['wavelength','imposter']){const s=await create(game,game==='wavelength'?2:3);let room=await act(s[0],'start');for(let round=1;round<=room.maxRounds;round++){assert.equal(room.round,round);if(game==='wavelength'){const giver=s.find(p=>p.id===room.giver),other=s.find(p=>p.id!==room.giver);const target=(await act(giver,'state')).target;await act(giver,'clue',{clue:'A fresh idea'});await act(other,'guess',{value:target});room=await act(s[0],'reveal');}else{for(const id of room.order)await act(s.find(p=>p.id===id),'clue',{clue:'Something subtle'});for(let i=0;i<s.length;i++)room=await act(s[i],'vote',{suspect:s[(i+1)%s.length].id});}room=await act(s[0],'next');}assert.equal(room.phase,'finished');if(game==='wavelength')assert.equal(room.totalScore,32);room=await act(s[0],'again');assert.equal(room.round,1);await act(s[0],'leave');room=await act(s[1],'state');assert.equal(room.host,s[1].id);await act(s[1],'skip');await act(s[1],'reset');assert.equal((await act(s[1],'state')).phase,'lobby');}
});
test('Scattergories keeps sheets private, locks submissions, scores duplicates and supports host review',async()=>{
 const s=await create('scattergories',3);let room=await act(s[0],'start');assert.equal(room.phase,'writing');assert.equal(room.categories.length,12);assert.equal(new Set(room.categories).size,12);assert.match(room.letter,/^[A-Z]$/);const prefix=room.letter;const values=[`${prefix}Shared`,`${prefix}Unique`,`${prefix}Good`,'1wrong'];await act(s[0],'answers',{answers:values});const hidden=await act(s[1],'state');assert.equal('answers' in hidden,false);assert.deepEqual(hidden.yourAnswers,[]);assert.equal(hidden.result,null);
 await act(s[0],'submit',{answers:values});await act(s[0],'answers',{answers:values},409);await act(s[1],'submit',{answers:[`The ${prefix.toLowerCase()}shared`,`${prefix}Other`,`${prefix}Second`,'']});room=await act(s[2],'submit',{answers:['',`${prefix}Third`,'','']});assert.equal(room.phase,'reveal');assert.equal(room.result.details[s[0].id][0].status,'duplicate');assert.equal(room.result.details[s[1].id][0].status,'duplicate');assert.equal(room.result.details[s[0].id][3].status,'letter');assert.equal(room.result.scores[s[0].id],2);assert.equal(room.result.scores[s[1].id],2);assert.equal(room.result.scores[s[2].id],1);assert.equal(room.players.find(p=>p.id===s[0].id).score,2);
 await act(s[1],'review',{player:s[0].id,index:1,accepted:false},403);room=await act(s[0],'review',{player:s[0].id,index:1,accepted:false});assert.equal(room.result.scores[s[0].id],1);assert.equal(room.players.find(p=>p.id===s[0].id).score,1);room=await act(s[0],'review',{player:s[0].id,index:1,accepted:false});assert.equal(room.players.find(p=>p.id===s[0].id).score,1);room=await act(s[0],'review',{player:s[0].id,index:1,accepted:true});assert.equal(room.players.find(p=>p.id===s[0].id).score,2);const oldCategories=room.categories,oldLetter=room.letter;room=await act(s[0],'next');assert.equal(room.round,2);assert.notEqual(room.letter,oldLetter);assert.ok(room.categories.every(v=>!oldCategories.includes(v)));assert.deepEqual((await act(s[1],'state')).yourAnswers,[]);
});
test('Scattergories server timer reveals the latest saved answers and rejects late edits',async()=>{
 const s=await create('scattergories',2);let room=await act(s[0],'start');await act(s[0],'answers',{answers:[`${room.letter}example`]});const file=path.join(dataRoot,s[0].code+'.json'),stored=JSON.parse(await readFile(file));stored.deadline=Math.floor(Date.now()/1000)-1;await writeFile(file,JSON.stringify(stored));room=await act(s[1],'state');assert.equal(room.phase,'reveal');assert.equal(room.answers[s[0].id][0],`${room.letter}example`);assert.equal(room.result.scores[s[0].id],1);await act(s[0],'answers',{answers:['Late']},409);assert.equal((await act(s[0],'state')).players.find(p=>p.id===s[0].id).score,1);
});
test('Scattergories plays all six rounds and reaches a fresh session with zero scores',async()=>{
 const s=await create('scattergories',2);let room=await act(s[0],'start');const used=new Set();for(let round=1;round<=6;round++){assert.equal(room.round,round);assert.ok(room.categories.every(v=>!used.has(v)));room.categories.forEach(v=>used.add(v));await act(s[0],'submit',{answers:[`${room.letter}first`]});await act(s[1],'submit',{answers:[`${room.letter}second`]});room=await act(s[0],'next');}assert.equal(room.phase,'finished');assert.deepEqual(room.players.map(p=>p.score),[6,6]);room=await act(s[0],'again',{recent:[...used]});assert.equal(room.round,1);assert.ok(room.categories.every(v=>!used.has(v)));assert.deepEqual(room.players.map(p=>p.score),[0,0]);
});
test('all imported modules, local music tracks and CSS font assets exist in the deployable folder',async()=>{
 const files=await readdir('release/party-room',{recursive:true}),local=[];
 for(const file of files){if(!/\.(js|css)$/.test(file))continue;const source=await readFile(path.join('release/party-room',file),'utf8');const matches=[...source.matchAll(/from\s+['"]([^'"]+)['"]/g),...source.matchAll(/url\(['"]?([^)'"\s]+)['"]?\)/g)];for(const m of matches){if(!m[1].startsWith('http')&&!m[1].startsWith('data:'))local.push(new URL(m[1],new URL(file.replaceAll(path.sep,'/'),base)));}}
 const {games}=await import('../games.js');for(const game of games){local.push(new URL(game.path,base),new URL(game.artwork,base));}for(const file of files.filter(v=>v.endsWith('.mp3')))local.push(new URL(file.replaceAll(path.sep,'/'),base));
 for(const url of local){const res=await fetch(url);assert.equal(res.status,200,url.href);await res.body.cancel();}
});
test('recent spectra and secret words supplied by a returning host are avoided in new games',async()=>{
 const w=await create('wavelength',2);let room=await act(w[0],'start');const spectrum=room.spectrum.join(' | ');await act(w[0],'reset');room=await act(w[0],'start',{recent:[spectrum]});assert.notEqual(room.spectrum.join(' | '),spectrum);
 const i=await create('imposter',3);room=await act(i[0],'start',{category:'Food'});const views=await Promise.all(i.map(p=>act(p,'state'))),word=views.find(v=>v.word).word;await act(i[0],'reset');await act(i[0],'start',{category:'Food',recent:[word]});const newViews=await Promise.all(i.map(p=>act(p,'state')));assert.notEqual(newViews.find(v=>v.word).word,word);
});
async function editRoom(session,update){const file=path.join(dataRoot,session.code+'.json'),stored=JSON.parse(await readFile(file));update(stored);stored.version++;await writeFile(file,JSON.stringify(stored));}
test('Hive Mind private multi-answer lists, plural matches, synonym review and survival movement',async()=>{
 const s=await create('hivemind',3);let room=await act(s[0],'start',{levels:6});assert.equal(room.phase,'question');assert.equal(room.questionOptions.length,3);assert.equal('questionOptions' in await act(s[1],'state'),false);await act(s[1],'question',{index:0},403);await act(s[0],'question',{custom:'Name three ordinary things.',count:3});await editRoom(s[0],r=>{r.die={dots:1,star:false};});await act(s[0],'answer',{answers:['dog','cats','rock']});let hidden=await act(s[1],'state');assert.deepEqual(hidden.yourAnswers,[]);assert.equal(hidden.result,null);assert.equal('answers' in hidden,false);await act(s[0],'submit',{answers:['dog','cats','rock']});await act(s[1],'submit',{answers:['dogs','cat','stone']});room=await act(s[2],'submit',{answers:['dog','cat','fish']});assert.equal(room.phase,'reveal');assert.deepEqual(Object.values(room.result.scores),[7,7,7]);await act(s[1],'merge',{from:'rock',to:'stone'},403);room=await act(s[0],'merge',{from:'rock',to:'stone'});assert.deepEqual(Object.values(room.result.scores),[8,8,7]);assert.equal(room.result.levels[s[2].id],1);assert.equal(room.levels[s[2].id],0);room=await act(s[0],'next');assert.equal(room.levels[s[2].id],1);assert.equal(room.active,s[1].id);assert.equal(room.phase,'question');assert.equal(room.maxRounds,0);
 await act(s[1],'question',{custom:'Name two things.',count:2});await editRoom(s[0],r=>{r.die={dots:1,star:false};for(const id of r.participants)r.levels[id]=5;});for(const player of s)room=await act(player,'submit',{answers:['sun','moon']});assert.deepEqual(Object.values(room.result.levels),[6,6,6]);room=await act(s[0],'next');assert.equal(room.phase,'finished');assert.deepEqual(room.winners,s.map(p=>p.id));
});
test('Apples private seven-card hands, anonymous shuffled judging, locked submissions and hand refill',async()=>{
 const s=await create('apples',4);let room=await act(s[0],'start');assert.equal(room.targetScore,8);assert.equal(room.hand.length,7);assert.equal(room.judge,s[0].id);const views=await Promise.all(s.map(p=>act(p,'state')));const all=views.flatMap(v=>v.hand.map(c=>c.id));assert.equal(new Set(all).size,28);await act(s[0],'play',{cards:[room.hand[0].id]},403);await act(s[1],'play',{cards:[room.hand[0].id]},403);await act(s[1],'play',{cards:[]},400);
 for(let i=1;i<4;i++){room=await act(s[i],'play',{cards:[views[i].hand[0].id]});if(i===1){assert.equal(room.hand.length,6);await act(s[i],'play',{cards:[views[i].hand[1].id]},409);const judge=await act(s[0],'state');assert.equal('choices' in judge,false);assert.equal('submissions' in judge,false);}}
 room=await act(s[0],'state');assert.equal(room.phase,'judging');assert.equal(room.choices.length,3);assert.ok(room.choices.every(c=>!('player' in c)));const chosen=room.choices.find(v=>v.texts[0]===views[1].hand[0].text);await act(s[1],'choose',{choice:chosen.id},403);room=await act(s[0],'choose',{choice:chosen.id});assert.equal(room.result.winner,s[1].id);assert.equal(room.players.find(p=>p.id===s[1].id).score,1);await act(s[0],'choose',{choice:chosen.id},403);room=await act(s[0],'next');assert.equal(room.judge,s[1].id);const refilled=await act(s[1],'state');assert.equal(refilled.hand.length,7);assert.ok(refilled.hand.every(c=>c.id!==views[1].hand[0].id));
});
test('Cards Against Humanity supports ordered Pick 2s, ten-card hands, winning targets and free play',async()=>{
 const s=await create('humanity',4);await act(s[0],'start',{target:5});await editRoom(s[0],r=>{r.prompt={text:'Combine _____ with _____.',pick:2};});const views=await Promise.all(s.map(p=>act(p,'state')));assert.ok(views.every(v=>v.hand.length===10));await act(s[1],'play',{cards:[views[1].hand[0].id,views[1].hand[0].id]},400);
 for(let i=1;i<4;i++)await act(s[i],'play',{cards:[views[i].hand[1].id,views[i].hand[0].id]});let room=await act(s[0],'state');assert.equal(room.phase,'judging');const chosen=room.choices.find(v=>v.texts[0]===views[1].hand[1].text);assert.deepEqual(chosen.texts,[views[1].hand[1].text,views[1].hand[0].text]);await editRoom(s[0],r=>{r.players.find(p=>p.id===s[1].id).score=4;});room=await act(s[0],'choose',{choice:chosen.id});assert.equal(room.result.gameOver,true);room=await act(s[0],'next');assert.equal(room.phase,'finished');assert.equal(room.players.find(p=>p.id===s[1].id).score,5);await act(s[0],'again',{target:0});let first=await act(s[0],'state');const activeViews=await Promise.all(s.map(p=>act(p,'state')));for(let i=1;i<4;i++)await act(s[i],'play',{cards:activeViews[i].hand.slice(0,first.prompt.pick).map(c=>c.id)});room=await act(s[0],'state');await act(s[0],'choose',{choice:room.choices[0].id});await act(s[1],'finish',{},403);room=await act(s[0],'finish');assert.equal(room.phase,'finished');
});
test('absent card judge can be replaced without judging their own submission',async()=>{
 const s=await create('apples',4);await act(s[0],'start');const views=await Promise.all(s.map(p=>act(p,'state')));for(let i=1;i<4;i++)await act(s[i],'play',{cards:[views[i].hand[0].id]});await act(s[0],'leave');let room=await act(s[1],'state');assert.equal(room.host,s[1].id);room=await act(s[1],'take_judge');assert.equal(room.judge,s[1].id);assert.equal(room.choices.length,2);assert.ok(room.choices.every(c=>c.texts[0]!==views[1].hand[0].text));room=await act(s[1],'choose',{choice:room.choices[0].id});assert.notEqual(room.result.winner,s[1].id);
});
test('Desktop Disaster roles, hidden gadget ownership, trap points, penalties and validated task completion',async()=>{
 const s=await create('desktop-disaster',2);let room=await act(s[0],'start');assert.equal(room.phase,'desktop');assert.equal(room.active,s[0].id);assert.equal(room.maxRounds,4);assert.equal('channels' in room,false);assert.equal('expected' in room.task.current,false);let sab=await act(s[1],'state');assert.equal(sab.channels.length,4);await act(s[1],'step',{step:0,value:'fake'},403);await act(s[0],'trap',{kind:'popup',index:0},403);await act(s[0],'step',{step:0,value:'fake'},400);
 await act(s[1],'trap',{kind:'popup',index:0});room=await act(s[0],'state');let trap=room.traps[0];assert.equal('owner' in trap,false);await act(s[0],'seen',{traps:[trap.id]});await act(s[0],'seen',{traps:[trap.id]});sab=await act(s[1],'state');assert.equal(sab.roundPoints,1);assert.equal(sab.players.find(p=>p.id===s[1].id).score,0);await act(s[0],'dismiss',{trap:trap.id});await editRoom(s[0],r=>{r.trapCooldown[s[1].id]=0;});await act(s[1],'trap',{kind:'error',index:0});room=await act(s[0],'state');trap=room.traps[0];const deadline=room.deadline;await act(s[0],'seen',{traps:[trap.id]});room=await act(s[0],'hit',{trap:trap.id});assert.equal(room.deadline,deadline-4);await act(s[0],'hit',{trap:trap.id},409);sab=await act(s[1],'state');assert.equal(sab.roundPoints,4);assert.equal(sab.yourStats.hits,1);
 const stored=JSON.parse(await readFile(path.join(dataRoot,s[0].code+'.json')));for(let step=0;step<4;step++)room=await act(s[0],'step',{step,value:stored.task.steps[step].expected});assert.equal(room.phase,'reveal');assert.equal(room.result.success,true);assert.equal(room.players.find(p=>p.id===s[1].id).score,4);assert.ok(room.players.find(p=>p.id===s[0].id).score>=10);assert.equal(room.result.channels[s[1].id].length,4);room=await act(s[0],'next');assert.equal(room.active,s[1].id);assert.notEqual(room.task.type,stored.task.type);
});
test('Desktop Disaster enforces assigned channels and timed-out rounds award sabotage bonuses once',async()=>{
 const s=await create('desktop-disaster',3);await act(s[0],'start');let sab=await act(s[1],'state');const forbidden=['popup','notification','error','buttons'].find(v=>!sab.channels.includes(v));await act(s[1],'trap',{kind:forbidden,index:0},403);await editRoom(s[0],r=>{r.deadline=Math.floor(Date.now()/1000)-1;});let room=await act(s[0],'state');assert.equal(room.phase,'reveal');assert.equal(room.result.success,false);assert.deepEqual(room.players.map(p=>p.score),[0,3,3]);room=await act(s[0],'state');assert.deepEqual(room.players.map(p=>p.score),[0,3,3]);
});
test('Hive timers reveal saved lists; a star lifts top scores and lowers only the bottom group',async()=>{
 const s=await create('hivemind',3);await act(s[0],'start',{levels:8});await act(s[0],'question',{custom:'Name two animals.',count:2});await editRoom(s[0],r=>{r.die={dots:1,star:true};for(const id of r.participants)r.levels[id]=2;});await act(s[0],'answer',{answers:['dog','cat']});await act(s[1],'answer',{answers:['dogs','cats']});await act(s[2],'answer',{answers:['goose','duck']});await editRoom(s[0],r=>{r.deadline=Math.floor(Date.now()/1000)-1;});let room=await act(s[0],'state');assert.equal(room.phase,'reveal');assert.deepEqual(Object.values(room.result.scores),[4,4,2]);assert.deepEqual(Object.values(room.result.levels),[1,1,3]);await act(s[0],'answer',{answers:['late','late']},409);
});
test('Hive matching bonuses apply once per meaning even when a list has equivalent answers',async()=>{
 const s=await create('hivemind',3);await act(s[0],'start');await act(s[0],'question',{custom:'Name three objects.',count:3});await act(s[0],'submit',{answers:['stone','rock','bird']});await act(s[1],'submit',{answers:['stone','rock','birds']});await act(s[2],'submit',{answers:['rock','bird','stone']});let room=await act(s[0],'merge',{from:'stone',to:'rock'});assert.deepEqual(Object.values(room.result.scores),[7,7,7]);
});
test('card-game submission and judging timers recover safely without awarding phantom points',async()=>{
 const s=await create('apples',4);await act(s[0],'start');const view=await act(s[1],'state');await act(s[1],'play',{cards:[view.hand[0].id]});await editRoom(s[0],r=>{r.deadline=Math.floor(Date.now()/1000)-1;});let room=await act(s[0],'state');assert.equal(room.phase,'judging');assert.equal(room.choices.length,1);await editRoom(s[0],r=>{r.deadline=Math.floor(Date.now()/1000)-1;});room=await act(s[0],'state');assert.equal(room.phase,'reveal');assert.equal(room.result.skipped,true);assert.ok(room.players.every(p=>p.score===0));await act(s[0],'next');await editRoom(s[0],r=>{r.deadline=Math.floor(Date.now()/1000)-1;});room=await act(s[0],'state');assert.equal(room.phase,'reveal');assert.equal(room.result.skipped,true);
});
test('twenty-five card rounds keep prompts and dealt responses fresh; new hosts carry recent history',async()=>{
 const s=await create('humanity',4);let room=await act(s[0],'start',{target:0});const prompts=[],cards=new Set();for(let round=1;round<=25;round++){assert.ok(!prompts.includes(room.prompt.text));prompts.push(room.prompt.text);const views=await Promise.all(s.map(p=>act(p,'state')));for(const view of views)for(const card of view.hand)cards.add(card.text);const judge=s.find(p=>p.id===room.judge);for(const player of s.filter(p=>p.id!==judge.id)){const hand=views.find(v=>v.you===player.id).hand;await act(player,'play',{cards:hand.slice(0,room.prompt.pick).map(c=>c.id)});}room=await act(judge,'state');await act(judge,'choose',{choice:room.choices[0].id});room=await act(s[0],'next');}assert.equal(room.round,26);assert.ok(cards.size>100);await act(s[0],'reset');room=await act(s[0],'start',{target:0,recent:[...prompts,...[...cards].map(v=>'card:'+v)]});assert.ok(!prompts.includes(room.prompt.text));assert.ok(room.hand.every(c=>!cards.has(c.text)));
});
test('Desktop task rotation gives everyone two active turns and ends with consistent scores',async()=>{
 const s=await create('desktop-disaster',2);let room=await act(s[0],'start');for(let round=1;round<=4;round++){assert.equal(room.round,round);assert.equal(room.active,s[(round-1)%2].id);const active=s.find(p=>p.id===room.active),stored=JSON.parse(await readFile(path.join(dataRoot,s[0].code+'.json')));for(let step=0;step<4;step++)room=await act(active,'step',{step,value:stored.task.steps[step].expected});assert.equal(room.phase,'reveal');room=await act(s[0],'next');}assert.equal(room.phase,'finished');assert.ok(room.players.every(p=>p.score>=20));
});
async function startRace(s,payload={}){await act(s[0],'start',payload);await editRoom(s[0],r=>{r.raceStarts=Date.now()/1000-10;});return act(s[0],'state');}
async function storedPuzzle(s){return JSON.parse(await readFile(path.join(dataRoot,s.code+'.json'))).puzzle;}
test('Word Circuit validates dictionary, exact letter changes, loops, private routes and shortest-route scoring',async()=>{
 const s=await create('word-circuit',2);let room=await act(s[0],'start',{difficulty:'easy',rounds:1});assert.equal(room.phase,'race');assert.equal('solution' in room.puzzle,false);assert.equal('paths' in room,false);await act(s[0],'word',{word:room.puzzle.start},409);await editRoom(s[0],r=>{r.raceStarts=Date.now()/1000-10;});await act(s[0],'word',{word:'zzzz'},400);await act(s[0],'word',{word:'too long'},400);await act(s[0],'word',{word:room.puzzle.start},400);
 const puzzle=await storedPuzzle(s[0]);for(const word of puzzle.solution.slice(1))room=await act(s[0],'word',{word:word.toUpperCase()});assert.deepEqual(room.bestPath,puzzle.solution);const hidden=await act(s[1],'state');assert.deepEqual(hidden.path,[puzzle.start]);assert.equal(hidden.bestPath,null);assert.ok(!JSON.stringify(hidden).includes('solution'));assert.equal(hidden.progress.find(p=>p.player===s[0].id).solved,true);await act(s[0],'word',{word:puzzle.solution.at(-2)},400);
 room=await act(s[0],'restart_path');assert.deepEqual(room.path,[puzzle.start]);assert.deepEqual(room.bestPath,puzzle.solution);await act(s[0],'lock');await act(s[0],'undo',{},409);room=await act(s[1],'give_up');assert.equal(room.phase,'reveal');assert.deepEqual(room.result.solution,puzzle.solution);assert.equal(room.result.scores[s[0].id],12);assert.equal(room.result.scores[s[1].id],0);assert.equal(room.players.find(p=>p.id===s[0].id).score,12);room=await act(s[0],'next');assert.equal(room.phase,'finished');
});
test('Word Circuit hints are private, bounded and charged; saved routes reveal on timeout only once',async()=>{
 const s=await create('word-circuit',2);let room=await startRace(s,{difficulty:'classic',rounds:3});const pair=room.puzzleKey;room=await act(s[0],'hint');assert.equal(room.hints,1);assert.ok(room.hint.word);assert.equal((await act(s[0],'hint')).hints,1);assert.equal((await act(s[1],'state')).hint,null);const route=(await storedPuzzle(s[0])).solution;await act(s[0],'word',{word:room.hint.word});await act(s[0],'undo');room=await act(s[0],'restart_path');for(const word of route.slice(1))room=await act(s[0],'word',{word});await editRoom(s[0],r=>{r.deadline=Date.now()/1000-1;});room=await act(s[1],'state');assert.equal(room.phase,'reveal');assert.equal(room.result.scores[s[0].id],10);const score=room.players.find(p=>p.id===s[0].id).score;assert.equal((await act(s[0],'state')).players.find(p=>p.id===s[0].id).score,score);await act(s[0],'hint',{},409);await act(s[0],'reset');room=await act(s[0],'start',{difficulty:'classic',recent:[pair]});assert.notEqual(room.puzzleKey,pair);
});
test('Word Circuit supports solo play, late spectators, recovery, host ending and validated options',async()=>{
 const s=await create('word-circuit',1);await act(s[0],'start',{difficulty:'bad'},400);await act(s[0],'start',{rounds:999},400);let room=await startRace(s,{difficulty:'expert',rounds:3});const late=(await api('join',{}, {game:'word-circuit',code:s[0].code,name:'Late'})).session;let view=await act(late,'state');assert.equal('path' in view,false);await act(late,'word',{word:room.puzzle.end},403);await act(late,'end_race',{},403);await act(s[0],'end_race');room=await act(s[0],'next');assert.ok(room.participants.includes(late.id));await act(s[0],'leave');room=await act(late,'state');assert.equal(room.host,late.id);
});
test('Sudoku Race shares clues while keeping solutions and boards private, validates givens and records ordered finishes',async()=>{
 const s=await create('sudoku-race',3);let room=await startRace(s,{difficulty:'medium',rounds:1});const givens=room.puzzle.givens,puzzle=await storedPuzzle(s[0]);assert.equal(givens.length,81);assert.equal(givens.replaceAll('0','').length,34);assert.equal('solution' in room.puzzle,false);let index=givens.indexOf('0'),board=givens.slice(0,index)+puzzle.solution[index]+givens.slice(index+1);await act(s[0],'board',{board});let other=await act(s[1],'state');assert.equal(other.puzzle.givens,givens);assert.equal(other.board,givens);assert.equal('boards' in other,false);assert.equal(other.progress.find(p=>p.player===s[0].id).filled,35);await act(s[0],'board',{board:'bad'},400);const fixed=[...givens].findIndex(v=>v!=='0');await act(s[0],'board',{board:givens.slice(0,fixed)+'0'+givens.slice(fixed+1)},400);await act(s[0],'finish',{board},400);
 room=await act(s[0],'finish',{board:puzzle.solution});assert.equal(room.phase,'race');assert.ok(room.ready.includes(s[0].id));await act(s[0],'board',{board},409);await act(s[1],'finish',{board:puzzle.solution});room=await act(s[2],'give_up');assert.equal(room.phase,'reveal');assert.equal(room.result.standings[0].player,s[0].id);assert.deepEqual(room.result.standings.map(p=>p.points),[16,14,0]);assert.equal(room.result.solution,puzzle.solution);assert.ok(room.result.standings[0].time>=10);room=await act(s[0],'next');assert.equal(room.phase,'finished');
});
test('Sudoku hints fill a selected cell and use adjusted race times; puzzle reset avoids recent bases',async()=>{
 const s=await create('sudoku-race',2);let room=await startRace(s,{difficulty:'hard',rounds:3});const puzzle=await storedPuzzle(s[0]),id=room.puzzleKey,blanks=[...puzzle.givens].map((v,i)=>v==='0'?i:-1).filter(i=>i>=0);let board=room.board;
 for(const index of blanks.slice(0,3)){room=await act(s[0],'hint',{board,index});board=room.board;assert.equal(board[index],puzzle.solution[index]);}assert.equal(room.hints,3);await act(s[0],'hint',{board,index:blanks[3]},409);await act(s[0],'hint',{board,index:100},400);assert.equal((await act(s[1],'state')).hints,0);await act(s[0],'finish',{board:puzzle.solution});await editRoom(s[0],r=>{r.raceStarts=Date.now()/1000-20;});room=await act(s[1],'finish',{board:puzzle.solution});assert.equal(room.phase,'reveal');assert.equal(room.result.standings[0].player,s[1].id);assert.equal(room.result.standings[1].hints,3);assert.ok(room.result.standings[1].adjustedTime>=100);await act(s[0],'reset');room=await act(s[0],'start',{difficulty:'hard',recent:[id]});assert.notEqual(room.puzzleKey,id);
});
test('Sudoku Race timeout awards no points for filling incorrect cells, and solo sessions finish and restart',async()=>{
 const s=await create('sudoku-race',1);let room=await startRace(s,{rounds:1,difficulty:'easy'});const wrong=[...room.board].map(v=>v==='0'?'1':v).join('');await act(s[0],'board',{board:wrong});await act(s[0],'finish',{board:wrong},400);await editRoom(s[0],r=>{r.deadline=Date.now()/1000-1;});room=await act(s[0],'state');assert.equal(room.phase,'reveal');assert.equal(room.result.standings[0].solved,false);assert.equal(room.result.standings[0].points,0);await act(s[0],'next');room=await act(s[0],'again',{difficulty:'easy',rounds:1});assert.equal(room.round,1);assert.equal(room.players[0].score,0);
});
test('puzzle-bank HTTP requests never reveal the server-side solutions',async()=>{
 for(const file of ['api/puzzle-data.php','api/puzzle-games.php']){const res=await fetch(base+file);assert.equal(res.status,200);assert.equal(await res.text(),'');}const res=await fetch(base+'api/word-circuit-words.txt');assert.equal(res.status,200);assert.ok((await res.text()).includes('\ncold\n'));
});
