import test,{beforeEach,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {parseHTML} from 'linkedom';
import jsQR from './vendor/jsQR.cjs';
import {inviteUrl,inviteMatrix,qrSvg} from '../shared/invite-qr.js';
import {setupInvites} from '../shared/party-invite.js';
import {games} from '../games.js';
const realTimeout=globalThis.setTimeout;
let descriptors,window,document,timers,intervals,media,sessionStore,current,calls,shareCalls,focus;
const ids=['document','window','location','history','navigator','matchMedia','localStorage','sessionStorage','fetch','setInterval','clearInterval','setTimeout','clearTimeout','confirm'];
beforeEach(()=>{descriptors=new Map(ids.map(id=>[id,Object.getOwnPropertyDescriptor(globalThis,id)]));timers=new Map();intervals=[];media={matches:true,callbacks:[],addEventListener(event,fn){this.callbacks.push(fn);}};sessionStore=new Map();calls=[];shareCalls=[];focus=null;});
afterEach(()=>{for(const [id,desc] of descriptors){if(desc)Object.defineProperty(globalThis,id,desc);else delete globalThis[id];}});
function set(name,value){Object.defineProperty(globalThis,name,{value,writable:true,configurable:true});}
async function dom(game,sharing=true){media={matches:true,callbacks:[],addEventListener(event,fn){this.callbacks.push(fn);}};({window,document}=parseHTML(await readFile(new URL(`../games/${game}/index.html`,import.meta.url),'utf8')));set('document',document);set('window',window);set('location',{href:`https://party.example.com/friends/friday/games/${game}/`});set('history',{replaceState(a,b,url){location.href=url;}});set('navigator',{clipboard:{writeText:async()=>{}},...(sharing?{share:async value=>shareCalls.push(value)}:{})});set('matchMedia',query=>query.includes('reduced-motion')?{matches:true}:media);set('localStorage',{getItem:()=>null,setItem:()=>{}});set('sessionStorage',{getItem:key=>sessionStore.get(key),setItem:(key,value)=>sessionStore.set(key,value),removeItem:key=>sessionStore.delete(key)});set('setInterval',fn=>{intervals.push(fn);return intervals.length;});set('clearInterval',()=>{});set('setTimeout',(fn,delay)=>{const key={};timers.set(key,{fn,delay});return key;});set('clearTimeout',key=>timers.delete(key));set('confirm',()=>true);
window.HTMLElement.prototype.showModal=function(){this.open=true;};window.HTMLElement.prototype.close=function(){this.open=false;};window.HTMLElement.prototype.scrollIntoView=function(){this.dataset.scrolled='true';};window.HTMLElement.prototype.focus=function(){focus=this;};window.HTMLElement.prototype.blur=function(){focus=null;};Object.defineProperty(document,'activeElement',{get:()=>focus,configurable:true});
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get(){return [...this.options].find(o=>o.selected)?.value||this.options[0]?.value||'';},set(value){for(const o of this.options)o.selected=o.value===String(value);},configurable:true});
set('fetch',async(url,options)=>{if(!options){return {ok:true,text:async()=> 'cold\ncord\ncard\nward\nwarm\n'};}const input=JSON.parse(options.body);calls.push(input);current.version++;return {ok:true,json:async()=>({room:structuredClone(current),...(input.action==='create'?{session:{game,code:current.code,id:current.you,token:'test-only'}}:{})})};});
return document;}
const flush=async()=>{await new Promise(resolve=>realTimeout(resolve,0));await new Promise(resolve=>realTimeout(resolve,0));};
const base=game=>({game,code:'ABCDE',host:'host',you:'you',phase:'lobby',round:0,maxRounds:3,version:1,participants:[],result:null,players:[{id:'host',name:'Host',online:true,score:0},{id:'you',name:'You',online:true,score:0},{id:'other',name:'Other',online:true,score:0},{id:'fourth',name:'Fourth',online:true,score:0}],serverTime:Date.now()/1000,deadline:Date.now()/1000+90,ready:[]});
async function enter(){document.getElementById('create-name').value='You';document.getElementById('create-form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));await flush();assert.equal(document.getElementById('notice').hidden,true,document.getElementById('notice').textContent);}
function decodeSvg(svg){const size=Number(svg.match(/viewBox="0 0 (\d+) /)[1]),scale=5,width=size*scale,rgba=new Uint8ClampedArray(width*width*4).fill(255);for(const m of svg.matchAll(/M(\d+),(\d+)h1v1h-1z/g)){const col=Number(m[1]),row=Number(m[2]);for(let y=0;y<scale;y++)for(let x=0;x<scale;x++){const p=((row*scale+y)*width+col*scale+x)*4;rgba[p]=rgba[p+1]=rgba[p+2]=0;}}return jsQR(rgba,width,width)?.data;}
test('invite SVGs independently decode to exact game URLs for all nine live games, including renamed folders and Unicode paths',()=>{
 for(const game of games.filter(g=>g.id!=='barcraft'))for(const href of [`https://example.com/${game.path}`,`https://example.com/friends/friday/${game.path}?token=private&room=OLD23#private`,`https://example.com/soirée/ゲーム/${game.path}`]){const url=inviteUrl(href,'ABCDE');assert.equal(decodeSvg(qrSvg(inviteMatrix(url))),url);assert.ok(!url.includes('private'));assert.ok(url.endsWith('?room=ABCDE'));}assert.throws(()=>inviteUrl('https://example.com/','bad'),/Invalid party code/);
});
test('all live games offer QR enlargement, native sharing, and mobile drawer behavior without recreating the QR on every poll',async()=>{
 for(const game of games.filter(g=>g.id!=='barcraft')){await dom(game.id);const reports=[],invites=setupInvites(document,location,navigator,text=>reports.push(text));const room=base(game.id);const url=invites.update(room),drawer=document.querySelector('.party-drawer');assert.equal(drawer.open,true);assert.equal(decodeSvg(document.querySelector('.qr-image').innerHTML),url);const original=document.querySelector('.qr-image svg');invites.update(room);assert.equal(document.querySelector('.qr-image svg'),original);document.querySelector('.invite-qr').click();assert.equal(document.querySelector('.qr-dialog').open,true);assert.equal(document.querySelector('.qr-room-code').textContent,'ABCDE');document.querySelector('.share-button').click();await flush();assert.equal(shareCalls.at(-1).url,url);room.phase='race';invites.update(room);assert.equal(drawer.open,false);drawer.open=true;invites.update(room);assert.equal(drawer.open,true);media.matches=false;media.callbacks.forEach(fn=>fn());assert.equal(drawer.open,true);invites.close();assert.equal(document.querySelector('.qr-dialog').open,false);assert.deepEqual(reports,[]);}
});
test('invite links and QR work without native mobile sharing support',async()=>{await dom('imposter',false);const invites=setupInvites(document,location,navigator,()=>{});invites.update(base('imposter'));assert.equal(document.querySelector('.share-button').hidden,true);assert.ok(document.querySelector('.qr-image svg'));assert.match(document.getElementById('share-link').value,/room=ABCDE/);});
test('mobile card selection shows Pick 2 order and preserves horizontal hand position when another player submits',async()=>{
 await dom('humanity');current={...base('humanity'),phase:'playing',round:1,participants:['host','you','other','fourth'],judge:'host',prompt:{text:'Combine _____ with _____.',pick:2},targetScore:7,submitted:[],hand:Array.from({length:10},(_,i)=>({id:`card${i}`,text:`Response ${i}`})),yourPlay:null};const {startJudgingGame}=await import('../shared/judging-game.js');startJudgingGame('humanity');await enter();const hand=document.querySelector('.card-grid');hand.scrollLeft=170;document.querySelector('[data-card="card3"]').click();document.querySelector('[data-card="card1"]').click();assert.deepEqual([...document.querySelectorAll('#selected-cards li')].map(n=>n.textContent),['Response 3','Response 1']);assert.equal(document.querySelector('[data-card="card3"]').getAttribute('aria-pressed'),'true');current.submitted=['other'];const poll=[...timers.values()].find(t=>t.delay===1100);await poll.fn();await flush();assert.equal(document.querySelector('.card-grid').scrollLeft,170);assert.deepEqual([...document.querySelectorAll('#selected-cards li')].map(n=>n.textContent),['Response 3','Response 1']);document.getElementById('play-cards').click();await flush();assert.deepEqual(calls.at(-1).cards,['card3','card1']);
});
test('mobile Scattergories Enter advances through answers without locking the sheet',async()=>{
 await dom('scattergories');current={...base('scattergories'),phase:'writing',round:1,participants:['host','you'],letter:'B',categories:Array.from({length:12},(_,i)=>`Category ${i+1}`),yourAnswers:[]};await import('../games/scattergories/app.js');await enter();const inputs=document.querySelectorAll('.answer-field input');assert.equal(inputs[0].enterKeyHint,'next');assert.equal(inputs[11].enterKeyHint,'done');const event=new window.Event('keydown',{bubbles:true,cancelable:true});event.key='Enter';inputs[0].dispatchEvent(event);assert.equal(event.defaultPrevented,true);assert.equal(focus,inputs[1]);assert.equal(calls.some(c=>c.action==='submit'),false);inputs[11].dispatchEvent(event);assert.equal(focus,null);
});
test('mobile Hive Mind starts with a compact board and Enter advances instead of submitting answers',async()=>{
 await dom('hivemind');current={...base('hivemind'),phase:'answering',round:1,participants:['host','you','other'],active:'host',hiveSize:6,levels:{host:0,you:0,other:0},die:{dots:1,star:false},prompt:{text:'Name three animals.',count:3},yourAnswers:[]};await import('../shared/hivemind.js');await enter();assert.equal(document.querySelector('.hive-board-panel').open,false);const inputs=document.querySelectorAll('.hive-answer'),event=new window.Event('keydown',{bubbles:true,cancelable:true});event.key='Enter';inputs[0].dispatchEvent(event);assert.equal(focus,inputs[1]);assert.equal(calls.some(c=>c.action==='submit'),false);
});
test('Wavelength touch nudges send precise guesses and respect spectrum bounds',async()=>{
 await dom('wavelength');current={...base('wavelength'),phase:'guess',round:1,participants:['host','you','other'],giver:'other',clue:'A nice bath',spectrum:['Cold','Hot'],guesses:{you:0},groupGuess:0,totalScore:0,history:[]};await import('../games/wavelength/app.js');await enter();const buttons=document.querySelectorAll('.dial-adjustments button');buttons[0].click();await flush();assert.equal(calls.at(-1).value,0);buttons[1].click();await flush();assert.equal(calls.at(-1).value,1);assert.equal(document.querySelector('.guess-control output').textContent,'1');
});
test('Sudoku touch number pad, pencil notes, selected-cell preview and erase work without a keyboard',async()=>{
 await dom('sudoku-race');current={...base('sudoku-race'),phase:'race',round:1,participants:['host','you'],startsAt:Date.now()/1000-10,puzzle:{givens:'0'.repeat(81)},board:'0'.repeat(81),hints:0,finishTime:null,difficulty:'easy',progress:[]};await import('../games/sudoku-race/app.js');await enter();assert.equal(document.querySelectorAll('.sudoku-cell').length,81);assert.equal(document.querySelectorAll('.digit-key').length,10);document.getElementById('cell-8').click();assert.match(document.getElementById('cell-inspector').textContent,/Row 1, column 9/);document.getElementById('pencil-mode').click();document.querySelectorAll('.digit-key')[2].click();assert.equal(document.getElementById('cell-8').querySelector('.cell-notes').textContent,'3');document.querySelector('.erase-key').click();assert.equal(document.getElementById('cell-8').querySelector('.cell-notes').hidden,true);document.getElementById('pencil-mode').click();document.querySelectorAll('.digit-key')[4].click();assert.equal(document.getElementById('cell-8').querySelector('.cell-value').textContent,'5');assert.match(document.getElementById('cell-inspector').textContent,/· 5/);assert.ok(document.querySelector('.sudoku-tools #finish-grid'));
});
