import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {inspectWord} from '../games/word-circuit/rules.js';
import {sudokuPeers,sudokuConflicts,validDraft} from '../games/sudoku-race/rules.js';
const source=readFileSync(new URL('../api/puzzle-data.php',import.meta.url),'utf8');
const data=JSON.parse(source.split("<<<'PUZZLES'\n")[1].split('\nPUZZLES')[0]);
const words=new Set(readFileSync(new URL('../api/word-circuit-words.txt',import.meta.url),'utf8').trim().split('\n'));
test('all 5,400 Word Circuit prompts have dictionary-valid routes and true shortest distances',()=>{
 const patterns=new Map(),graph=new Map();for(const w of words)for(let i=0;i<w.length;i++){const p=w.slice(0,i)+'*'+w.slice(i+1);if(!patterns.has(p))patterns.set(p,[]);patterns.get(p).push(w);}for(const w of words){const next=new Set();for(let i=0;i<w.length;i++)for(const n of patterns.get(w.slice(0,i)+'*'+w.slice(i+1)))if(n!==w)next.add(n);graph.set(w,[...next]);}
 let count=0;const pairs=new Set(),cache=new Map();for(const [difficulty,deck] of Object.entries(data.circuit)){assert.equal(deck.length,1800);for(const p of deck){count++;assert.equal(p.solution[0],p.start);assert.equal(p.solution.at(-1),p.end);assert.equal(p.solution.length-1,p.optimal);assert.equal(new Set(p.solution).size,p.solution.length);const pair=[p.start,p.end].sort().join('|');assert.ok(!pairs.has(pair));pairs.add(pair);for(let i=0;i<p.solution.length;i++){assert.ok(words.has(p.solution[i]));if(i)assert.equal([...p.solution[i]].filter((c,j)=>c!==p.solution[i-1][j]).length,1);}if(!cache.has(p.start)){const distance=new Map([[p.start,0]]),queue=[p.start];for(let i=0;i<queue.length;i++){const w=queue[i];if(distance.get(w)>=9)continue;for(const n of graph.get(w))if(!distance.has(n)){distance.set(n,distance.get(w)+1);queue.push(n);}}cache.set(p.start,distance);}assert.equal(cache.get(p.start).get(p.end),p.optimal);assert.ok(difficulty==='easy'?p.start.length===4:p.start.length>=4);}}assert.equal(count,5400);assert.equal(words.size,16604);
});
function solutions(value){const board=[...value].map(Number),rows=Array(9).fill(0),cols=Array(9).fill(0),boxes=Array(9).fill(0);for(let i=0;i<81;i++)if(board[i]){const r=Math.floor(i/9),c=i%9,b=Math.floor(r/3)*3+Math.floor(c/3),bit=1<<board[i];if((rows[r]|cols[c]|boxes[b])&bit)return 0;rows[r]|=bit;cols[c]|=bit;boxes[b]|=bit;}function visit(){let chosen=-1,mask=0,min=10;for(let i=0;i<81;i++)if(!board[i]){const r=Math.floor(i/9),c=i%9,b=Math.floor(r/3)*3+Math.floor(c/3),possible=1022&~(rows[r]|cols[c]|boxes[b]),n=possible.toString(2).replaceAll('0','').length;if(!n)return 0;if(n<min){chosen=i;mask=possible;min=n;}if(n===1)break;}if(chosen<0)return 1;const r=Math.floor(chosen/9),c=chosen%9,b=Math.floor(r/3)*3+Math.floor(c/3);let total=0;while(mask){const bit=mask&-mask;mask-=bit;board[chosen]=Math.log2(bit);rows[r]|=bit;cols[c]|=bit;boxes[b]|=bit;total+=visit();rows[r]^=bit;cols[c]^=bit;boxes[b]^=bit;board[chosen]=0;if(total>=2)return 2;}return total;}return visit();}
test('all 450 Sudoku puzzles have exactly one solution, correct clue density and valid solved grids',()=>{
 const unique=new Set();for(const [level,deck] of Object.entries(data.sudoku)){assert.equal(deck.length,150);for(const p of deck){assert.match(p.givens,/^[0-9]{81}$/);assert.match(p.solution,/^[1-9]{81}$/);assert.equal(p.givens.replaceAll('0','').length,{easy:42,medium:34,hard:28}[level]);assert.ok(validDraft(p.solution,p.givens));assert.equal(sudokuConflicts(p.solution).size,0);assert.equal(solutions(p.givens),1);assert.ok(!unique.has(p.givens));unique.add(p.givens);}}
});
test('Word Circuit input feedback rejects fake words, length changes, rearranging and loops',()=>{const dictionary=new Set(['cold','cord','card','ward']);assert.equal(inspectWord(' CORD ',['cold'],dictionary),'Valid next word.');assert.equal(inspectWord('czld',['cold'],dictionary),'Not in the game dictionary.');assert.equal(inspectWord('colder',['cold'],dictionary),'Use 4 letters.');assert.equal(inspectWord('clod',['cold'],dictionary),'Change exactly one letter.');assert.equal(inspectWord('cold',['cold','cord'],dictionary),'Already in your route. Undo to return.');});
test('Sudoku peer, duplicate and draft checks respect rows, columns, boxes and immutable clues',()=>{assert.equal(sudokuPeers(40).size,20);const blank='0'.repeat(81),conflict='1'+blank.slice(1,10)+'1'+blank.slice(11);assert.deepEqual([...sudokuConflicts(conflict)].sort((a,b)=>a-b),[0,10]);assert.equal(validDraft(blank,'1'+blank.slice(1)),false);assert.equal(validDraft(blank,blank),true);assert.equal(validDraft('a'.repeat(81),blank),false);assert.equal(validDraft('0',blank),false);});
