import {$,setupParty,perform,lobbyContent,roomControls,playerName,notice} from '../../shared/party-ui.js';
import {el,button,scores} from '../../shared/game-tools.js';
let latest,client,key='',offset=0,trapKey='',acknowledged=new Set(),pending=false;
const channelNames={popup:'Popup bureau',notification:'Notification desk',error:'Error department',buttons:'Button control'};
const trapAction={popup:'Install now',notification:'Open message',error:'Restart workflow',buttons:'Use shortcut'};
const icons={TripDesk:'✈','File Cabinet':'▤',Mailroom:'✉',DayPlan:'▦','Tiny Store':'◈'};
function remaining(){return Math.max(0,Math.ceil(latest.deadline-(Date.now()/1000+offset)));}
function liveTraps(){return (latest.traps||[]).filter(t=>t.expires>Date.now()/1000+offset);}
function clock(){if(!latest||latest.phase!=='desktop')return;const left=remaining(),node=$('disaster-clock');if(node){node.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;node.classList.toggle('urgent',left<20);}const cooling=Math.max(0,Math.ceil((latest.cooldown||0)-(Date.now()/1000+offset)));for(const node of document.querySelectorAll('.deploy-trap')){node.disabled=left===0||cooling>0||latest.yourStats.deployed>=10||liveTraps().length>=3;node.textContent=cooling?`Recharging · ${cooling}s`:'Deploy gadget';}const action=$('desktop-action');if(action)action.disabled=latest.you!==latest.active||left===0||pending;if($('desktop-input'))$('desktop-input').disabled=latest.you!==latest.active||left===0;if($('desktop-decoy'))$('desktop-decoy').disabled=latest.you!==latest.active||left===0;drawTraps();}
async function desktopAction(action,payload){if(pending)return;pending=true;clock();try{await client.act(action,payload);notice('');}catch(error){notice(error.message);}finally{pending=false;clock();}}
function drawTraps(){const layer=$('trap-layer');if(!layer||!latest)return;const traps=liveTraps(),serial=traps.map(t=>t.id).join(',');if(latest.you===latest.active){const unseen=traps.filter(t=>!t.seen&&!acknowledged.has(t.id)).map(t=>t.id);if(unseen.length){unseen.forEach(id=>acknowledged.add(id));client.act('seen',{traps:unseen}).catch(()=>unseen.forEach(id=>acknowledged.delete(id)));}}if(serial===trapKey)return;trapKey=serial;layer.replaceChildren();const active=latest.you===latest.active;const action=$('desktop-action'),decoy=$('desktop-decoy');action?.classList.remove('shift-left','shift-right');if(decoy)decoy.hidden=true;
for(const [index,trap] of traps.entries()){
 if(trap.kind==='buttons'){action?.classList.add(trap.shift>0?'shift-right':'shift-left');if(decoy){decoy.hidden=false;decoy.textContent=latest.task.current.button;decoy.onclick=()=>desktopAction('hit',{trap:trap.id});}continue;}
 const box=el('div','',`desktop-trap trap-${trap.kind}`);box.style.setProperty('--trap-index',index);const bar=el('div','','trap-title');bar.append(el('span',trap.kind==='error'?'System message':trap.kind==='notification'?'New notification':'Important update'));const close=button('×',()=>desktopAction('dismiss',{trap:trap.id}),'trap-close');close.setAttribute('aria-label','Dismiss desktop message safely');close.disabled=!active;bar.append(close);box.append(bar,el('p',trap.text));const actions=el('div','','trap-actions'),bait=button(trapAction[trap.kind],()=>desktopAction('hit',{trap:trap.id}),'trap-bait'),safe=button(trap.kind==='error'?'Ignore':'Dismiss',()=>desktopAction('dismiss',{trap:trap.id}),'trap-safe');bait.disabled=safe.disabled=!active;actions.append(bait,safe);box.append(actions);layer.append(box);
}
}
function fakeDesktop(room){const active=room.you===room.active,node=el('div','','fake-desktop');const chrome=el('div','','desktop-chrome');chrome.append(el('span','● ● ●','window-dots'),el('strong','Workstation 01'),el('span','Simulated desktop','desktop-sim'));node.append(chrome);
const dock=el('div','','desktop-dock');for(const [name,icon] of Object.entries(icons)){const app=el('span',`${icon} ${name}`);app.classList.toggle('open',name===room.task.app&&room.step>0);dock.append(app);}node.append(dock);
const window=el('div','','task-window'),bar=el('div','','task-title');bar.append(el('strong',room.step===0?'Launch an application':`${icons[room.task.app]} ${room.task.app}`),el('span',`${room.step+1} / ${room.task.steps}`));window.append(bar);
const current=room.task.current;window.append(el('h3',current.title));if(current.body)window.append(el('pre',current.body,'file-memo'));const form=el('form','','desktop-form'),label=el('label',current.input==='text'?'Enter the mission detail':'Select an option');let input;
if(current.input==='text'){input=el('input');input.type='text';input.maxLength=100;input.autocomplete='off';input.spellcheck=false;input.placeholder='Type the exact detail…';}else{input=el('select');const placeholder=el('option','Choose…');placeholder.value='';input.append(placeholder);for(const choice of current.choices){const option=el('option',choice.label);option.value=choice.id;input.append(option);}}
input.id='desktop-input';input.required=true;input.setAttribute('aria-label',current.title);input.disabled=!active;label.append(input);form.append(label);const actionRow=el('div','','desktop-action-row'),action=button(current.button,()=>{},'workflow-button');action.id='desktop-action';action.type='submit';action.disabled=!active;const decoy=button(current.button,()=>{},'decoy-button');decoy.id='desktop-decoy';decoy.type='button';decoy.hidden=true;decoy.setAttribute('aria-label','Run desktop shortcut');actionRow.append(decoy,action);form.append(actionRow);form.addEventListener('submit',event=>{event.preventDefault();desktopAction('step',{step:room.step,value:input.value});});window.append(form);
if(room.step>0){const back=button('← Previous step',()=>desktopAction('back',{}),'desktop-back');back.disabled=!active;window.append(back);}node.append(window);const layer=el('div','','trap-layer');layer.id='trap-layer';node.append(layer);return node;}
function gadgetControls(room){const panel=el('section','','gadget-controls');panel.append(el('h2','Cause a little trouble.'),el('p',`Your channels stay secret. ${room.yourStats.deployed} / 10 gadgets used · ${room.roundPoints} points this round.`,'stage-copy'));const grid=el('div','','gadget-grid');for(const kind of room.channels){const card=el('div','','gadget-card');card.append(el('h3',channelNames[kind]),el('p',kind==='buttons'?'Move the real action and leave a tempting shortcut behind.':'Drop a distracting message onto the active desktop.'));const select=el('select');select.setAttribute('aria-label',`${channelNames[kind]} message`);room.gadgetDeck[kind].forEach((text,index)=>{const option=el('option',text);option.value=index;select.append(option);});select.selectedIndex=Math.floor(Math.random()*select.options.length);card.append(select,button('Deploy gadget',()=>perform(client,'trap',{kind,index:Number(select.value)}),'deploy-trap'));grid.append(card);}panel.append(grid,el('p','Seven-second recharge. Three traps can be live at once. Traps disappear after twelve seconds.','gadget-note'));return panel;}
function render(room,c){if(!room){key='';latest=null;trapKey='';acknowledged=new Set();return;}latest=room;client=c;offset=room.serverTime-Date.now()/1000;roomControls(room,c);const nextKey=[room.code,room.phase,room.round,room.active,room.host,room.step,JSON.stringify(room.yourStats)].join(':');if(key===nextKey){clock();if(room.phase==='lobby'&&$('start-game'))$('start-game').disabled=room.players.filter(p=>p.online).length<2;return;}const sameWorkflow=key.startsWith(`${room.code}:desktop:${room.round}:`)&&room.phase==='desktop';const sameStep=sameWorkflow&&Number(key.split(':')[5])===room.step;const draft=sameStep?$('desktop-input')?.value:null;key=nextKey;trapKey='';const stage=$('game-stage');stage.replaceChildren();const host=room.you===room.host,active=room.you===room.active,participant=room.participants.includes(room.you);
if(room.phase==='lobby'){lobbyContent(room,'desktop-disaster');$('start-game')?.addEventListener('click',()=>perform(c,'start'));return;}
if(room.phase==='finished'){stage.append(el('h2','The IT department needs a holiday.'),scores(room));if(host)stage.append(button('Run another shift',()=>perform(c,'again')));return;}
const mission=el('div','','mission-banner'),copy=el('div');copy.append(el('span',active?'Your mission':`${playerName(room,room.active)}’s mission`,'eyebrow'),el('h2',room.task.text));mission.append(copy);if(room.phase==='desktop'){const time=el('strong','','disaster-clock');time.id='disaster-clock';time.setAttribute('aria-label','Time remaining');mission.append(time);}stage.append(mission);
if(room.phase==='desktop'){if(!sameWorkflow)acknowledged=new Set();stage.append(el('p',active?'Finish the workflow. Ignore distractions and check every detail.':participant?'Watch the live desktop. Your sabotage controls are below.':'You’ll join the next shift. Watch the live desktop.','desktop-role'),fakeDesktop(room));if(!active&&room.channels)stage.append(gadgetControls(room));if(sameStep&&draft&&$('desktop-input')){const input=$('desktop-input');if(input.type==='text'||[...input.options].some(o=>o.value===draft))input.value=draft;}clock();return;}
if(room.phase==='reveal'){stage.append(el('h2',room.result.skipped?'Shift skipped':room.result.success?'Task completed. Chaos defeated.':'The desktop won.'),el('p',room.result.reason,'stage-copy'));if(!room.result.skipped){const recap=el('div','','disaster-recap');for(const id of room.participants){const row=el('div','','recap-row');const stats=room.result.stats[id];row.append(el('strong',playerName(room,id)),el('span',id===room.active?'Active player':room.result.channels[id].map(kind=>channelNames[kind]).join(' + ')),el('span',stats?`${stats.seen} seen · ${stats.hits} successful traps`:`${room.result.remaining}s left`),el('strong',`+${room.result.scores[id]}`));recap.append(row);}stage.append(recap);}stage.append(scores(room));if(host)stage.append(button(room.round===room.maxRounds?'See final scores':'Rotate roles',()=>perform(c,'next')));else stage.append(el('p','Waiting for the host to rotate roles.','stage-copy'));}}
setupParty('desktop-disaster',render);setInterval(clock,250);
