import {PartyClient} from '../../shared/party-client.js?v=20261009-party-1';
import {followGame,gameUrl} from '../../shared/party-navigation.js?v=20261009-party-1';
import {setupComfort} from '../../shared/ui-comfort.js?v=20261009-party-1';
import {BeatEngine,tracks} from './audio.js?v=20261009-party-1';
import {createRhymeChain,getWordPool,wordBankSize} from './rhymes.js?v=20261009-party-1';
import {WordMemory} from './word-memory.js?v=20261009-party-1';
setupComfort(document);
const $=id=>document.getElementById(id),engine=new BeatEngine();
let storage;try{storage=localStorage;}catch{storage=null;}
const memory=WordMemory.load(storage);
const words={
 Everyday:{easy:['midnight','coffee','window','sneakers','mirror','pocket','radio','weekend','ticket','rooftop','paper','story','kitchen','train','city','phone','dinner','jacket','morning','backpack'],hard:['elevator','conversation','neighborhood','silhouette','electricity','celebration','photograph','calendar','architecture','ordinary']},
 Culture:{easy:['rhythm','vinyl','canvas','movie','legend','stage','chorus','fashion','poetry','record','spotlight','dance','screen','melody','graffiti','artist','remix','culture','stereo','encore'],hard:['cinematic','renaissance','improvisation','masterpiece','choreography','underground','instrumental','revolution','documentary','symphony']},
 Nature:{easy:['ocean','thunder','river','sunset','mountain','storm','forest','moonlight','desert','bloom','cloud','rain','island','sunrise','winter','wave','petal','breeze','jungle','seasons'],hard:['horizon','constellation','avalanche','evergreen','atmosphere','ecosystem','wildflower','supernova','butterfly','wilderness']},
 Feelings:{easy:['hope','fear','freedom','dream','pride','peace','love','doubt','trust','joy','courage','heart','focus','spark','hunger','calm','wonder','strength'],hard:['nostalgia','resilience','ambition','vulnerability','euphoria','gratitude','determination','melancholy','confidence','perspective']},
 Street:{easy:['corner','block','subway','hustle','lights','concrete','alley','crew','asphalt','bridge','metro','uptown','stoop','district','court','downtown','crosswalk','skyline'],hard:['intersection','boulevard','metropolis','community','skyscraper','infrastructure','gentrification','entrepreneur','navigation','underdog']},
 Wildcard:{easy:['dragon','space','pizza','robot','magic','pirate','rocket','castle','glitch','treasure','ghost','laser','wizard','puzzle','galaxy','tiger','diamond','kingdom'],hard:['paradox','teleportation','kaleidoscope','dinosaur','algorithm','labyrinth','hypnotize','parallel','extraterrestrial','serendipity']}
};
let categories=['Everyday','Culture','Nature'],positions=['end'],grid=4,level='easy',countin=true,track=tracks[0],limit=16,queue=[],busy=false,lastBar=0,totalCues=0,completed=false;
let rhymeLength=4,chainBuffer=[],previousFamily=null,chainNumber=0,beatFilter='all';
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
function makePrompt(){let entry;if(rhymeLength){if(!chainBuffer.length){chainNumber++;chainBuffer=createRhymeChain({categories,level,length:rhymeLength,previousFamily,usedWords:memory.words,recentFamilies:memory.families}).map(p=>({...p,chainId:chainNumber}));previousFamily=chainBuffer[0].rhymeFamily;memory.rememberFamily(previousFamily);}entry=chainBuffer.shift();}else{const extras=categories.flatMap(category=>words[category][level].map(word=>({word,category})));const pool=[...new Map([...getWordPool(categories,level),...extras].map(p=>[p.word.toLowerCase(),p])).values()];entry=memory.pick(pool);}memory.remember(entry.word);memory.save(storage);const position=positions[Math.floor(Math.random()*positions.length)];const sub=grid/4,offset=Math.floor(Math.random()*sub)/sub;return{...entry,position,beat:({beginning:0,middle:2,end:3}[position])+offset};}
function clearPrompts(){queue=[];chainBuffer=[];previousFamily=null;chainNumber=0;}
function replenish(){while(queue.length<5)queue.push(makePrompt());}
function rhythmLabel(beat){const integer=Math.floor(beat)+1,fraction=beat%1;return fraction===0?`beat ${integer}`:`the ${fraction===.25?'e':fraction===.5?'&':'a'} of ${integer}`;}
function setWord(text,animate=false){const el=$('word');if(el.textContent===text)return;el.getAnimations().forEach(a=>a.cancel());if(animate&&!reducedMotion){const old=el.cloneNode(true);old.removeAttribute('id');old.classList.add('outgoing-word');el.parentElement.append(old);const out=old.animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(-22px)'}],{duration:240,easing:'cubic-bezier(.2,.6,.3,1)'});out.onfinish=()=>old.remove();}el.textContent=text;el.classList.toggle('long-word',text.length>10);if(animate&&!reducedMotion)el.animate([{opacity:0,transform:'translateY(22px)'},{opacity:1,transform:'translateY(0)'}],{duration:280,easing:'cubic-bezier(.2,.6,.3,1)'});}
function renderPrompt(animate=false){replenish();const prompt=queue[0];setWord(prompt.word,animate);$('prompt-category').textContent=prompt.category;$('target').textContent=`Land it on ${rhythmLabel(prompt.beat)}`;$('note').textContent=grid===4?'♩':grid===8?'♫':'♬';$('target-marker').style.left=`${(prompt.beat+.5/(grid/4))/4*100}%`;
  $('rhyme-info').textContent=prompt.rhymeFamily?`Rhyming ${prompt.rhymeLabel} · ${prompt.chainIndex} of ${prompt.chainLength}`:'Free association';
  $('word-bank-size').textContent=`${getWordPool(categories,level).length.toLocaleString()} words in your mix · fresh words first`;
  const future=queue.slice(1,5).filter((p,i)=>!limit||lastBar+i+1<limit);
  $('queue').innerHTML=future.map((p,i)=>`<div class="queue-item ${p.chainId!==prompt.chainId&&rhymeLength?'new-chain':''}"><span class="future-bar">${String(lastBar+i+2).padStart(2,'0')}</span><div><strong>${p.word}</strong><small>${p.rhymeFamily?(p.chainId!==prompt.chainId?'New rhyme · ':'')+p.rhymeLabel:p.category}</small></div><span class="future-target">${Math.floor(p.beat)+1}${p.beat%1===.5?'&':p.beat%1===.25?'e':p.beat%1===.75?'a':''}<small>beat</small></span></div>`).join('');
  if(!future.length)$('queue').innerHTML='<div class="queue-empty">Last bar. Bring it home.</div>';
  $('queue').style.transform='translateY(0)';$('queue').classList.toggle('short-queue',future.length<3);renderGrid();}
function renderGrid(){const count=grid,sub=grid/4;const labels=grid===4?['1','2','3','4']:grid===8?['1','&','2','&','3','&','4','&']:['1','e','&','a','2','e','&','a','3','e','&','a','4','e','&','a'];$('ticks').innerHTML=Array.from({length:count},(_,i)=>`<span class="tick ${i%sub===0?'major':''} ${i/sub===queue[0].beat?'target-tick':''}"></span>`).join('');$('beat-labels').innerHTML=labels.map((label,i)=>`<span class="${i/sub===queue[0].beat?'target-label':''}">${label}</span>`).join('');}
function shuffle(){clearPrompts();renderPrompt(true);toast(rhymeLength?'New rhyme chain. Keep your flow.':'Fresh words. Keep your flow.');}
function renderTracks(){const visible=tracks.filter(t=>beatFilter==='all'||(beatFilter==='real'?t.url:!t.url&&!t.file));$('beats').innerHTML=visible.map(t=>`<button class="beat-card ${t.id===track.id?'selected':''}" data-track="${t.id}" aria-pressed="${t.id===track.id}"><div class="artwork logo-art">${t.id===track.id?'<span class="selected-indicator">✓</span>':''}<img src="logos/${t.file?'custom':t.id}.svg" alt="" loading="lazy"></div><strong class="beat-title"></strong><span class="beat-sub"><span>${t.genre}</span><span>${t.bpm} BPM</span></span></button>`).join('');[...$('beats').querySelectorAll('.beat-title')].forEach((el,i)=>el.textContent=visible[i].name);$('track-name').textContent=track.name;$('track-description').textContent=track.description;$('bpm').value=engine.bpm;$('beat-count').textContent=tracks.length;}
function setPlayUI(){const active=engine.running;$('play-label').textContent=active?'Pause session':completed?'Go again':engine.elapsed>0?'Resume session':'Start session';$('play-icon').textContent=active?'Ⅱ':'▶';$('status-dot').classList.toggle('playing',active);}
function reset(){engine.stop();lastBar=0;totalCues=0;completed=false;clearPrompts();renderPrompt(true);$('bar').textContent='01';$('bar-total').textContent=limit?`/ ${limit}`:'/ ∞';$('status').textContent='Ready when you are';$('session-stats').textContent='Your next great bar starts here.';$('playhead').style.opacity=0;$('timeline-fill').style.width='0%';document.body.classList.remove('hit');setPlayUI();}
async function play(){if(busy)return;if(engine.running){engine.pause();$('status').textContent='Take a breath. Your beat is waiting.';setPlayUI();return;}busy=true;$('play').disabled=true;try{await engine.load(track);engine.offset=Number($('offset').value)||0;if(completed)reset();const position=engine.elapsed!==0?engine.elapsed:countin?-4:0;engine.play(position);setPlayUI();}catch(e){toast(e.message);$('status').textContent='Choose another beat to start.';}finally{busy=false;$('play').disabled=false;}}
async function selectTrack(id){if(busy)return;reset();track=tracks.find(t=>t.id===id);engine.bpm=track.bpm;engine.offset=0;$('offset').value=0;renderTracks();toast(`${track.name} is on the turntable.`);}
function changeTempo(value){const bpm=Math.max(60,Math.min(180,Number(value)||track.bpm));if(engine.running)engine.pause();engine.bpm=bpm;if(track.file){track.bpm=bpm;renderTracks();}$('bpm').value=bpm;setPlayUI();if(engine.elapsed!==0)$('status').textContent='Tempo changed. Press play to resume.';}
function applySettings(){clearPrompts();renderPrompt(true);if(engine.running)toast('New prompts ready. Keep going.');}
$('categories').addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;const c=b.dataset.category;if(categories.includes(c)){if(categories.length===1){toast('Keep at least one category selected.');return;}categories=categories.filter(x=>x!==c);}else categories.push(c);b.classList.toggle('selected');b.setAttribute('aria-pressed',categories.includes(c));$('category-count').textContent=`${categories.length} selected`;applySettings();});
$('placements').addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;const p=b.dataset.position;if(positions.includes(p)){if(positions.length===1){toast('Choose at least one word placement.');return;}positions=positions.filter(x=>x!==p);}else positions.push(p);b.classList.toggle('selected');b.setAttribute('aria-pressed',positions.includes(p));applySettings();});
$('difficulty').addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;level=b.dataset.level;[...$('difficulty').children].forEach(el=>{el.classList.toggle('selected',el===b);el.setAttribute('aria-pressed',el===b);});applySettings();});
$('notation').addEventListener('change',()=>{grid=Number($('notation').value);applySettings();});
$('rhyme-mode').addEventListener('change',()=>{rhymeLength=Number($('rhyme-mode').value);applySettings();});
$('mode').addEventListener('change',()=>{limit=Number($('mode').value);reset();});
$('countin').addEventListener('click',()=>{countin=!countin;$('countin').classList.toggle('on',countin);$('countin').setAttribute('aria-checked',countin);});
$('metronome').addEventListener('click',()=>{engine.metronome=!engine.metronome;$('metronome').classList.toggle('on',engine.metronome);$('metronome').setAttribute('aria-checked',engine.metronome);});
$('play').addEventListener('click',play);$('reset').addEventListener('click',reset);$('shuffle').addEventListener('click',shuffle);$('focus').addEventListener('click',()=>{document.body.classList.toggle('focus');$('focus').setAttribute('aria-pressed',document.body.classList.contains('focus'));});
$('volume').addEventListener('input',()=>{engine.setVolume(Number($('volume').value)/100);$('volume-label').textContent=$('volume').value+'%';});
$('beats').addEventListener('click',event=>{const b=event.target.closest('[data-track]');if(b)selectTrack(b.dataset.track);});
$('beat-filters').addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;beatFilter=b.dataset.filter;[...$('beat-filters').children].forEach(el=>{el.classList.toggle('selected',el===b);el.setAttribute('aria-pressed',el===b);});renderTracks();});
$('bpm').addEventListener('change',()=>changeTempo($('bpm').value));$('bpm-down').addEventListener('click',()=>changeTempo(engine.bpm-2));$('bpm-up').addEventListener('click',()=>changeTempo(engine.bpm+2));
$('offset').addEventListener('change',()=>{const value=Math.max(0,Math.min(60,Number($('offset').value)||0));$('offset').value=value;engine.offset=value;if(engine.running){engine.pause();$('status').textContent='Timing adjusted. Press play to resume.';setPlayUI();}});
$('upload').addEventListener('change',async()=>{const file=$('upload').files[0];if(!file)return;if(file.size>100*1024*1024){toast('Choose an audio file under 100 MB.');return;}if(busy)return;reset();busy=true;$('play').disabled=true;try{const custom={id:'custom',name:file.name.replace(/\.[^.]+$/,''),genre:'Your beat',bpm:90,description:'Your beat. Set the BPM and downbeat offset to sync the prompts.',file};await engine.load(custom);const previous=tracks.findIndex(t=>t.id==='custom');if(previous>=0)tracks.splice(previous,1);tracks.push(custom);track=custom;engine.bpm=90;engine.offset=0;$('offset').value=0;renderTracks();toast('Beat loaded. Set its BPM below.');}catch{toast('This file could not be decoded. Try an MP3, WAV, or M4A.');}finally{busy=false;$('play').disabled=false;}});
$('help').addEventListener('click',()=>$('help-dialog').showModal());$('close-help').addEventListener('click',()=>$('help-dialog').close());$('got-it').addEventListener('click',()=>$('help-dialog').close());
document.addEventListener('keydown',event=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(event.target.tagName)||$('help-dialog').open)return;if(event.code==='Space'){event.preventDefault();play();}if(event.key.toLowerCase()==='r')shuffle();if(event.key.toLowerCase()==='f')$('focus').click();if(event.key==='Escape'&&document.body.classList.contains('focus'))$('focus').click();});
$('mini-wave').innerHTML=Array.from({length:35},(_,i)=>`<i style="height:${6+Math.sin(i*1.8)**2*25}px"></i>`).join('');
let lastFrame=0;
function animate(now){requestAnimationFrame(animate);if(!engine.running)return;engine.tick();const pos=engine.position();if(pos<0){$('status').textContent=`Count in · ${Math.min(4,Math.max(1,5+Math.floor(pos)))} of 4`;return;}
  const bar=Math.floor(pos/4),fraction=pos%4;
  if(limit&&bar>=limit){engine.stop();completed=true;$('status').textContent='Session complete. That’s your sixteen.';if(limit!==16)$('status').textContent='Session complete. Keep that energy.';$('session-stats').textContent=`${limit} bars practiced · ${limit} word cues · Your flow, your progress.`;$('word').textContent='Nice flow.';$('prompt-category').textContent='Session complete';$('target').textContent='Go again with a fresh set of words';$('playhead').style.opacity=0;document.body.classList.remove('hit');setPlayUI();toast(`${limit} bars in the books. Run it back?`);return;}
  if(bar>lastBar){for(let i=lastBar;i<bar;i++){queue.shift();replenish();totalCues++;}lastBar=bar;renderPrompt(true);}
  $('status').textContent='In the pocket';$('bar').textContent=String(bar+1).padStart(2,'0');$('playhead').style.opacity=1;
  if(!reducedMotion&&!$('queue').classList.contains('short-queue')){const t=Math.max(0,Math.min(1,(fraction-3)/1)),smooth=t*t*(3-2*t),row=$('queue').firstElementChild;$('queue').style.transform=`translateY(-${smooth*(row?row.getBoundingClientRect().height:0)}px)`;}
  const percent=(fraction+.5/(grid/4))/4*100;$('playhead').style.left=`${Math.min(100,percent)}%`;$('timeline-fill').style.width=`${Math.min(100,percent)}%`;document.body.classList.toggle('hit',Math.abs(fraction-queue[0].beat)<.16);
  [...$('beat-labels').children].forEach((el,i)=>el.classList.toggle('current',Math.floor(fraction*(grid/4))===i));
  $('session-stats').textContent=`${bar} bars practiced · ${Math.floor(pos*60/engine.bpm)} seconds in the flow`;
  if(now-lastFrame>70&&engine.analyser){lastFrame=now;const data=new Uint8Array(engine.analyser.frequencyBinCount);engine.analyser.getByteFrequencyData(data);[...$('mini-wave').children].forEach((el,i)=>el.style.height=`${4+data[i*2]/255*36}px`);}
}
renderTracks();renderPrompt();requestAnimationFrame(animate);
$('music-credits').innerHTML=tracks.filter(t=>t.artist).map(t=>`<p>“${t.name}” by <a href="${t.source}" target="_blank" rel="noopener">${t.artist}${t.artist==='Shane Ivers'?' (silvermansound.com)':' (incompetech.com)'}</a> · CC BY 4.0</p>`).join('');
$('dictionary-total').textContent=`${wordBankSize.toLocaleString()} rhyme targets. Recent words and rhyme sounds are remembered on this browser across sessions. Fresh words are used first; when a category runs low, its oldest words return.`;
[...document.querySelectorAll('[data-category],[data-position],[data-level]')].forEach(el=>el.setAttribute('aria-pressed',el.classList.contains('selected')));

const studioMedia=matchMedia('(max-width:760px)'),studioSettings=$('studio-settings');studioSettings.open=!studioMedia.matches;studioMedia.addEventListener('change',()=>{studioSettings.open=!studioMedia.matches;});

const studioParty=new PartyClient('barcraft',room=>{if(!room)return;if(room.game!=='barcraft'){followGame(room.game,room.code);return;}let banner=document.getElementById('studio-party');if(!banner){banner=document.createElement('div');banner.id='studio-party';banner.className='studio-party';document.querySelector('.main-content').prepend(banner);}banner.replaceChildren();const label=document.createElement('span');label.textContent=`Party ${room.code} · ${room.players.length} players`;const link=document.createElement('a');link.href=gameUrl('party',room.code).href;link.textContent='Party lobby / switch games';banner.append(label,link);},()=>{});studioParty.restore(new URL(location.href).searchParams.get('room'));
