import {$,setupParty,perform,lobbyContent,roomControls,playerName,notice} from '../../shared/party-ui.js?v=20261008-refine-1';
import {el,button,scores} from '../../shared/game-tools.js?v=20261008-refine-1';
let latest,client,key='',saveTimer,clockOffset=0;
const labels={unique:'+1 unique',duplicate:'0 duplicate',letter:'0 wrong letter',blank:'0 blank',rejected:'0 rejected'};
function answers(){return [...$('game-stage').querySelectorAll('.answer-field input')].map(input=>input.value);}
async function save(lock=false){clearTimeout(saveTimer);if(!latest||latest.phase!=='writing'||latest.ready.includes(latest.you))return;const values=answers();if(!values.length)return;const status=$('save-status');if(status)status.textContent=lock?'Locking sheet…':'Saving…';try{await client.act(lock?'submit':'answers',{answers:values});if($('save-status'))$('save-status').textContent=lock?'Sheet locked.':'Saved privately.';}catch(error){notice(error.message);if($('save-status'))$('save-status').textContent='Not saved yet. Check your connection and try again.';}}
function clock(){const display=$('clock');if(!display||!latest?.deadline)return;const left=Math.max(0,Math.ceil(latest.deadline-(Date.now()/1000+clockOffset)));display.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;display.classList.toggle('urgent',left<=20);for(const input of $('game-stage').querySelectorAll('.answer-field input'))input.disabled=left===0||latest.ready.includes(latest.you);if($('lock-sheet'))$('lock-sheet').disabled=left===0||latest.ready.includes(latest.you);if(left===0&&$('save-status'))$('save-status').textContent='Time’s up. Revealing the saved sheets…';}
function render(room,c){if(!room){key='';latest=null;clearTimeout(saveTimer);return;}latest=room;client=c;clockOffset=room.serverTime-Date.now()/1000;roomControls(room,c);const ready=$('ready-note');if(ready)ready.textContent=`${room.ready.length} / ${room.participants.length} sheets locked`;const nextKey=[room.code,room.phase,room.round,room.host,room.ready.includes(room.you),JSON.stringify(room.result)].join(':');if(key===nextKey){if(room.phase==='lobby'&&$('start-game'))$('start-game').disabled=room.players.filter(p=>p.online).length<2;clock();return;}const focusedIndex=[...$('game-stage').querySelectorAll('.answer-field input')].indexOf(document.activeElement);const sameWriting=room.phase==='writing'&&key.includes(`:writing:${room.round}:`),draft=sameWriting?answers():null;key=nextKey;clearTimeout(saveTimer);const stage=$('game-stage');stage.replaceChildren();if(room.phase==='lobby'){lobbyContent(room,'scattergories');$('start-game')?.addEventListener('click',()=>perform(c,'start'));return;}
const host=room.you===room.host,participant=room.participants.includes(room.you);
if(room.phase==='finished'){stage.append(el('span','Session complete','eyebrow'),el('h2','Fast minds. Original answers.'),scores(room));if(host)stage.append(button('Play again',()=>perform(c,'again')));return;}
const heading=el('div','','round-heading'),letter=el('div',room.letter,'letter-badge'),copy=el('div');copy.append(el('h2',room.phase==='writing'?'Think outside the obvious.':'Compare your answers.'),el('span','Every answer starts with this letter.','eyebrow'));heading.append(letter,copy);if(room.phase==='writing'){const time=el('div','','clock');time.id='clock';time.setAttribute('aria-label','Time remaining');heading.append(time);}stage.append(heading);
if(room.phase==='writing'){if(!participant){stage.append(el('p','You’ll join the next round. The answer sheets are private for now.','stage-copy'));clock();return;}const sheet=el('form','','answer-sheet'),grid=el('div','','answer-grid');room.categories.forEach((category,index)=>{const label=el('label','','answer-field');label.append(el('span',`${index+1}. ${category}`));const input=el('input');input.type='text';input.maxLength=60;input.autocomplete='off';input.enterKeyHint=index===room.categories.length-1?'done':'next';input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();const next=grid.querySelectorAll('input')[index+1];if(next)next.focus();else input.blur();}});input.spellcheck=false;input.value=draft?.[index]??room.yourAnswers[index]??'';input.setAttribute('aria-label',category);input.placeholder=`${room.letter}…`;input.disabled=room.ready.includes(room.you);input.addEventListener('input',()=>{if($('save-status'))$('save-status').textContent='Unsaved changes…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(),400);});label.append(input);grid.append(label);});const status=el('div',room.ready.includes(room.you)?'Sheet locked. Wait for everyone else.':'Answers save privately as you type.','save-status');status.id='save-status';const lock=button('Lock answer sheet',()=>{});lock.id='lock-sheet';lock.type='submit';sheet.append(grid,status,lock);sheet.addEventListener('submit',event=>{event.preventDefault();save(true);});const note=el('p',`${room.ready.length} / ${room.participants.length} sheets locked`,'ready-note');note.id='ready-note';stage.append(sheet,note);clock();if(sameWriting&&focusedIndex>=0){const input=grid.querySelectorAll('input')[focusedIndex];input?.focus();}if(sameWriting&&!room.ready.includes(room.you)&&draft?.some(Boolean))saveTimer=setTimeout(()=>save(),400);return;}
if(room.phase==='reveal'){if(room.result.skipped)stage.append(el('p',room.result.reason,'stage-copy'));else{stage.append(el('p','Unique answers earn one point. Discuss anything questionable; the host can reject or restore it before the next round.','stage-copy'));const results=el('div','','results');room.categories.forEach((category,index)=>{const card=el('section','','result-category');card.append(el('h3',`${index+1}. ${category}`));for(const id of room.participants){const detail=room.result.details[id][index],row=el('div','','answer-result');row.append(el('span',playerName(room,id)),el('strong',room.answers[id]?.[index]||'—'));const meta=el('div','','result-detail');meta.append(el('span',labels[detail.status]));if(host&&room.answers[id]?.[index]){const accepted=detail.status!=='rejected';meta.append(button(accepted?'Reject':'Accept',()=>perform(c,'review',{player:id,index,accepted:!accepted}),'review-button'));}row.append(meta);card.append(row);}results.append(card);});stage.append(results);}stage.append(scores(room));if(host)stage.append(button(room.round===room.maxRounds?'See final scores':'Next round',()=>perform(c,'next')));else stage.append(el('p','Waiting for the host to continue.','stage-copy'));}}
setupParty('scattergories',render);setInterval(clock,250);
