import {$,setupParty,perform,lobbyContent,roomControls,notice,playerName} from './party-ui.js?v=20261009-party-1';
import {el,button,scores} from './game-tools.js?v=20261009-party-1';
export const deductionInstructions={
 rulebreakers:['Study the green passing words and peach failing words. The hidden rule is about spelling, not a word’s meaning.','Test dictionary words of 3–6 letters. Build a rule from the condition menus; an incorrect rule gives you a counterexample.','Solve before five minutes expire. Score 12 minus tests after your first three and 2 per incorrect rule. Six incorrect rules lock your round.'],
 'alien-dictionary':['Study the example translations. Each alien word has one meaning; word order can differ from English.','Answer eight translations, alternating alien → English and English → alien. Tap an option to lock it: one attempt per question.','Each correct translation earns 2 points. You have six minutes. Switch between Study examples and Translations whenever you need.'],
 'question-quest':['One visitor is responsible. Read the profiles, then ask yes/no questions to eliminate suspects.','One value costs 1 credit; a group of up to four values costs 2. Answers and remaining suspects stay private on your device.','Naming a suspect costs 2 credits, including wrong guesses. Solve within five minutes; score 20 minus credits spent. Save two credits for your final choice.']
};
const titles={rulebreakers:'Find the hidden rule.','alien-dictionary':'Learn a new language.','question-quest':'Ask the right question.'};
const copy={rulebreakers:'Test. Compare. Find the pattern.','alien-dictionary':'The examples are your dictionary.','question-quest':'Every good question narrows the field.'};
function tokens(words,cls='alien-tokens'){const n=el('span','',cls);for(const word of words)n.append(el('span',word));return n;}
function how(game){const details=el('details','','deduction-how');details.append(el('summary','Quick instructions'));const list=el('ol');for(const text of deductionInstructions[game])list.append(el('li',text));details.append(list);return details;}
function sample(word,pass){return el('span',word,`word-example ${pass?'passes':'fails'}`);}
export function startDeductionGame(game){
 let latest,client,key='',busy=false,offset=0,alienQuestion=0,alienPane='study',showAll=false;
 function playable(){return !!latest&&latest.phase==='deducing'&&latest.participants.includes(latest.you)&&!latest.ready.includes(latest.you)&&Date.now()/1000+offset>=latest.startsAt&&Date.now()/1000+offset<latest.deadline;}
 function tick(){if(!latest||latest.phase!=='deducing')return;const node=$('deduction-clock'),now=Date.now()/1000+offset;if(node){const before=Math.max(0,Math.ceil(latest.startsAt-now)),left=Math.max(0,Math.ceil(latest.deadline-now));node.textContent=before?`Starts in ${before}`:`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;node.classList.toggle('urgent',!before&&left<30);const inline=$('alien-inline-clock');if(inline)inline.textContent=node.textContent;}for(const control of document.querySelectorAll('[data-play]'))control.disabled=busy||!playable()||control.dataset.unavailable==='true';}
 async function act(action,payload={}){if(busy||!playable())return null;busy=true;tick();notice('');try{return await client.act(action,payload);}catch(error){notice(error.message);return null;}finally{busy=false;tick();}}
 function playButton(text,action,cls='primary'){const n=button(text,action,cls);n.type='button';n.dataset.play='true';return n;}
 function heading(room){const head=el('div','','deduction-heading'),text=el('div');text.append(el('h2',titles[game]),el('p',copy[game]));head.append(text);if(room.phase==='deducing'){const timer=el('strong','','deduction-clock');timer.id='deduction-clock';timer.setAttribute('aria-label','Time remaining');head.append(timer);}return head;}
 function rulePanel(room,stage){
  const initial=el('div','','rule-examples');for(const [label,pass,words] of [['Passes',true,room.examples.yes],['Fails',false,room.examples.no]]){const group=el('section');group.append(el('h3',label));const list=el('div','','word-examples');for(const word of words)list.append(sample(word,pass));group.append(list);initial.append(group);}stage.append(initial);
  if(!room.state){stage.append(el('p','You’ll play next round. Starting examples are shared; tests stay private.','deduction-note'));return;}
  const state=room.state;stage.append(el('p',state.solved?'Rule cracked! Waiting for the room.':`${state.probes.length}/30 word tests · ${state.wrong}/6 incorrect rules`,'deduction-note'));
  const form=el('form','','rule-test-form'),label=el('label','Test a word'),input=el('input');input.id='test-word';input.type='text';input.maxLength=6;input.minLength=3;input.required=true;input.pattern='[A-Za-z]{3,6}';input.placeholder='e.g. apple';input.autocomplete='off';input.autocapitalize='none';input.spellcheck=false;input.enterKeyHint='go';input.dataset.play='true';input.dataset.unavailable=String(state.probes.length>=30);label.append(input);const submit=playButton('Test word',()=>{});submit.type='submit';submit.dataset.unavailable=String(state.probes.length>=30);form.append(label,submit);form.addEventListener('submit',async e=>{e.preventDefault();const result=await act('probe',{word:input.value});if(result&&$('test-word')){$('test-word').value='';$('test-word').focus();}});stage.append(form);
  if(state.probes.length){const tests=el('div','','word-examples private-tests');tests.setAttribute('aria-label','Your private word tests');for(const p of state.probes)tests.append(sample(p.word,p.pass));stage.append(tests);}
  const builder=el('form','','rule-builder');builder.append(el('h3','What is the rule?'),el('p',room.difficulty==='easy'?'Warm-up rules use one condition.':room.difficulty==='classic'?'Classic rules combine two conditions with AND or OR.':'Expert rules use exactly one condition (XOR), or A but not B.','deduction-note'));
  const opLabel=el('label','Combination'),op=el('select');op.id='rule-op';op.dataset.play='true';for(const [value,text] of [['single','One condition'],['and','Both A and B'],['or','A or B (or both)'],['xor','Exactly one of A or B'],['andnot','A, but not B']]){const option=el('option',text);option.value=value;op.append(option);}op.value=room.difficulty==='easy'?'single':room.difficulty==='expert'?'xor':'and';opLabel.append(op);builder.append(opLabel);
  for(const letter of ['a','b']){const label=el('label',`Condition ${letter.toUpperCase()}`),select=el('select');select.id=`rule-${letter}`;select.dataset.play='true';select.required=true;const placeholder=el('option','Choose a condition…');placeholder.value='';select.append(placeholder);const groups=new Map();for(const atom of room.atoms){const title=atom.text.startsWith('starts with')?'Starts with':atom.text.startsWith('ends with')?'Ends with':atom.text.startsWith('contains the adjacent')?'Adjacent letters':atom.text.startsWith('contains')?'Contains a letter':atom.text.includes('vowel')?'Vowels':'Length & letter patterns';if(!groups.has(title)){const group=el('optgroup');group.label=title;groups.set(title,group);select.append(group);}const option=el('option',atom.text);option.value=atom.id;groups.get(title).append(option);}label.append(select);if(letter==='b')label.id='condition-b';builder.append(label);}
  function changeOp(){const single=op.value==='single';$('condition-b').hidden=single;$('rule-b').required=!single;}op.addEventListener('change',changeOp);const submitRule=playButton('Test my rule',()=>{});submitRule.type='submit';builder.append(submitRule);builder.addEventListener('submit',e=>{e.preventDefault();act('rule',{a:$('rule-a').value,op:op.value,b:op.value==='single'?null:$('rule-b').value});});stage.append(builder);changeOp();
  if(state.guesses.length){const list=el('div','','hypothesis-history');list.append(el('h3','Your hypotheses'));for(const guess of [...state.guesses].reverse()){const row=el('div','','hypothesis');row.append(el('p',guess.text));if(guess.correct)row.append(el('strong','Correct — you cracked it.','success-message'));else{row.append(el('span','Counterexample: '),sample(guess.counter.word,guess.counter.pass),el('span',guess.counter.pass?' passes the real rule.':' fails the real rule.'));}list.append(row);}stage.append(list);}
 }
 function alienPanel(room,stage){
  const tabs=el('div','','alien-tabs');for(const [pane,text] of [['study','Study examples'],['quiz','Translations']]){const b=button(text,()=>{alienPane=pane;const content=$('alien-content');if(content)content.dataset.pane=pane;for(const n of tabs.querySelectorAll('button'))n.setAttribute('aria-pressed',String(n.dataset.pane===pane));},'secondary-action');b.type='button';b.dataset.pane=pane;b.setAttribute('aria-pressed',String(alienPane===pane));tabs.append(b);}const inlineClock=el('span','','alien-inline-clock');inlineClock.id='alien-inline-clock';inlineClock.setAttribute('aria-label','Time remaining');tabs.append(inlineClock);stage.append(tabs);
  const content=el('div','','alien-content');content.id='alien-content';content.dataset.pane=alienPane;const reference=el('section','','alien-reference');reference.append(el('h3','Examples from this planet'),el('p','The pictures identify the characters. Read the English caption for the full meaning.','deduction-note'));
  for(const example of room.examples){const row=el('div','','alien-example');row.append(el('span',example.icons.join(' '),'alien-picture'),tokens(example.alien),el('p',example.english,'example-english'));reference.append(row);}content.append(reference);
  const quiz=el('section','','alien-quiz');if(!room.state){quiz.append(el('p','You’ll translate next round. You can study the examples now.'));content.append(quiz);stage.append(content);return;}
  const answers=room.state.answers||{};const nav=el('div','','translation-nav');nav.setAttribute('aria-label','Choose a translation');for(let i=0;i<room.challenges.length;i++){const answer=answers[i];const b=button(`${i+1}${answer?(answer.correct?' ✓':' ×'):''}`,()=>{alienQuestion=i;alienPane='quiz';render(latest,client,true);},'translation-number');b.type='button';b.setAttribute('aria-label',`Translation ${i+1}${answer?', answered':''}`);b.setAttribute('aria-pressed',String(i===alienQuestion));nav.append(b);}quiz.append(nav);
  const q=room.challenges[alienQuestion],answer=answers[alienQuestion];quiz.append(el('p',`${Object.keys(answers).length}/8 locked · 2 points per correct translation`,'deduction-note'),el('h3',q.direction==='decode'?'What does this mean?':'How would an alien say this?'));if(Array.isArray(q.prompt))quiz.append(tokens(q.prompt,'alien-tokens challenge-tokens'));else quiz.append(el('p',q.prompt,'translation-prompt'));
  const options=el('div','','translation-options');q.options.forEach((option,index)=>{const b=playButton('',async()=>{const result=await act('translate',{question:alienQuestion,choice:index});if(result){const unanswered=room.challenges.findIndex((_,i)=>!latest.state?.answers?.[i]);if(unanswered>=0){alienQuestion=unanswered;render(latest,client,true);}}},'translation-option');if(Array.isArray(option))b.append(tokens(option));else b.textContent=option;b.dataset.unavailable=String(!!answer);if(answer){b.classList.toggle('correct-answer',index===answer.correctIndex);b.classList.toggle('wrong-answer',index===answer.choice&&!answer.correct);b.setAttribute('aria-label',`${Array.isArray(option)?option.join(' '):option}${index===answer.correctIndex?' — correct translation':''}`);}options.append(b);});quiz.append(options);if(answer)quiz.append(el('p',answer.correct?'Correct translation.':'The highlighted option is the correct translation.','answer-feedback'));else quiz.append(el('p','One attempt. Tapping an option locks your answer.','deduction-note'));content.append(quiz);stage.append(content);
 }
 function questPanel(room,stage){
  stage.append(el('h3',room.story.title,'quest-title'),el('p',room.story.text,'quest-story'));if(!room.state){stage.append(el('p','You’ll investigate next round. Profiles are visible; questions stay private.','deduction-note'));return;}
  const state=room.state,credits=room.budget-state.spent;const meter=el('div','','quest-meter');meter.append(el('strong',`${credits} credits left`),el('span',`${state.possible.length} suspects remain`));stage.append(meter);
  const form=el('form','','quest-question-form'),label=el('label','Ask about'),field=el('select');field.id='quest-field';field.dataset.play='true';for(const [id,data] of Object.entries(room.fields)){const option=el('option',data.label);option.value=id;field.append(option);}label.append(field);const values=el('fieldset','','quest-values');values.id='quest-values';const legend=el('legend','Choose one value, or a group of up to four');values.append(legend);const submit=playButton('Ask (1 credit)',()=>{});submit.type='submit';submit.id='ask-question';
  function choices(){values.replaceChildren(legend);for(const value of room.fields[field.value].values){const row=el('label'),input=el('input');input.type='checkbox';input.value=value;input.dataset.play='true';input.addEventListener('change',()=>{const selected=[...values.querySelectorAll('input:checked')];if(selected.length>4){input.checked=false;notice('Choose at most four values.');}const cost=values.querySelectorAll('input:checked').length>1?2:1;submit.textContent=`Ask (${cost} ${cost===1?'credit':'credits'})`;submit.dataset.unavailable=String(credits<cost+2||!values.querySelector('input:checked'));tick();});row.append(input,el('span',value));values.append(row);}submit.dataset.unavailable='true';tick();}field.addEventListener('change',choices);form.append(label,values,submit);form.addEventListener('submit',e=>{e.preventDefault();const selected=[...values.querySelectorAll('input:checked')].map(n=>n.value);act('question',{field:field.value,values:selected});});stage.append(form);choices();
  if(state.history.length){const history=el('details','','quest-history');history.open=true;history.append(el('summary','Your questions'));for(const h of [...state.history].reverse()){const line=el('div','','question-history-row');line.append(el('span',`${room.fields[h.field].label}: ${h.values.join(' or ')}?`),el('strong',h.yes?'Yes':'No',h.yes?'success-message':'failure-message'));history.append(line);}stage.append(history);}
  if(state.guesses.length){for(const guess of state.guesses)stage.append(el('p',`${room.roster.find(s=>s.id===guess.suspect)?.name}: ${guess.correct?'case solved!':'ruled out.'}`,'deduction-note'));}
  const controls=el('div','','suspect-heading');controls.append(el('h3','Visitor profiles'));const toggle=button(showAll?'Show remaining':'Show all visitors',()=>{showAll=!showAll;render(latest,client,true);},'secondary-action');toggle.type='button';controls.append(toggle);stage.append(controls);const roster=el('div','','suspect-grid');for(const suspect of room.roster){const remains=state.possible.includes(suspect.id);if(!remains&&!showAll)continue;const card=el('article','',`suspect-card${remains?'':' excluded'}`);card.append(el('h4',suspect.name));const traits=el('dl');for(const [f,value] of Object.entries(suspect.traits)){const pair=el('div');pair.append(el('dt',room.fields[f].label),el('dd',value));traits.append(pair);}card.append(traits);const choose=playButton(`Name ${suspect.name} (2 credits)`,()=>act('accuse',{suspect:suspect.id}),'secondary-action');choose.dataset.unavailable=String(!remains||credits<2);card.append(choose);roster.append(card);}stage.append(roster);
 }
 function reveal(room,stage){
  stage.append(el('h2',room.result.skipped?'Round skipped.':'The mystery, revealed.'));if(room.result.skipped)stage.append(el('p','No points awarded for this round.','deduction-note'));
  if(game==='rulebreakers')stage.append(el('p',room.solution.text,'rule-solution'));
  else if(game==='alien-dictionary'){stage.append(el('p',`Sentence order: ${room.solution.sentenceOrder.split('').map(v=>({S:'subject',V:'verb',O:'object'})[v]).join(' → ')}. Phrase order: ${room.solution.phraseOrder.join(' → ')}.`,'deduction-note'));const list=el('div','','lexicon-reveal');for(const terms of Object.values(room.solution.lexicon))for(const term of terms){const row=el('div');row.append(el('strong',term.alien),el('span',`${term.icon} ${term.word}`));list.append(row);}stage.append(list);}
  else {const suspect=room.roster.find(s=>s.id===room.solution);stage.append(el('p',`${suspect.name} was responsible.`,'rule-solution'));const traits=el('p',Object.entries(suspect.traits).map(([f,v])=>`${room.fields[f].label}: ${v}`).join(' · '),'deduction-note');stage.append(traits);}
  if(!room.result.skipped){const results=el('div','','deduction-results');for(const row of room.result.standings){const line=el('div','','deduction-result');line.append(el('strong',playerName(room,row.player)),el('span',game==='alien-dictionary'?`${row.correct}/8 correct`:row.solved?'Solved':'Unsolved'),el('strong',`+${row.points}`));results.append(line);}stage.append(results);}stage.append(scores(room));if(room.you===room.host)stage.append(button(room.round===room.maxRounds?'Final scores':'Next round',()=>perform(client,'next')));else stage.append(el('p','Waiting for the host to continue.','deduction-note'));
 }
 function render(room,c,force=false){
  if(!room){key='';latest=null;alienQuestion=0;alienPane='study';showAll=false;return;}latest=room;client=c;offset=room.serverTime-Date.now()/1000;roomControls(room,c);
  const nextKey=[room.code,room.you,room.phase,room.round,room.host,room.participants.includes(room.you),JSON.stringify(room.state),JSON.stringify(room.result)].join(':');if(key===nextKey&&!force){tick();if(room.phase==='lobby'&&$('start-game'))$('start-game').disabled=room.players.filter(p=>p.online).length<2;return;}
  const sameRound=key.startsWith(`${room.code}:${room.you}:${room.phase}:${room.round}:`);const stage=$('game-stage'),draft=sameRound?Object.fromEntries([...stage.querySelectorAll('input[id],select[id]')].map(n=>[n.id,n.value])):{};const focused=document.activeElement?.id;if(!sameRound&&room.phase==='deducing'){alienQuestion=0;alienPane='study';showAll=false;}key=nextKey;stage.replaceChildren();
  if(room.phase==='lobby'){lobbyContent(room,game);stage.append(how(game));$('start-game')?.addEventListener('click',()=>perform(c,'start',{difficulty:$('puzzle-difficulty').value,rounds:Number($('puzzle-rounds').value)}));return;}
  if(room.phase==='finished'){stage.append(el('h2','Good questions. Great discoveries.'),scores(room));if(room.you===room.host)stage.append(button('Play again',()=>perform(c,'again',{difficulty:room.difficulty,rounds:room.maxRounds})));return;}
  if(room.phase==='reveal'){reveal(room,stage);return;}
  stage.append(heading(room),how(game));const status=el('p',`${room.ready.length}/${room.participants.length} players finished. Your answers stay private.`,'deduction-note');stage.append(status);
  if(game==='rulebreakers')rulePanel(room,stage);else if(game==='alien-dictionary')alienPanel(room,stage);else questPanel(room,stage);
  if(room.state){if(room.ready.includes(room.you))stage.append(el('p',room.state.solved?'Solved! Waiting for the room.':'Your round is locked. Waiting for the room.','locked-round'));else stage.append(playButton('Finish my round',()=>{if(confirm('Finish with your current answers? You cannot make more attempts this round.'))act('give_up');},'secondary-action finish-deduction'));}
  if(room.you===room.host)stage.append(button('End round & reveal',()=>{if(confirm('End this round for everyone and show the solution?'))perform(c,'end_race');},'text-button'));
  for(const [id,value] of Object.entries(draft)){const node=$(id);if(node)node.value=value;}if($('rule-op'))$('rule-op').dispatchEvent(new Event('change'));if($('quest-field'))$('quest-field').dispatchEvent(new Event('change'));if(focused&&$(focused)&&game!=='alien-dictionary')$(focused).focus();tick();
 }
 setupParty(game,render);setInterval(tick,250);
}
