const NS='http://www.w3.org/2000/svg';
export function drawingSvg(strokes){const svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox','0 0 512 384');svg.setAttribute('role','img');svg.setAttribute('aria-label','Player drawing');svg.classList.add('player-drawing');const bg=document.createElementNS(NS,'rect');bg.setAttribute('width','512');bg.setAttribute('height','384');bg.setAttribute('fill','#f5efe5');svg.append(bg);for(const stroke of strokes||[]){const path=document.createElementNS(NS,'polyline');path.setAttribute('points',stroke.points.map(p=>p.join(',')).join(' '));path.setAttribute('fill','none');path.setAttribute('stroke',stroke.color);path.setAttribute('stroke-width',String(stroke.width));path.setAttribute('stroke-linecap','round');path.setAttribute('stroke-linejoin','round');svg.append(path);}return svg;}
export function drawingPad(onSubmit,draftKey){
 const panel=document.createElement('div');panel.className='drawing-pad';const canvas=document.createElement('canvas');canvas.width=512;canvas.height=384;canvas.setAttribute('aria-label','Drawing canvas. Draw using your finger, mouse, or stylus.');canvas.className='drawing-canvas';panel.append(canvas);
 let strokes=[],current=null,color='#292039',width=4;try{const saved=JSON.parse(sessionStorage.getItem(draftKey)||'[]');if(Array.isArray(saved))strokes=saved;}catch{}
 const ctx=canvas.getContext('2d');const paint=()=>{if(!ctx)return;ctx.fillStyle='#f5efe5';ctx.fillRect(0,0,512,384);for(const s of strokes){ctx.strokeStyle=s.color;ctx.lineWidth=s.width;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();s.points.forEach((p,i)=>i?ctx.lineTo(...p):ctx.moveTo(...p));if(s.points.length===1)ctx.lineTo(s.points[0][0]+.1,s.points[0][1]+.1);ctx.stroke();}};
 const save=()=>{try{sessionStorage.setItem(draftKey,JSON.stringify(strokes));}catch{}};
 const controls=document.createElement('div');controls.className='brush-controls';const colors=[['#292039','Ink'],['#c45c69','Rose'],['#467f71','Green'],['#467fa3','Blue'],['#ffffff','White']];
 for(const [value,name] of colors){const b=document.createElement('button');b.type='button';b.className='brush-color';b.style.background=value;b.setAttribute('aria-label',name+' brush');b.setAttribute('aria-pressed',String(color===value));b.addEventListener('click',()=>{color=value;for(const other of controls.querySelectorAll('.brush-color'))other.setAttribute('aria-pressed',String(other===b));});controls.append(b);}
 const size=document.createElement('select');size.setAttribute('aria-label','Brush thickness');for(const [value,label] of [[4,'Fine'],[8,'Medium'],[14,'Bold']]){const o=document.createElement('option');o.value=value;o.textContent=label;size.append(o);}size.addEventListener('change',()=>width=Number(size.value));controls.append(size);
 const addButton=(text,fn)=>{const b=document.createElement('button');b.type='button';b.className='secondary-action';b.textContent=text;b.addEventListener('click',fn);controls.append(b);return b;};addButton('Undo',()=>{strokes.pop();current=null;paint();save();});addButton('Clear',()=>{strokes=[];current=null;paint();save();});panel.append(controls);
 const note=document.createElement('p');note.className='jb-note';note.textContent='Draw with a finger, mouse, or stylus. Keep it simple. No text required.';panel.append(note);
 const point=e=>{const r=canvas.getBoundingClientRect();return [Math.max(0,Math.min(512,Math.round((e.clientX-r.left)*512/r.width))),Math.max(0,Math.min(384,Math.round((e.clientY-r.top)*384/r.height)))];};
 canvas.addEventListener('pointerdown',e=>{if(e.button!==undefined&&e.button!==0)return;e.preventDefault();if(strokes.reduce((n,s)=>n+s.points.length,0)>=898||strokes.length>=100){note.textContent='Canvas detail limit reached. Undo a stroke to make room.';return;}current={color,width,points:[point(e)]};strokes.push(current);canvas.setPointerCapture?.(e.pointerId);paint();});
 canvas.addEventListener('pointermove',e=>{if(!current)return;e.preventDefault();const p=point(e),last=current.points.at(-1);if(Math.hypot(p[0]-last[0],p[1]-last[1])<4)return;if(strokes.reduce((n,s)=>n+s.points.length,0)>=899)return;current.points.push(p);paint();});
 const finish=()=>{if(current&&current.points.length===1)current.points.push([Math.min(512,current.points[0][0]+1),current.points[0][1]]);current=null;save();paint();};canvas.addEventListener('pointerup',finish);canvas.addEventListener('pointercancel',finish);
 const submit=document.createElement('button');submit.type='button';submit.className='primary';submit.textContent='Lock drawing';submit.dataset.play='true';submit.addEventListener('click',()=>{finish();if(!strokes.length){note.textContent='Draw something before locking it.';return;}onSubmit(strokes);});panel.append(submit);paint();return panel;
}
