import {$,setupParty,perform,lobbyContent,roomControls,playerName,notice} from './party-ui.js?v=20261008-qr-mobile-2';
import {el,button} from './game-tools.js?v=20261008-qr-mobile-2';
let latest,client,key='',offset=0,saveTimer;
function board(room){const node=el('div','','hive-board');const levels=room.phase==='reveal'&&!room.result.skipped?room.result.levels:room.levels;for(let level=0;level<=room.hiveSize;level++){const row=el('div','','hive-level');row.append(el('span',level===room.hiveSize?'Exit':level===0?'Top':`Level ${level+1}`,'level-name'));const pawns=el('div','','hive-pawns');for(const player of room.players)if(levels[player.id]===level){const pawn=el('span',player.name,'hive-pawn');pawn.classList.toggle('you',player.id===room.you);pawn.title=room.result?.scores?.[player.id]!==undefined?`${room.result.scores[player.id]} points this round`:player.name;pawns.append(pawn);}row.append(pawns);node.append(row);}return node;}
function values(){return [...$('game-stage').querySelectorAll('.hive-answer')].map(input=>input.value);}
async function save(lock=false){clearTimeout(saveTimer);if(latest.phase!=='answering'||latest.ready.includes(latest.you))return;const input=values();if(!input.length)return;try{await client.act(lock?'submit':'answer',{answers:input});if($('save-note'))$('save-note').textContent=lock?'Answers locked.':'Saved privately.';}catch(error){notice(error.message);}}
function clock(){const node=$('hive-clock');if(!node||!latest.deadline)return;const remaining=Math.max(0,Math.ceil(latest.deadline-(Date.now()/1000+offset)));node.textContent=`${Math.floor(remaining/60)}:${String(remaining%60).padStart(2,'0')}`;for(const input of $('game-stage').querySelectorAll('.hive-answer'))input.disabled=remaining===0||latest.ready.includes(latest.you);const submit=$('hive-submit');if(submit)submit.disabled=remaining===0||latest.ready.includes(latest.you);}
function render(room,c){if(!room){key='';latest=null;clearTimeout(saveTimer);return;}latest=room;client=c;offset=room.serverTime-Date.now()/1000;roomControls(room,c);if($('hive-ready'))$('hive-ready').textContent=`${room.ready.length} / ${room.participants.length} lists locked`;const nextKey=[room.code,room.phase,room.round,room.host,room.active,room.ready.includes(room.you),JSON.stringify(room.result)].join(':');if(key===nextKey){clock();if(room.phase==='lobby'&&$('start-game'))$('start-game').disabled=room.players.filter(p=>p.online).length<3;return;}const sameAnswer=key.startsWith(`${room.code}:answering:${room.round}:`)&&room.phase==='answering',draft=sameAnswer?values():null;key=nextKey;clearTimeout(saveTimer);const stage=$('game-stage');stage.replaceChildren();const host=room.you===room.host,active=room.you===room.active,participant=room.participants.includes(room.you);
if(room.phase==='lobby'){lobbyContent(room,'hivemind');$('start-game')?.addEventListener('click',()=>perform(c,'start',{levels:Number($('hive-size').value)}));return;}
const positions=el('details','','hive-board-panel');positions.open=!matchMedia('(max-width:760px)').matches;positions.append(el('summary','Hive positions'),board(room));stage.append(positions);
if(room.phase==='finished'){stage.append(el('h2',room.winners.length===room.participants.length?'Everyone stayed together.':'The hive has its survivors.'),el('p',room.winners.map(id=>playerName(room,id)).join(', '),'stage-copy'));if(host)stage.append(button('Build a new hive',()=>perform(c,'again',{levels:room.hiveSize})));return;}
const die=el('div','','hive-turn');die.append(el('span',`${playerName(room,room.active)} is the active player`),el('strong',`Die: ${room.die.dots}${room.die.star?' ★':''}`));stage.append(die);
if(room.phase==='question'){stage.append(el('h2',active?'Choose the question.':'A question is coming.'),el('p',active?'Which answers will the room have in common?':'The active player chooses one of three questions.','stage-copy'));if(active){const choices=el('div','','hive-questions');room.questionOptions.forEach((p,index)=>choices.append(button(p.text,()=>perform(c,'question',{index}),'question-card')));stage.append(choices);const form=el('form','','custom-question'),label=el('label','Or ask your own question'),input=el('input');input.type='text';input.maxLength=120;input.required=true;input.placeholder='Name three things…';input.setAttribute('aria-label','Custom question');const count=el('select');count.setAttribute('aria-label','Number of answers');for(let n=2;n<=5;n++){const option=el('option',`${n} answers`);option.value=n;count.append(option);}count.value=3;form.append(label,input,count,button('Ask this question',()=>{}));form.addEventListener('submit',event=>{event.preventDefault();perform(c,'question',{custom:input.value,count:Number(count.value)});});stage.append(form);}return;}
if(room.prompt)stage.append(el('h2',room.prompt.text,'hive-prompt'));
if(room.phase==='answering'){const time=el('div','','hive-clock');time.id='hive-clock';time.setAttribute('aria-label','Time remaining');stage.append(time);if(participant){const form=el('form','','hive-answer-form');for(let n=0;n<room.prompt.count;n++){const label=el('label',`Answer ${n+1}`),input=el('input','','hive-answer');input.type='text';input.maxLength=60;input.value=draft?.[n]??room.yourAnswers[n]??'';input.autocomplete='off';input.enterKeyHint=n===room.prompt.count-1?'done':'next';input.addEventListener('keydown',event=>{if(event.key==='Enter'){event.preventDefault();const next=form.querySelectorAll('input')[n+1];if(next)next.focus();else input.blur();}});input.setAttribute('aria-label',`Answer ${n+1}`);input.addEventListener('input',()=>{if($('save-note'))$('save-note').textContent='Saving…';clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(),400);});label.append(input);form.append(label);}const note=el('p',room.ready.includes(room.you)?'Answers locked.':'Answers save privately. Stay quiet until reveal.','save-note');note.id='save-note';const submit=button('Lock my answers',()=>{});submit.id='hive-submit';form.append(note,submit);form.addEventListener('submit',event=>{event.preventDefault();save(true);});stage.append(form);}else stage.append(el('p','You’ll enter the hive next round.','stage-copy'));const ready=el('p',`${room.ready.length} / ${room.participants.length} lists locked`,'stage-copy');ready.id='hive-ready';stage.append(ready);clock();return;}
if(room.phase==='reveal'){if(room.result.skipped)stage.append(el('p',room.result.reason,'stage-copy'));else{const points=el('div','','hive-results');for(const id of room.participants){const move=room.result.movement[id],row=el('div','','hive-score');row.append(el('span',playerName(room,id)),el('strong',`${room.result.scores[id]} points`),el('span',move>0?'Down one level':move<0?'Up one level':'Stay here'));points.append(row);}stage.append(points);const groups=el('div','','hive-groups');for(const group of room.result.groups){const card=el('section','','hive-match');card.append(el('h3',[...new Set(group.answers.map(v=>v.text))].join(' / ')),el('p',`${group.players.length} ${group.players.length===1?'player':'players'} · ${group.players.map(id=>playerName(room,id)).join(', ')}`));if(host){const label=el('label','Match this meaning with'),select=el('select');select.setAttribute('aria-label','Matching answer');for(const target of room.result.groups){const text=target.answers[0].text;const option=el('option',text);option.value=text;select.append(option);}select.value=group.answers[0].text;label.append(select);card.append(label,button('Apply match',()=>perform(c,'merge',{from:group.answers[0].text,to:select.value}),'text-button'));}groups.append(card);}stage.append(groups,el('p','Positions above preview this round’s movement. Apply them when the group agrees on the matches.','stage-copy'));}if(host)stage.append(button('Apply movement & continue',()=>perform(c,'next')));else stage.append(el('p','Waiting for the host to apply movement.','stage-copy'));}}
setupParty('hivemind',render);setInterval(clock,250);
