import {$,setupParty,perform,lobbyContent,roomControls,playerName,notice} from './party-ui.js?v=20261009-party-1';
import {el,button,scores} from './game-tools.js?v=20261009-party-1';
import {drawingPad,drawingSvg} from './drawing-pad.js?v=20261009-party-1';
export const jackboxInstructions={
 'quiz-after-dark':['Choose the right answer before the 25-second timer ends. Correct answers earn up to 200 points for speed; wrong answers cost 50.','Once per game, screw an unanswered opponent to give them only eight seconds. Your answer stays private until everyone finishes.','The host advances after each reveal. Highest total wins.'],
 punchline:['Write two funny responses to your private prompts. Each prompt has two writers.','Vote for your favorite response in each matchup where you are eligible. You cannot vote for yourself. With two players, a house response joins the matchups.','Earn 100 per vote plus a 50-point win bonus (25 for a tie). Highest total wins.'],
 'fact-or-fiction':['Invent a believable missing answer to the fact. If you accidentally type the truth, the game asks you to try again.','Find the real answer among everyone’s bluffs and the house decoys. You cannot vote for your own lie.','Earn 100 for finding the truth and 50 whenever someone believes your bluff.'],
 'doodle-bluff':['Draw your private, strange prompt with a finger, mouse, or stylus. Keep the prompt secret.','Write convincing fake captions for the other drawings. Then find each drawing’s original prompt among the captions.','Earn 100 for a correct guess, 50 for fooling someone, and 25 when someone decodes your drawing.'],
 'last-laugh-trivia':['Answer the trivia. A wrong answer sends living players into a quick math, memory, or number trap. Failing a trap costs one of your two lives.','Ghosts keep answering; two correct answers bring you back with one life. Every correct trivia answer moves you two escape steps; a successful trap adds one.','At the end, the furthest escape distance wins; trivia score breaks ties.'],
 'thread-battle':['Draw a strange shirt graphic, then write two short slogans. They do not have to match your own drawing.','Mix any submitted artwork with any slogan to make the funniest shirt. Vote for a design other than your own. Two-player games include a house design.','Earn 100 per vote for your design; its artist and slogan writer also get 25 each. Highest total wins.']
};
export function startJackboxGame(game){
 let latest,client,key='',busy=false,active=0,offset=0;const captionDrafts=new Map();
 const locked=(text='Locked. Waiting for the others.')=>el('p',text,'jb-locked');
 const playButton=(text,fn,cls='primary')=>{const b=button(text,fn,cls);b.dataset.play='true';return b;};
 async function act(action,payload={}){if(busy)return;busy=true;tick();notice('');try{await client.act(action,payload);}catch(e){notice(e.message);}finally{busy=false;tick();}}
 function tick(){if(!latest)return;const now=Date.now()/1000+offset;const time=$('jb-clock');if(time){const deadline=latest.personalDeadline?Math.min(latest.deadline,latest.personalDeadline):latest.deadline;const left=Math.max(0,Math.ceil(deadline-now));time.textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;time.classList.toggle('urgent',left<10);}
 for(const b of document.querySelectorAll('[data-play]'))b.disabled=busy||now>=latest.deadline||Number(b.dataset.notBefore||0)>now||b.dataset.locked==='true';
 const ready=$('jb-ready');if(ready)ready.textContent=`${latest.jbReady?.length||0} / ${latest.participants.length} players locked in`;
 const memory=$('memory-code');if(memory&&latest.challenge?.hideAt<=now){memory.hidden=true;const heading=$('danger-prompt');if(heading)heading.textContent='Which code did you see?';}
 }
 function help(){const d=el('details','','jb-how');d.append(el('summary','How this game works'));const list=el('ol');for(const text of jackboxInstructions[game])list.append(el('li',text));d.append(list);return d;}
 function nav(entries,render){const bar=el('div','','jb-nav');entries.forEach((e,i)=>{const b=button(String(i+1),()=>{active=i;render();},'secondary-action');b.setAttribute('aria-pressed',String(active===i));b.setAttribute('aria-label',`View item ${i+1}`);bar.append(b);});return bar;}
 function render(room,c,force=false){if(!room){key='';latest=null;return;}latest=room;client=c;offset=room.serverTime-Date.now()/1000;roomControls(room,c);
 const signature=JSON.stringify([room.gameEpoch,room.code,room.you,room.phase,room.round,room.host,room.yourWriting,room.yourAnswer,room.yourDanger,room.yourDrawing,room.yourSlogans,room.yourDesign,room.entries,room.pictures,room.challenge,room.result,room.phase==='lobby'?room.players:null]);if(key===signature&&!force){tick();return;}
 const changed=!key||latest.phase!==$('game-stage').dataset.jbPhase||latest.round!==Number($('game-stage').dataset.jbRound);if(changed)active=0;key=signature;const stage=$('game-stage');stage.dataset.jbPhase=room.phase;stage.dataset.jbRound=room.round;stage.replaceChildren();
 if(room.phase==='lobby'){
  lobbyContent(room,game);stage.append(help());if(room.you===room.host){const label=el('label','Rounds','category-select'),select=el('select');select.id='jb-rounds';for(const n of [3,1,5,10]){const o=el('option',`${n} ${n===1?'round':'rounds'}`);o.value=n;select.append(o);}label.append(select);stage.insertBefore(label,$('start-game'));$('start-game').addEventListener('click',()=>perform(c,'start',{rounds:Number(select.value)}));}return;
 }
 if(room.phase==='finished'){stage.append(el('h2','One more round?'));if(game==='last-laugh-trivia'){const list=el('div','','escape-board');for(const p of [...room.players].sort((a,b)=>(room.escape?.[b.id]||0)-(room.escape?.[a.id]||0)||b.score-a.score))list.append(el('p',`${p.name}: ${room.escape?.[p.id]||0} escape steps`));const winner=[...room.players].filter(p=>!p.left).sort((a,b)=>(room.escape?.[b.id]||0)-(room.escape?.[a.id]||0)||b.score-a.score)[0];if(winner)stage.append(el('h3',`${winner.name} escaped furthest!`));stage.append(list);}else stage.append(scores(room));if(room.you===room.host)stage.append(button('Play again',()=>perform(c,'again',{rounds:room.maxRounds})));return;}
 const header=el('div','','jb-heading'),heading=el('h2',({'jb-writing':'Make it convincing.','jb-drawing':'Make a beautiful mess.','jb-bluffing':'Name that masterpiece.','jb-slogans':'Two slogans. No bad ideas.','jb-designing':'Build your dream shirt.','jb-voting':'Choose your favorite.','jb-trivia':'Trust your questionable instincts.','jb-danger':'Survive the trap.',reveal:'The room has spoken.'})[room.phase]||'Time to play.');header.append(heading);if(room.phase!=='reveal'){const clock=el('strong','','jb-clock');clock.id='jb-clock';header.append(clock);}stage.append(header);
 if(room.phase==='reveal'){if(room.result.skipped){stage.append(el('p','Round skipped. No points awarded.','jb-note'));}else{
  if(room.result.explanation)stage.append(el('p',room.result.explanation,'jb-answer'));
  for(const entry of room.result.entries||[]){const section=el('section','','jb-reveal-entry');section.append(el('h3',entry.prompt));if(entry.drawing)section.append(drawingSvg(entry.drawing));for(const o of entry.options){const text=el('div','','jb-reveal-choice');if(o.drawing)text.append(drawingSvg(o.drawing));text.append(el('strong',o.text),el('span',`${room.result.votes?.[entry.id]?.[o.id]||0} votes${o.truth?' · Original answer':''}${o.author?' · '+playerName(room,o.author):''}${o.authors?.length?' · '+o.authors.map(id=>playerName(room,id)).join(', '):''}`));if(o.truth)text.classList.add('correct');section.append(text);}stage.append(section);}
  const result=el('div','','jb-round-scores');for(const p of room.players)if(room.result.scores?.[p.id]!==undefined)result.append(el('p',`${p.name}: ${room.result.scores[p.id]>=0?'+':''}${room.result.scores[p.id]} this round`));stage.append(result);
 }stage.append(scores(room));if(room.you===room.host)stage.append(button(room.round>=room.maxRounds?'Final scores':'Next round',()=>perform(c,'next')));else stage.append(locked('Waiting for the host to continue.'));if(game==='last-laugh-trivia')lifeBoard(stage,room);return;}
 stage.append(help());if(!room.participants.includes(room.you)){stage.append(locked('You joined during a round. You’ll play in the next one.'));return;}
 if(room.phase==='jb-trivia'){
  stage.append(el('h3',room.question.text,'jb-question'));if(room.personalDeadline)stage.append(el('p','You’ve been screwed! Choose before your eight-second timer ends.','jb-alert'));
  const options=el('div','','jb-options');room.question.options.forEach((text,i)=>{const b=playButton(text,()=>act('answer',{choice:i}),'jb-option');if(room.yourAnswer!==null){b.dataset.locked='true';if(room.yourAnswer===i)b.classList.add('selected');}options.append(b);});stage.append(options);if(room.yourAnswer!==null)stage.append(locked('Answer locked. The truth appears at the reveal.'));
  else if(game==='quiz-after-dark'&&!room.screwUsed){const targets=room.participants.filter(id=>id!==room.you&&!room.jbReady.includes(id));if(targets.length){const controls=el('div','','screw-controls'),select=el('select');select.setAttribute('aria-label','Opponent to screw');for(const id of targets){const o=el('option',playerName(room,id));o.value=id;select.append(o);}controls.append(select,playButton('Use screw · 1 per game',()=>act('screw',{target:select.value}),'secondary-action'));stage.append(controls);}}
  if(game==='last-laugh-trivia')lifeBoard(stage,room);
 }else if(room.phase==='jb-danger'){
  if(!room.challenge)stage.append(locked('You’re safe. Watch the others face their traps.'));else if(room.yourDanger!==null)stage.append(locked('Trap answer locked.'));else{const h=el('h3',room.challenge.preview?room.challenge.text:'Which code did you see?','jb-question');h.id='danger-prompt';if(!room.challenge.hideAt)h.textContent=room.challenge.text;stage.append(h);if(room.challenge.preview){const code=el('strong',room.challenge.preview,'memory-code');code.id='memory-code';stage.append(code);}const options=el('div','','jb-options');room.challenge.options.forEach((text,i)=>{const b=playButton(text,()=>act('danger',{choice:i}),'jb-option');if(room.challenge.hideAt)b.dataset.notBefore=room.challenge.hideAt;options.append(b);});stage.append(options);}lifeBoard(stage,room);
 }else if(room.phase==='jb-drawing'){
  if(room.yourDrawing)stage.append(drawingSvg(room.yourDrawing),locked('Drawing locked.'));else{stage.append(el('p',game==='thread-battle'?'A spark for your shirt graphic: '+room.drawingPrompt:room.drawingPrompt,'jb-private-prompt'));stage.append(drawingPad(strokes=>act('draw',{strokes}),`party-room.draft.${room.code}.${room.gameEpoch}.${room.round}.${room.you}`));}
 }else if(room.phase==='jb-writing'){
  if(room.yourWriting)stage.append(locked('Your writing is locked.'));else{const form=el('form','','jb-writing-form');const prompts=game==='punchline'?room.prompts:[{id:'fact',text:room.question.text}];for(const prompt of prompts){const label=el('label',prompt.text,'jb-prompt-label'),input=el('input');input.type='text';input.required=true;input.maxLength=game==='punchline'?120:80;input.dataset.prompt=prompt.id;input.autocomplete='off';label.append(input);form.append(label);}const b=playButton(game==='punchline'?'Lock responses':'Lock bluff',()=>{});b.type='submit';form.append(b);form.addEventListener('submit',e=>{e.preventDefault();const inputs=[...form.querySelectorAll('input')];act('write',game==='punchline'?{answers:Object.fromEntries(inputs.map(n=>[n.dataset.prompt,n.value]))}:{text:inputs[0].value});});stage.append(form);}
 }else if(room.phase==='jb-bluffing'){
  const pictures=room.pictures||[];if(!pictures.length)stage.append(locked());else{active=Math.min(active,pictures.length-1);stage.append(nav(pictures,()=>render(latest,client,true)));const picture=pictures[active];stage.append(drawingSvg(picture.strokes));if(picture.yourBluff)stage.append(locked('Your caption is locked. Choose another drawing above.'));else{const form=el('form','','jb-bluff-form'),label=el('label','Invent a convincing caption'),input=el('input');input.type='text';input.required=true;input.maxLength=80;const draftKey=`${room.code}:${room.gameEpoch}:${room.round}:${picture.id}`;input.value=captionDrafts.get(draftKey)||'';input.addEventListener('input',()=>captionDrafts.set(draftKey,input.value));label.append(input);const b=playButton('Lock caption',()=>{});b.type='submit';form.append(label,b);form.addEventListener('submit',e=>{e.preventDefault();act('bluff',{picture:picture.id,text:input.value});});stage.append(form);}}
 }else if(room.phase==='jb-slogans'){
  if(room.yourSlogans.length)stage.append(locked('Your slogans are locked.'));else{const form=el('form','','jb-slogan-form');for(const n of [1,2]){const label=el('label',`Slogan ${n}`),input=el('input');input.type='text';input.required=true;input.maxLength=80;label.append(input);form.append(label);}const b=playButton('Lock slogans',()=>{});b.type='submit';form.append(b);form.addEventListener('submit',e=>{e.preventDefault();act('slogans',{texts:[...form.querySelectorAll('input')].map(i=>i.value)});});stage.append(form);}
 }else if(room.phase==='jb-designing'){
  if(room.yourDesign)stage.append(locked('Your shirt is locked.'));else{let artwork=room.artworks[0]?.id,slogan=room.slogans[0]?.id;const preview=el('div','','shirt-preview'),picture=el('div','','shirt-art'),text=el('strong');preview.append(picture,text);const update=()=>{picture.replaceChildren(drawingSvg(room.artworks.find(a=>a.id===artwork)?.strokes));text.textContent=room.slogans.find(s=>s.id===slogan)?.text||'';};const gallery=el('div','','art-gallery');for(const a of room.artworks){const b=button('',()=>{artwork=a.id;for(const other of gallery.children)other.setAttribute('aria-pressed',String(other===b));update();},'art-choice');b.append(drawingSvg(a.strokes));b.setAttribute('aria-label','Choose artwork');b.setAttribute('aria-pressed',String(a.id===artwork));gallery.append(b);}const select=el('select');select.setAttribute('aria-label','Choose slogan');for(const s of room.slogans){const o=el('option',s.text);o.value=s.id;select.append(o);}select.addEventListener('change',()=>{slogan=select.value;update();});stage.append(preview,gallery,select,playButton('Lock shirt',()=>act('design',{drawing:artwork,slogan})));update();}
 }else if(room.phase==='jb-voting'){
  const entries=room.entries||[];if(entries.length){active=Math.min(active,entries.length-1);stage.append(nav(entries,()=>render(latest,client,true)));const entry=entries[active];stage.append(el('h3',entry.prompt,'jb-question'));if(entry.drawing)stage.append(drawingSvg(entry.drawing));const options=el('div','','jb-options');for(const o of entry.options){const b=playButton('',()=>act('vote',{entry:entry.id,choice:o.id}),'jb-option');if(o.drawing)b.append(drawingSvg(o.drawing));b.append(el('span',o.text));b.dataset.locked=String(entry.yourVote!==null||!entry.eligible.includes(o.id));if(entry.yourVote===o.id)b.classList.add('selected');if(!entry.eligible.includes(o.id))b.append(el('small','Your entry · cannot vote'));options.append(b);}stage.append(options);if(entry.yourVote!==null)stage.append(locked('Vote locked. Choose another matchup above.'));else if(!entry.eligible.length)stage.append(locked('You wrote these entries. The other players decide. Choose another matchup above.'));}
 }
 const ready=el('p','','jb-note');ready.id='jb-ready';stage.append(ready);
 if(room.you===room.host)stage.append(playButton('Close this stage',()=>{if(confirm('Finish this stage for everyone? Missing responses will be skipped.'))act('finish_stage');},'text-button'));tick();
 }
 function lifeBoard(stage,room){const list=el('div','','escape-board');for(const p of room.players){const lives=room.lives?.[p.id]??0;list.append(el('p',`${p.name}: ${lives?'♥'.repeat(lives):'Ghost'} · ${room.escape?.[p.id]||0} escape steps`));}stage.append(list);}
 setupParty(game,render);setInterval(tick,200);
}
