import {$,setupParty,perform,lobbyContent,roomControls,playerName} from '../../shared/party-ui.js?v=20261008-refine-1';
import {el,button,form} from '../../shared/game-tools.js?v=20261008-refine-1';
let key='',latest,client,dragging=false,localGuess=50;
const point=(v,r=220)=>{const a=Math.PI*(1-v/100);return [300+Math.cos(a)*r,260-Math.sin(a)*r];};
function dial(room){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 600 290');svg.setAttribute('class','dial');svg.setAttribute('role','img');svg.setAttribute('aria-label',`Spectrum dial. Group guess ${Math.round(room.groupGuess)} out of 100.`);
const path=(d,color)=>{const p=document.createElementNS(ns,'path');p.setAttribute('d',d);p.setAttribute('fill',color);svg.append(p);};path('M80 260 A220 220 0 0 1 520 260 L300 260 Z','#343b50');
if(room.target!==undefined){for(const [width,color] of [[12,'#edb396'],[8,'#b4c7b5'],[4,'#c8b7fb']]){const a=point(Math.max(0,room.target-width)),b=point(Math.min(100,room.target+width));path(`M300 260 L${a.join(' ')} A220 220 0 0 1 ${b.join(' ')} Z`,color);}}
if(room.phase!=='clue'){const value=dragging?localGuess:room.groupGuess,p=point(value,205);const line=document.createElementNS(ns,'line');for(const [name,v] of Object.entries({x1:300,y1:260,x2:p[0],y2:p[1],stroke:'#faf5ec','stroke-width':5,'stroke-linecap':'round'}))line.setAttribute(name,v);svg.append(line);}
const circle=document.createElementNS(ns,'circle');circle.setAttribute('cx',300);circle.setAttribute('cy',260);circle.setAttribute('r',18);circle.setAttribute('fill','#faf5ec');svg.append(circle);return svg;}
function draw(){const box=$('dial-holder');if(box)box.replaceChildren(dial(latest));const guesses=$('guess-list');if(guesses){guesses.replaceChildren(...Object.entries(latest.guesses).map(([id,value])=>el('span',`${playerName(latest,id)} · ${Math.round(value)}`,'guess-chip')));}const lock=$('lock-guess');if(lock)lock.disabled=!Object.keys(latest.guesses).length;}
function render(room,c){if(!room){key='';latest=null;return;}latest=room;client=c;roomControls(room,c);const nextKey=[room.code,room.you,room.phase,room.round,room.giver,room.host,room.spectrum?.join('|')].join(':');if(key===nextKey){if(room.phase==='lobby'&&$('start-game'))$('start-game').disabled=room.players.filter(p=>p.online).length<2;draw();return;}const oldInput=$('game-stage').querySelector('form input'),draft=oldInput?.value,focused=oldInput===document.activeElement,samePhase=key.startsWith(`${room.code}:${room.you}:${room.phase}:${room.round}:`);key=nextKey;dragging=false;const stage=$('game-stage');stage.replaceChildren();if(room.phase==='lobby'){lobbyContent(room,'wavelength');$('start-game')?.addEventListener('click',()=>perform(c,'start'));return;}
const host=room.you===room.host,giver=room.you===room.giver,participant=room.participants.includes(room.you);
if(room.phase==='finished'){stage.append(el('span','SESSION COMPLETE','eyebrow'),el('h2',`${room.totalScore} / 32`),el('p',room.totalScore>=20?'You’re on the same wavelength.':'Keep tuning in. Your next clue could be the one.','stage-copy'));const history=el('div','','guess-list');room.history.forEach(h=>history.append(el('span',`Round ${h.round}: ${h.points}`,'guess-chip')));stage.append(history);if(host)stage.append(button('Play again',()=>perform(c,'again')));return;}
stage.append(el('span',giver?'YOU ARE THE CLUE-GIVER':`${playerName(room,room.giver)} IS THE CLUE-GIVER`,'eyebrow'));
const spectrum=el('div','','spectrum');spectrum.append(el('strong',room.spectrum[0]),el('span','↔'),el('strong',room.spectrum[1]));stage.append(spectrum);const holder=el('div');holder.id='dial-holder';stage.append(holder);
if(room.phase==='clue'){stage.append(el('h2',giver?'Find a clue for the target.':'A clue is coming.'),el('p',giver?`Your private target is ${room.target.toFixed(1)} / 100. Give an example that belongs there.`:`${playerName(room,room.giver)} is finding the perfect example. The target stays hidden on your screen.`,'stage-copy'));if(giver){stage.append(form('Your clue',90,clue=>perform(c,'clue',{clue})));const swap=button(`Swap spectrum (${3-room.rerolls} left)`,()=>perform(c,'reroll'),'text-button');swap.disabled=room.rerolls>=3;stage.append(swap);}}
if(room.phase==='guess'){stage.append(el('span','THE CLUE','eyebrow'),el('h2',room.clue,'big-clue'));if(participant&&!giver){const label=el('label','','guess-control');label.append(el('span','Where does the clue belong?'));const range=el('input');range.type='range';range.min=0;range.max=100;range.value=room.guesses[room.you]??50;range.setAttribute('aria-label','Your position on the spectrum');const output=el('output',range.value);label.append(range,output);stage.append(label);range.addEventListener('input',()=>{dragging=true;localGuess=Number(range.value);output.textContent=range.value;draw();});range.addEventListener('change',async()=>{await perform(c,'guess',{value:Number(range.value)});dragging=false;draw();});const adjustments=el('div','','dial-adjustments');for(const [label,delta] of [['−1',-1],['+1',1]]){const nudge=button(label,async()=>{range.value=Math.max(0,Math.min(100,Number(range.value)+delta));dragging=true;localGuess=Number(range.value);output.textContent=range.value;draw();await perform(c,'guess',{value:localGuess});dragging=false;draw();});nudge.setAttribute('aria-label',delta<0?'Move your guess one point left':'Move your guess one point right');adjustments.append(nudge);}stage.append(adjustments);stage.append(el('p','Move your dial, then discuss. The group needle uses the median of submitted guesses.','stage-copy'));}else stage.append(el('p',giver?'Let the group discuss. Your target is private.':'You’ll join the next round. Follow the group’s discussion.','stage-copy'));const list=el('div','','guess-list');list.id='guess-list';stage.append(list);if(host){const lock=button('Lock group guess & reveal',()=>perform(c,'reveal'));lock.id='lock-guess';stage.append(lock);}}
if(room.phase==='reveal'){const result=room.result;stage.append(el('h2',result.skipped?'Round skipped':`+${result.points} points`),el('p',result.skipped?result.reason:`Group: ${result.guess.toFixed(1)} · Target: ${result.target.toFixed(1)} · Total: ${room.totalScore}`,'stage-copy'));if(room.clue)stage.append(el('p',`“${room.clue}”`,'reveal-clue'));if(host)stage.append(button(room.round===room.maxRounds?'See final score':'Next round',()=>perform(c,'next')));else stage.append(el('p','Waiting for the host to continue.','stage-copy'));}if(samePhase&&draft!==undefined){const input=stage.querySelector('form input');if(input){input.value=draft;if(focused)input.focus();}}draw();}
setupParty('wavelength',render);
