import {$,setupParty,perform,lobbyContent,roomControls,notice} from '../../shared/party-ui.js';
import {el,button,scores} from '../../shared/game-tools.js';
import {raceClock,paintRaceStatus,standings} from '../../shared/race-ui.js';
import {sudokuPeers,sudokuConflicts,validDraft} from './rules.js';
let latest,client,key='',board='',notes=Array(81).fill(0),selected=0,pencil=false,dirty=false,revision=0,saveTimer=null,busy=false,undoStack=[],storageKey='';
function unlocked(){return latest?.phase==='race'&&latest.participants.includes(latest.you)&&!latest.ready.includes(latest.you)&&Date.now()/1000+latest.serverTimeOffset>=latest.startsAt&&Date.now()/1000+latest.serverTimeOffset<latest.deadline;}
function store(){try{localStorage.setItem(storageKey,JSON.stringify({board,notes}));}catch{}}
function scheduleSave(){store();clearTimeout(saveTimer);saveTimer=setTimeout(save,350);}
async function save(){if(!dirty||!unlocked())return;const currentRevision=revision,currentBoard=board;try{await client.act('board',{board:currentBoard});if(revision===currentRevision){dirty=false;if($('save-status'))$('save-status').textContent='Board saved';}}catch(e){if(latest?.phase==='race'){notice(e.message);if($('save-status'))$('save-status').textContent='Edits kept here · retrying';clearTimeout(saveTimer);saveTimer=setTimeout(save,1800);}}}
function select(index,focus=false){selected=index;paint();if(focus)$(`cell-${index}`)?.focus();}
function edit(value){if(!unlocked()||busy||latest.puzzle.givens[selected]!=='0')return;undoStack.push({board,notes:[...notes]});if(undoStack.length>100)undoStack.shift();
if(pencil&&value!=='0'){if(board[selected]!=='0'){undoStack.pop();return;}notes[selected]^=1<<value;store();}else{board=board.slice(0,selected)+value+board.slice(selected+1);notes[selected]=0;dirty=true;revision++;scheduleSave();}paint();}
function undo(){if(!unlocked()||busy||!undoStack.length)return;const prev=undoStack.pop();board=prev.board;notes=prev.notes;dirty=true;revision++;scheduleSave();paint();}
function paint(){if(!latest||latest.phase!=='race'||!board||!$('cell-0'))return;const peers=sudokuPeers(selected),conflicts=sudokuConflicts(board),picked=board[selected];for(let i=0;i<81;i++){const cell=$(`cell-${i}`);if(!cell)continue;cell.disabled=busy||!unlocked();cell.classList.toggle('selected',i===selected);cell.classList.toggle('peer',peers.has(i));cell.classList.toggle('same-digit',picked!=='0'&&board[i]===picked);cell.classList.toggle('conflict',conflicts.has(i));cell.tabIndex=i===selected?0:-1;cell.setAttribute('aria-selected',String(i===selected));const clue=latest.puzzle.givens[i]!=='0';cell.setAttribute('aria-label',`Row ${Math.floor(i/9)+1}, column ${i%9+1}, ${board[i]==='0'?'empty':board[i]}${clue?', starting clue':''}${conflicts.has(i)?', repeated digit':''}`);
const value=cell.querySelector('.cell-value'),pencils=cell.querySelector('.cell-notes');value.textContent=board[i]==='0'?'':board[i];pencils.hidden=board[i]!=='0'||!notes[i];pencils.querySelectorAll('span').forEach((n,j)=>n.textContent=notes[i]&(1<<(j+1))?j+1:'');}
const editable=unlocked()&&!busy&&latest.puzzle.givens[selected]==='0';for(const control of document.querySelectorAll('.digit-key'))control.disabled=!editable;$('pencil-mode').setAttribute('aria-pressed',String(pencil));$('pencil-mode').textContent=pencil?'Notes on':'Notes off';$('undo-grid').disabled=!unlocked()||busy||!undoStack.length;$('hint-grid').disabled=!editable||latest.hints>=3;$('finish-grid').disabled=!unlocked()||busy||board.includes('0');$('pass-grid').disabled=!unlocked()||busy;$('pencil-mode').disabled=!unlocked()||busy;$('grid-summary').textContent=latest.ready.includes(latest.you)?latest.finishTime!==null?'Finished! Waiting for the other racers.':'Your round is locked.':`${81-board.split('0').length+1} / 81 cells filled${conflicts.size?` · ${conflicts.size} cells with conflicts`:''}`;$('race-hint').textContent=`${latest.hints}/3 hints used · +30 seconds each.`;if($('save-status'))$('save-status').textContent=dirty?'Saving edits…':'Board saved';}
async function action(type){if(busy||!unlocked())return;clearTimeout(saveTimer);busy=true;paint();try{const result=await client.act(type,{board,index:selected});if(result&&['hint','finish'].includes(type)){board=result.room.board||board;dirty=false;revision++;if(type==='hint')notes[selected]=0;store();}notice('');}catch(e){notice(e.message);if(dirty)scheduleSave();}finally{busy=false;paint();}}
function makeGrid(givens,solution=null){const grid=el('div','','sudoku-grid');grid.setAttribute('role','grid');grid.setAttribute('aria-label',solution?'Sudoku solution':'Your Sudoku board');for(let r=0;r<9;r++){const row=el('div','','sudoku-row');row.setAttribute('role','row');for(let c=0;c<9;c++){const i=r*9+c;let cell;if(solution){cell=el('div',solution[i],'sudoku-cell');cell.setAttribute('role','gridcell');cell.setAttribute('aria-label',`Row ${r+1}, column ${c+1}, ${solution[i]}`);}else{cell=button('',()=>select(i),'sudoku-cell');cell.id=`cell-${i}`;cell.setAttribute('role','gridcell');const value=el('span','','cell-value'),pencils=el('span','','cell-notes');pencils.setAttribute('aria-hidden','true');for(let digit=1;digit<=9;digit++)pencils.append(el('span'));cell.append(value,pencils);}
cell.classList.toggle('given',givens[i]!=='0');cell.classList.toggle('box-right',c===2||c===5);cell.classList.toggle('box-bottom',r===2||r===5);row.append(cell);}grid.append(row);}return grid;}
function tick(){if(latest?.phase==='race'){raceClock(latest);paintRaceStatus(latest);paint();}}
function render(room,c){latest=room;client=c;room.serverTimeOffset=room.serverTime-Date.now()/1000;roomControls(room,c);const signature=[room.code,room.phase,room.round,room.host,room.participants.includes(room.you)].join(':');if(key===signature){if(room.phase==='race'&&!dirty&&!busy&&room.board&&board!==room.board){board=room.board;store();}tick();return;}const newRound=!key.startsWith(`${room.code}:race:${room.round}:`);key=signature;clearTimeout(saveTimer);const stage=$('game-stage');stage.replaceChildren();const host=room.you===room.host;
if(room.phase==='lobby'){lobbyContent(room,'sudoku-race');$('start-game')?.addEventListener('click',()=>perform(c,'start',{difficulty:$('puzzle-difficulty').value,rounds:Number($('puzzle-rounds').value)}));return;}
if(room.phase==='finished'){stage.append(el('h2','Every square settled.'),scores(room));if(host)stage.append(button('Race again',()=>perform(c,'again',{difficulty:room.difficulty,rounds:room.maxRounds})));return;}
const heading=el('div','','race-heading'),copy=el('div');copy.append(el('h2',room.phase==='race'?'Find your way through.':'The grid, solved.'),el('p',`${room.difficulty} · ${81-room.puzzle.givens.split('0').length+1} starting clues`,'race-settings'));heading.append(copy);if(room.phase==='race'){const clock=el('strong','','race-clock');clock.id='race-clock';heading.append(clock);}stage.append(heading);
if(room.phase==='reveal'){if(room.result.skipped)stage.append(el('p','The host skipped this puzzle.'));else stage.append(makeGrid(room.puzzle.givens,room.result.solution),standings(room),el('p','Times include a 30-second penalty per hint.','race-note'));stage.append(scores(room));if(host)stage.append(button(room.round===room.maxRounds?'Final scores':'Next puzzle',()=>perform(c,'next')));return;}
if(room.participants.includes(room.you)){
if(newRound){board=room.board;notes=Array(81).fill(0);undoStack=[];pencil=false;dirty=false;revision=0;storageKey=`party-room.sudoku.${room.code}.${room.you}.${room.round}.${room.puzzle.givens}`;try{const saved=JSON.parse(localStorage.getItem(storageKey)||'null');if(saved&&validDraft(saved.board,room.puzzle.givens)){if(!room.ready.includes(room.you)){board=saved.board;dirty=board!==room.board;}if(Array.isArray(saved.notes)&&saved.notes.length===81)notes=saved.notes.map(n=>Number.isInteger(n)?n&1022:0);}}catch{}selected=room.puzzle.givens.indexOf('0');if(dirty)saveTimer=setTimeout(save,6000);}
const summary=el('p','','race-note');summary.id='grid-summary';stage.append(summary,makeGrid(room.puzzle.givens));const pad=el('div','','number-pad');for(let digit=1;digit<=9;digit++)pad.append(button(String(digit),()=>edit(String(digit)),'digit-key'));pad.append(button('⌫',()=>edit('0'),'digit-key erase-key'));stage.append(pad);
const controls=el('div','','race-actions');for(const [id,text,fn] of [['pencil-mode','Notes off',()=>{pencil=!pencil;paint();}],['undo-grid','Undo',undo],['hint-grid','Hint +30s',()=>action('hint')],['finish-grid','Finish race',()=>action('finish')],['pass-grid','Pass puzzle',()=>{if(confirm('Lock your board and pass this puzzle?'))action('give_up');}]]){const b=button(text,fn,id==='finish-grid'?'primary':'secondary-action');b.id=id;controls.append(b);}stage.append(controls);const hint=el('p','','race-hint');hint.id='race-hint';const saveLabel=el('p','','race-note');saveLabel.id='save-status';saveLabel.setAttribute('aria-live','polite');stage.append(hint,el('p','Digits 1–9 · arrows to move · N for notes · Backspace to erase. Your board stays private.','race-note'),saveLabel);
}else stage.append(el('p','You’ll race next round. Progress is visible below.'));
const progress=el('div','','race-players');progress.id='race-players';stage.append(progress);if(host)stage.append(button('End race and reveal',()=>{if(confirm('End the race for everyone and show the solution?'))perform(c,'end_race');},'text-button'));tick();if(dirty&&unlocked())scheduleSave();}
document.addEventListener('keydown',event=>{if(!unlocked()||!$('cell-0')||/INPUT|TEXTAREA|SELECT/.test(event.target.tagName)||$('help-dialog').open)return;const row=Math.floor(selected/9),col=selected%9;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key)){event.preventDefault();const index=event.key==='ArrowLeft'?row*9+Math.max(0,col-1):event.key==='ArrowRight'?row*9+Math.min(8,col+1):event.key==='ArrowUp'?Math.max(0,row-1)*9+col:Math.min(8,row+1)*9+col;select(index,true);}else if(/^[1-9]$/.test(event.key)){event.preventDefault();edit(event.key);}else if(['0','Backspace','Delete'].includes(event.key)){event.preventDefault();edit('0');}else if(event.key.toLowerCase()==='n'){event.preventDefault();pencil=!pencil;paint();}else if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();undo();}});
setupParty('sudoku-race',render);setInterval(tick,250);
