import {$,setupParty,perform,lobbyContent,roomControls,notice} from '../../shared/party-ui.js';
import {el,button,scores} from '../../shared/game-tools.js';
import {raceClock,paintRaceStatus,standings} from '../../shared/race-ui.js';
import {inspectWord} from './rules.js';
let latest,client,key='',pathKey='',dictionary=null,busy=false;
fetch(new URL('../../api/word-circuit-words.txt',import.meta.url)).then(r=>{if(!r.ok)throw Error();return r.text();}).then(text=>{dictionary=new Set(text.trim().split(/\s+/));feedback();}).catch(()=>{});
function feedback(){const input=$('next-word'),output=$('word-feedback');if(input&&output&&latest?.path){output.textContent=inspectWord(input.value,latest.path,dictionary);output.classList.toggle('valid',output.textContent==='Valid next word.');}}
function route(words){const list=el('ol','','word-chain');words.forEach((word,i)=>{const item=el('li'),tiles=el('span','','letter-word');[...word].forEach((c,j)=>tiles.append(el('span',c,i&&words[i-1][j]!==c?'changed-letter':'')));item.append(tiles);list.append(item);});return list;}
async function act(action,payload={}){if(busy)return;busy=true;update();try{await client.act(action,payload);notice('');if(action==='word'&&$('next-word'))$('next-word').value='';}catch(e){notice(e.message);}finally{busy=false;update();}}
function update(){if(!latest||latest.phase!=='race')return;raceClock(latest);paintRaceStatus(latest);const locked=latest.ready.includes(latest.you)||!latest.participants.includes(latest.you),before=Date.now()/1000+latest.serverTimeOffset<latest.startsAt,expired=Date.now()/1000+latest.serverTimeOffset>=latest.deadline;
for(const id of ['next-word','add-word','undo-word','restart-word','hint-word','lock-word','pass-word'])if($(id))$(id).disabled=locked||before||expired||busy;
if($('undo-word'))$('undo-word').disabled=locked||before||expired||busy||latest.path.length<2;if($('hint-word'))$('hint-word').disabled=locked||before||expired||busy||latest.hints>=3||latest.path.at(-1)===latest.puzzle.end;
if(latest.path){const serial=latest.path.join('|');if(serial!==pathKey){pathKey=serial;$('your-chain')?.replaceChildren(route(latest.path));}const found=latest.bestPath;$('route-summary').textContent=found?`Best saved: ${found.length-1} changes. Keep improving or lock your route.`:`${latest.path.length-1} changes so far. Aim for ${latest.puzzle.optimal}.`;$('race-hint').textContent=latest.hint?`Try ${latest.hint.word.toUpperCase()} next. (${latest.hints}/3 hints)`:`${latest.hints}/3 hints used · each costs 2 points.`;if($('lock-word'))$('lock-word').hidden=!found;if($('pass-word'))$('pass-word').hidden=!!found;}
if($('next-word'))$('next-word').maxLength=latest.puzzle.start.length;feedback();}
function render(room,c){if(!room){key='';latest=null;return;}latest=room;client=c;room.serverTimeOffset=room.serverTime-Date.now()/1000;roomControls(room,c);const signature=[room.code,room.phase,room.round,room.host,room.participants.includes(room.you)].join(':');if(key===signature){update();return;}key=signature;pathKey='';const stage=$('game-stage');stage.replaceChildren();const host=room.host===room.you;
if(room.phase==='lobby'){lobbyContent(room,'word-circuit');$('start-game')?.addEventListener('click',()=>perform(c,'start',{difficulty:$('puzzle-difficulty').value,rounds:Number($('puzzle-rounds').value)}));return;}
if(room.phase==='finished'){stage.append(el('h2','Connections made.'),scores(room));if(host)stage.append(button('Play again',()=>perform(c,'again',{difficulty:room.difficulty,rounds:room.maxRounds})));return;}
const heading=el('div','','race-heading'),copy=el('div');copy.append(el('h2',`${room.puzzle.start.toUpperCase()} → ${room.puzzle.end.toUpperCase()}`),el('p',`${room.puzzle.start.length} letters · ${room.difficulty} · shortest route: ${room.puzzle.optimal} changes`,'race-settings'));heading.append(copy);if(room.phase==='race'){const clock=el('strong','','race-clock');clock.id='race-clock';heading.append(clock);}stage.append(heading);
if(room.phase==='reveal'){if(room.result.skipped){stage.append(el('p','The host skipped this pair.'));}else{stage.append(el('h3','One shortest route'),route(room.result.solution),standings(room,true));}stage.append(scores(room));if(host)stage.append(button(room.round===room.maxRounds?'Final scores':'Next pair',()=>perform(c,'next')));return;}
if(!room.participants.includes(room.you)){stage.append(el('p','You’ll race next round. Watch the room’s progress.'));}else{
const chain=el('div');chain.id='your-chain';const summary=el('p','','race-note');summary.id='route-summary';stage.append(chain,summary);
const form=el('form','','word-entry'),label=el('label','Next word'),input=el('input');input.id='next-word';input.type='text';input.autocomplete='off';input.spellcheck=false;input.autocapitalize='none';input.setAttribute('autocorrect','off');input.enterKeyHint='go';input.placeholder='Change one letter…';input.required=true;input.setAttribute('aria-describedby','word-feedback');input.addEventListener('input',feedback);label.append(input);const add=button('Add word',()=>{});add.type='submit';add.id='add-word';form.append(label,add);form.addEventListener('submit',e=>{e.preventDefault();act('word',{word:input.value});});const output=el('p','','word-feedback');output.id='word-feedback';output.setAttribute('aria-live','polite');stage.append(form,output);
const controls=el('div','','race-actions');for(const [id,label,action] of [['undo-word','Undo','undo'],['restart-word','Restart route','restart_path'],['hint-word','Hint −2 points','hint'],['lock-word','Lock best route','lock'],['pass-word','Pass this pair','give_up']]){const b=button(label,()=>act(action),id==='lock-word'?'primary':'secondary-action');b.id=id;controls.append(b);}const hint=el('p','','race-hint');hint.id='race-hint';stage.append(controls,hint,el('p','Your route stays private until reveal. Every added word is checked by the game dictionary.','race-note'));}
const progress=el('div','','race-players');progress.id='race-players';stage.append(progress);if(host)stage.append(button('End race and reveal',()=>{if(confirm('End the round for everyone and reveal all routes?'))act('end_race');},'text-button'));update();}
setupParty('word-circuit',render);setInterval(()=>{if(latest?.phase==='race')update();},250);
