import {$,setupParty,perform,lobbyContent,roomControls,playerName} from '../../shared/party-ui.js?v=20261008-deduction-1';
import {el,button,form,scores} from '../../shared/game-tools.js?v=20261008-deduction-1';
let key='',latest,open=false;
function privateCard(room){const card=button('',()=>{open=!open;paintCard(room,card);},'secret-card');paintCard(room,card);return card;}
function paintCard(room,card){card.replaceChildren();card.setAttribute('aria-expanded',String(open));card.append(el('span',open?(room.role==='imposter'?'YOU ARE THE IMPOSTER':'YOUR SECRET WORD'):'YOUR PRIVATE CARD','eyebrow'),el('strong',open?(room.role==='imposter'?'Blend in.':room.word):'Tap to peek.'),el('small',open?'Tap to hide · Keep this to yourself':`Category: ${room.category}`));}
function render(room,c){if(!room){key='';latest=null;open=false;return;}latest=room;roomControls(room,c);const nextKey=[room.code,room.you,room.phase,room.round,room.turn,room.host,room.yourVote,Object.keys(room.clues).length,room.voteCount,room.phase==='lobby'?'':room.players.map(p=>`${p.id}:${p.online}`).join(',')].join(':');if(key===nextKey){if(room.phase==='lobby'&&$('start-game'))$('start-game').disabled=room.players.filter(p=>p.online).length<3;return;}const oldInput=$('game-stage').querySelector('form input'),draft=oldInput?.value,focused=oldInput===document.activeElement;const samePhase=key.startsWith(`${room.code}:${room.you}:${room.phase}:${room.round}:`);if(!samePhase)open=false;key=nextKey;const stage=$('game-stage');stage.replaceChildren();if(room.phase==='lobby'){lobbyContent(room,'imposter');$('start-game')?.addEventListener('click',()=>perform(c,'start',{category:$('category').value}));return;}
const host=room.you===room.host,participant=room.participants.includes(room.you);
if(room.phase==='finished'){stage.append(el('span','SESSION COMPLETE','eyebrow'),el('h2','Who fooled the room?'),scores(room));if(host)stage.append(button('Play again',()=>perform(c,'again')));return;}
if(participant&&['clues','vote','last_guess'].includes(room.phase))stage.append(privateCard(room));
if(room.phase==='clues'){stage.append(el('h2',room.turn===room.you?'Your turn. Make it subtle.':`${playerName(room,room.turn)} is giving a clue.`),el('p',participant?'Give a clue that proves you know the word. Don’t make it too easy for the imposter.':'You’ll join next round. Watch the clues.','stage-copy'));if(room.turn===room.you)stage.append(form('One word or short phrase',40,clue=>perform(c,'clue',{clue})));}
if(['clues','vote','last_guess','reveal'].includes(room.phase)){const clues=el('div','','clue-list');for(const id of room.order){const row=el('div','','clue-row');row.classList.toggle('current',room.phase==='clues'&&room.turn===id);row.append(el('span',playerName(room,id)),el('strong',room.clues[id]||'…'));clues.append(row);}stage.append(clues);}
if(room.phase==='vote'){stage.append(el('h2',room.yourVote?'Your vote is locked.':'Who is the imposter?'),el('p',`${room.voteCount} / ${room.participants.length} votes in. Votes stay private until the reveal.`,'stage-copy'));if(participant&&!room.yourVote){const votes=el('div','','vote-grid');for(const id of room.participants.filter(id=>id!==room.you))votes.append(button(playerName(room,id),()=>perform(c,'vote',{suspect:id}),'vote-choice'));stage.append(votes);}if(host){const remaining=room.participants.filter(id=>!room.voted.includes(id));if(remaining.every(id=>!room.players.find(p=>p.id===id)?.online))stage.append(button('Finish vote with remaining players',()=>perform(c,'finish_vote'),'text-button'));}}
if(room.phase==='last_guess'){stage.append(el('h2',`${playerName(room,room.imposter)} was caught.`),el('p',room.you===room.imposter?'One last chance: guess the secret word to steal the round.':'The imposter gets one final guess at the secret word.','stage-copy'));if(room.you===room.imposter){const node=form('Guess the secret word',40,guess=>perform(c,'final_guess',{guess}));node.querySelector('button').textContent='Lock final guess';stage.append(node);}else if(host&&!room.players.find(p=>p.id===room.imposter)?.online)stage.append(button('Finish after imposter disconnects',()=>perform(c,'finish_guess'),'text-button'));}
if(room.phase==='reveal'){stage.append(el('span','THE SECRET WORD','eyebrow'),el('h2',room.word,'revealed-word'),el('p',`Imposter: ${playerName(room,room.imposter)}`,'imposter-name'));stage.append(el('h3',room.result.skipped?'Round skipped':room.result.imposterWins?'The imposter wins.':'The group wins.'),el('p',room.result.reason,'stage-copy'));if(room.result.finalGuess)stage.append(el('p',`Final guess: ${room.result.finalGuess}`));const counts=el('div','','vote-counts');for(const [id,count] of Object.entries(room.result.counts||{}))counts.append(el('span',`${playerName(room,id)}: ${count} ${count===1?'vote':'votes'}`));stage.append(counts,scores(room));if(host)stage.append(button(room.round===room.maxRounds?'See final scores':'Next round',()=>perform(c,'next')));else stage.append(el('p','Waiting for the host to continue.','stage-copy'));}
if(samePhase&&draft!==undefined){const input=stage.querySelector('form input');if(input){input.value=draft;if(focused)input.focus();}}
}
setupParty('imposter',render);
