"""Rebuild verified puzzle banks. No runtime Python is required on hosting.
Dictionary: SCOWL 2020.12.07 sizes <=60, English + American + British,
lowercase ASCII words of length 3–6, with a small explicit-content filter.
Endpoint pool: same sources through size35. See api/WORDLIST-LICENSE.txt.
"""
from pathlib import Path
from collections import defaultdict, deque
import random, json
ROOT=Path(__file__).resolve().parent.parent
rng=random.Random(1062026)
words=set((ROOT/'api/word-circuit-words.txt').read_text().split())
common=set((ROOT/'tools/circuit-common.txt').read_text().split()) & words
buckets=defaultdict(list)
for word in sorted(words):
 for i in range(len(word)):buckets[word[:i]+'*'+word[i+1:]].append(word)
graph={w:sorted({n for i in range(len(w)) for n in buckets[w[:i]+'*'+w[i+1:]] if n!=w}) for w in sorted(words)}
circuit={};used=set()
for mode,lengths,low,high in [('easy',[4],3,4),('classic',[4,5],4,6),('expert',[5,6],6,9)]:
 pool=sorted(w for w in common if len(w) in lengths and graph[w])
 rng.shuffle(pool);deck=[]
 for start in pool:
  parents={start:None};distance={start:0};queue=deque([start])
  while queue:
   w=queue.popleft()
   if distance[w]>=high:continue
   for n in graph[w]:
    if n not in parents:parents[n]=w;distance[n]=distance[w]+1;queue.append(n)
  ends=[w for w in sorted(parents) if w in common and low<=distance[w]<=high and sum(a!=b for a,b in zip(start,w))>=min(3,len(start)) and tuple(sorted([start,w])) not in used]
  rng.shuffle(ends)
  for end in ends[:6]:
   route=[];w=end
   while w is not None:route.append(w);w=parents[w]
   route.reverse();used.add(tuple(sorted([start,end])))
   deck.append({'id':f'{mode}-{len(deck)+1}','start':start,'end':end,'solution':route,'optimal':len(route)-1})
   if len(deck)>=1800:break
  if len(deck)>=1800:break
 assert len(deck)>=500,(mode,len(deck))
 circuit[mode]=deck
 print(mode,len(deck),flush=True)

def solve_count(grid,limit=2):
 rows=[0]*9;cols=[0]*9;boxes=[0]*9
 for i,v in enumerate(grid):
  if not v:continue
  r,c=divmod(i,9);b=r//3*3+c//3;bit=1<<v
  if (rows[r]|cols[c]|boxes[b])&bit:return 0
  rows[r]|=bit;cols[c]|=bit;boxes[b]|=bit
 def visit():
  best=-1;bits=0;count=10
  for i,v in enumerate(grid):
   if v:continue
   r,c=divmod(i,9);b=r//3*3+c//3;opts=1022&~(rows[r]|cols[c]|boxes[b]);n=bin(opts).count('1')
   if n==0:return 0
   if n<count:best,bits,count=i,opts,n
   if n==1:break
  if best<0:return 1
  r,c=divmod(best,9);b=r//3*3+c//3;total=0
  while bits:
   bit=bits&-bits;bits-=bit;grid[best]=bit.bit_length()-1
   rows[r]|=bit;cols[c]|=bit;boxes[b]|=bit
   total+=visit()
   rows[r]^=bit;cols[c]^=bit;boxes[b]^=bit;grid[best]=0
   if total>=limit:return limit
  return total
 return visit()

def solved_grid():
 bands=rng.sample(range(3),3);stacks=rng.sample(range(3),3)
 rows=[3*b+r for b in bands for r in rng.sample(range(3),3)]
 cols=[3*b+c for b in stacks for c in rng.sample(range(3),3)]
 digits=rng.sample(range(1,10),9)
 return [digits[(r*3+r//3+c)%9] for r in rows for c in cols]
sudoku={}
for mode,target in [('easy',42),('medium',34),('hard',28)]:
 deck=[];attempt=0
 while len(deck)<150:
  attempt+=1;solution=solved_grid();grid=solution.copy();positions=list(range(81));rng.shuffle(positions)
  for i in positions:
   if sum(v!=0 for v in grid)<=target:break
   old=grid[i];grid[i]=0
   if solve_count(grid.copy())!=1:grid[i]=old
  if sum(v!=0 for v in grid)>target:continue
  assert solve_count(grid.copy())==1
  deck.append({'id':f'{mode}-{len(deck)+1}','givens':''.join(map(str,grid)),'solution':''.join(map(str,solution))})
 sudoku[mode]=deck;print('sudoku',mode,len(deck),'attempts',attempt,flush=True)
data={'circuit':circuit,'sudoku':sudoku,'dictionaryCount':len(words)}
# PHP-only bank: solutions must never be delivered as a public JSON asset.
(ROOT/'api/puzzle-data.php').write_text("<?php\n// Generated by tools/generate-puzzles.py. Solutions stay on the server.\nfunction party_puzzle_data(): array { static $data; if ($data === null) $data=json_decode(<<<'PUZZLES'\n"+json.dumps(data,separators=(',',':'))+"\nPUZZLES\n,true); return $data; }\n")
print('Written puzzle-data.php',flush=True)
