<?php
function party_alien_vocabulary(): array {
 return [
 'noun'=>[
 ['cat','🐈'],['dog','🐕'],['fox','🦊'],['owl','🦉'],['bear','🐻'],['frog','🐸'],['duck','🦆'],['whale','🐋'],['shark','🦈'],['crab','🦀'],['bee','🐝'],['ant','🐜'],['snail','🐌'],['rabbit','🐇'],['turtle','🐢'],['penguin','🐧'],['panda','🐼'],['koala','🐨'],['lion','🦁'],['tiger','🐯'],['wolf','🐺'],['horse','🐎'],['cow','🐄'],['pig','🐖'],['goat','🐐'],['sheep','🐑'],['deer','🦌'],['bat','🦇'],['mouse','🐁'],['hedgehog','🦔'],['squirrel','🐿️'],['octopus','🐙'],['squid','🦑'],['lobster','🦞'],['butterfly','🦋'],['dragon','🐉'],['robot','🤖'],['alien','👽'],['wizard','🧙'],['pirate','🏴‍☠️'],['astronaut','🧑‍🚀'],['ghost','👻'],['snowman','⛄'],['vampire','🧛'],['mermaid','🧜'],['ninja','🥷'],['clown','🤡'],['unicorn','🦄'],['dinosaur','🦕'],['peacock','🦚'],['flamingo','🦩'],['parrot','🦜'],['eagle','🦅'],['seal','🦭'],['camel','🐪'],['giraffe','🦒'],['zebra','🦓'],['elephant','🐘'],['gorilla','🦍'],['otter','🦦'],['raccoon','🦝'],['skunk','🦨'],['badger','🦡'],['beaver','🦫'],['kangaroo','🦘'],['rooster','🐓'],['turkey','🦃'],['lizard','🦎'],['crocodile','🐊'],['monkey','🐒'],['fairy','🧚'],['genie','🧞'],['ogre','👹'],['elf','🧝'],['goblin','👺'],['detective','🕵️'],['chef','🧑‍🍳'],['artist','🧑‍🎨'],['juggler','🤹'],['diver','🤿']],
 'adj'=>array_map(fn($v)=>[$v,''],['red','blue','green','yellow','purple','orange','pink','silver','golden','tiny','giant','sleepy','happy','grumpy','shiny','fuzzy','striped','spotted','brave','quiet','noisy','hungry','curious','dizzy','gentle','fancy','muddy','silly','invisible','glowing','sparkly','fast','slow','young','old','friendly','nervous','proud','puzzled','soggy']),
 'verb'=>array_map(fn($v)=>[$v,''],['follows','chases','greets','helps','watches','finds','hugs','tickles','carries','avoids','teaches','rescues','paints','photographs','copies','surprises','admires','cheers for','listens to','dances with','laughs with','waves to','waits for','looks for']),
 'number'=>[['one',''],['two',''],['three',''],['four',''],['five',''],['six',''],['seven',''],['eight',''],['nine','']]];
}
function party_quest_fields(): array {return [
 'job'=>['label'=>'Role','question'=>'Is the suspect a','values'=>['chef','pilot','gardener','librarian','magician','musician','inventor','painter','detective','astronaut','archaeologist','juggler']],
 'place'=>['label'=>'Last seen','question'=>'Was the suspect last seen in the','values'=>['greenhouse','observatory','kitchen','library','workshop','gallery','garden','theater','aquarium','lobby','rooftop','ballroom']],
 'color'=>['label'=>'Coat','question'=>'Was the suspect wearing a','values'=>['red coat','blue coat','green coat','yellow coat','purple coat','orange coat','pink coat','silver coat']],
 'item'=>['label'=>'Carrying','question'=>'Was the suspect carrying a','values'=>['camera','umbrella','map','notebook','lantern','toolbox','violin','telescope','backpack','magnifying glass','bouquet','sketchbook']],
 'drink'=>['label'=>'Drink','question'=>'Was the suspect drinking','values'=>['tea','coffee','lemonade','cocoa','water','orange juice','apple juice','milk','berry soda','mint tea']],
 'time'=>['label'=>'Arrived','question'=>'Did the suspect arrive at','values'=>['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00']]];}
function party_quest_stories(): array {
 $venues=['museum','space station','magic academy','island resort','robot convention','royal palace','aquarium','film studio','science fair','mountain lodge','theme park','opera house','art auction','botanical garden','train station','sports arena','secret laboratory','costume party','cooking contest','book festival'];
 $treasures=['golden trophy','ancient map','moon rock','royal crown','robot battery','prize pumpkin','tiny spaceship','rare fossil','crystal compass','silver microphone','championship medal','magic teapot','secret recipe','diamond chess piece','clockwork bird','glowing meteorite','painting of a penguin','giant emerald','signed first edition','miniature submarine'];
 $incidents=[['vanished','Someone borrowed the %s without asking.'],['swapped','Someone replaced the %s with a rubber duck.'],['hidden','Someone hid the %s inside a cereal box.'],['decorated','Someone covered the %s in glitter.'],['mailed','Someone mailed the %s to the wrong address.'],['renamed','Someone relabeled the %s as “probably a potato.”'],['moved','Someone moved the %s onto the roof.'],['shrunk','Someone shrank the %s with an experimental gadget.']];
 $out=[];foreach($venues as $venue)foreach($treasures as $treasure)foreach($incidents as [$kind,$text]){$story=sprintf($text,$treasure);$out[]=['key'=>'quest:'.$venue.'|'.$treasure.'|'.$kind,'title'=>ucfirst($venue).' mystery','text'=>$story.' Everyone’s visitor details are below. One visitor is responsible.'];}return $out;
}
